// Code generated by zapgen; DO NOT EDIT.
// source: xchain.zap

package xchain

import (
	zap "github.com/zap-proto/go"
)

const (
	signedUnsignedOff        = 0
	signedCredentialCountOff = 8
	signedCredentialBytesOff = 12
	signedSize               = 20
)

// Signed is a zero-copy view into a ZAP-encoded Signed message.
type Signed struct{ o zap.Object }

// WrapSigned parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapSigned(b []byte) (Signed, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Signed{}, err
	}
	return Signed{o: m.Root()}, nil
}

func (t Signed) Unsigned() []byte        { return t.o.Bytes(signedUnsignedOff) }
func (t Signed) CredentialCount() uint32 { return t.o.Uint32(signedCredentialCountOff) }
func (t Signed) CredentialBytes() []byte { return t.o.Bytes(signedCredentialBytesOff) }

// SignedInput collects the field values for NewSigned.
type SignedInput struct {
	Unsigned        []byte
	CredentialCount uint32
	CredentialBytes []byte
}

// NewSigned builds a ZAP-encoded Signed message from in and returns the bytes.
func NewSigned(in SignedInput) []byte {
	b := zap.NewBuilderV2(256)
	ob := b.StartObject(signedSize)
	ob.SetBytes(signedUnsignedOff, in.Unsigned)
	ob.SetUint32(signedCredentialCountOff, in.CredentialCount)
	ob.SetBytes(signedCredentialBytesOff, in.CredentialBytes)
	ob.FinishAsRoot()
	return b.Finish()
}

const (
	baseNetworkIDOff    = 0
	baseBlockchainIDOff = 8
	baseOutsOff         = 40
	baseInsOff          = 48
	baseMemoOff         = 56
	baseSize            = 64
)

// Base is a zero-copy view into a ZAP-encoded Base message.
type Base struct{ o zap.Object }

// WrapBase parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapBase(b []byte) (Base, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Base{}, err
	}
	return Base{o: m.Root()}, nil
}

func (t Base) NetworkID() uint32 { return t.o.Uint32(baseNetworkIDOff) }
func (t Base) BlockchainID() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(baseBlockchainIDOff, 32))
	return out
}
func (t Base) Outs() PtrList { return PtrList{l: t.o.ListStride(baseOutsOff, ptrSize)} }
func (t Base) Ins() PtrList  { return PtrList{l: t.o.ListStride(baseInsOff, ptrSize)} }
func (t Base) Memo() []byte  { return t.o.Bytes(baseMemoOff) }

// BaseInput collects the field values for NewBase.
type BaseInput struct {
	NetworkID    uint32
	BlockchainID [32]byte
	Outs         [][]byte
	Ins          [][]byte
	Memo         []byte
}

// NewBase builds a ZAP-encoded Base message from in and returns the bytes.
func NewBase(in BaseInput) []byte {
	b := zap.NewBuilderV2(256)
	outsAt := 0
	if len(in.Outs) > 0 {
		lb := b.StartList(ptrSize)
		for _, elem := range in.Outs {
			var rec [ptrSize]byte
			copy(rec[:], elem)
			lb.AddBytes(rec[:])
		}
		outsAt = lb.FinishOffset()
	}
	insAt := 0
	if len(in.Ins) > 0 {
		lb := b.StartList(ptrSize)
		for _, elem := range in.Ins {
			var rec [ptrSize]byte
			copy(rec[:], elem)
			lb.AddBytes(rec[:])
		}
		insAt = lb.FinishOffset()
	}
	ob := b.StartObject(baseSize)
	ob.SetUint32(baseNetworkIDOff, in.NetworkID)
	ob.SetBytesFixed(baseBlockchainIDOff, in.BlockchainID[:])
	ob.SetList(baseOutsOff, outsAt, len(in.Outs))
	ob.SetList(baseInsOff, insAt, len(in.Ins))
	ob.SetBytes(baseMemoOff, in.Memo)
	ob.FinishAsRoot()
	return b.Finish()
}

const (
	ptrOffsetOff = 0
	ptrSize      = 4
)

// Ptr is a zero-copy view into a ZAP-encoded Ptr message.
type Ptr struct{ o zap.Object }

// WrapPtr parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapPtr(b []byte) (Ptr, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Ptr{}, err
	}
	return Ptr{o: m.Root()}, nil
}

func (t Ptr) Offset() uint32 { return t.o.Uint32(ptrOffsetOff) }

// Record is the ptrSize bytes this Ptr occupies where it lies.
func (t Ptr) Record() []byte { return t.o.BytesFixed(0, ptrSize) }

// PtrList is a run of Ptr records, ptrSize bytes each.
type PtrList struct{ l zap.List }

// Len is how many elements the list holds.
func (x PtrList) Len() int { return x.l.Len() }

// At is element i, or the absent Ptr past the end.
func (x PtrList) At(i int) Ptr { return Ptr{o: x.l.Object(i, ptrSize)} }

// PtrInput collects the field values for NewPtr.
type PtrInput struct {
	Offset uint32
}

// NewPtr builds a ZAP-encoded Ptr message from in and returns the bytes.
func NewPtr(in PtrInput) []byte {
	b := zap.NewBuilderV2(256)
	ob := b.StartObject(ptrSize)
	ob.SetUint32(ptrOffsetOff, in.Offset)
	ob.FinishAsRoot()
	return b.Finish()
}

const (
	blockParentOff    = 0
	blockHeightOff    = 32
	blockTimeOff      = 40
	blockRootOff      = 48
	blockTxLengthsOff = 80
	blockTxBlobOff    = 88
	blockSize         = 96
)

// Block is a zero-copy view into a ZAP-encoded Block message.
type Block struct{ o zap.Object }

// WrapBlock parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapBlock(b []byte) (Block, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Block{}, err
	}
	return Block{o: m.Root()}, nil
}

func (t Block) Parent() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(blockParentOff, 32))
	return out
}
func (t Block) Height() uint64 { return t.o.Uint64(blockHeightOff) }
func (t Block) Time() uint64   { return t.o.Uint64(blockTimeOff) }
func (t Block) Root() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(blockRootOff, 32))
	return out
}
func (t Block) TxLengths() PtrList { return PtrList{l: t.o.ListStride(blockTxLengthsOff, ptrSize)} }
func (t Block) TxBlob() []byte     { return t.o.Bytes(blockTxBlobOff) }

// BlockInput collects the field values for NewBlock.
type BlockInput struct {
	Parent    [32]byte
	Height    uint64
	Time      uint64
	Root      [32]byte
	TxLengths [][]byte
	TxBlob    []byte
}

// NewBlock builds a ZAP-encoded Block message from in and returns the bytes.
func NewBlock(in BlockInput) []byte {
	b := zap.NewBuilderV2(256)
	txLengthsAt := 0
	if len(in.TxLengths) > 0 {
		lb := b.StartList(ptrSize)
		for _, elem := range in.TxLengths {
			var rec [ptrSize]byte
			copy(rec[:], elem)
			lb.AddBytes(rec[:])
		}
		txLengthsAt = lb.FinishOffset()
	}
	ob := b.StartObject(blockSize)
	ob.SetBytesFixed(blockParentOff, in.Parent[:])
	ob.SetUint64(blockHeightOff, in.Height)
	ob.SetUint64(blockTimeOff, in.Time)
	ob.SetBytesFixed(blockRootOff, in.Root[:])
	ob.SetList(blockTxLengthsOff, txLengthsAt, len(in.TxLengths))
	ob.SetBytes(blockTxBlobOff, in.TxBlob)
	ob.FinishAsRoot()
	return b.Finish()
}
