// Code generated by zapgen; DO NOT EDIT.
// source: xchain.zap

package xchain

import (
	"encoding/binary"
	zap "github.com/zap-proto/go"
)

const (
	signedUnsignedOff        = 0
	signedCredentialCountOff = 8
	signedCredentialBytesOff = 12
	signedSize               = 20
)

// Signed is a zero-copy view into a ZAP-encoded Signed message.
type Signed struct{ o zap.Object }

// WrapSigned parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapSigned(b []byte) (Signed, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Signed{}, err
	}
	return Signed{o: m.Root()}, nil
}

func (t Signed) Unsigned() []byte        { return t.o.Bytes(signedUnsignedOff) }
func (t Signed) CredentialCount() uint32 { return t.o.Uint32(signedCredentialCountOff) }
func (t Signed) CredentialBytes() []byte { return t.o.Bytes(signedCredentialBytesOff) }

// SignedInput collects the field values for NewSigned.
type SignedInput struct {
	Unsigned        []byte
	CredentialCount uint32
	CredentialBytes []byte
}

// PutSigned writes a Signed into b and returns where its object landed.
//
// What a field points AT is written first, in field order, and the fixed
// section last: a pointer always leads backward, to bytes already placed.
func PutSigned(b *zap.Builder, in SignedInput) int {
	ob := b.StartObject(signedSize)
	ob.SetBytes(signedUnsignedOff, in.Unsigned)
	ob.SetUint32(signedCredentialCountOff, in.CredentialCount)
	ob.SetBytes(signedCredentialBytesOff, in.CredentialBytes)
	return ob.Finish()
}

// NewSigned builds a ZAP-encoded Signed message from in and returns the bytes.
func NewSigned(in SignedInput) []byte {
	b := zap.NewBuilderV2(256)
	b.SetRoot(PutSigned(b, in))
	return b.Finish()
}

const (
	baseNetworkIDOff    = 0
	baseBlockchainIDOff = 8
	baseOutsOff         = 40
	baseInsOff          = 48
	baseMemoOff         = 56
	baseSize            = 64
)

// Base is a zero-copy view into a ZAP-encoded Base message.
type Base struct{ o zap.Object }

// WrapBase parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapBase(b []byte) (Base, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Base{}, err
	}
	return Base{o: m.Root()}, nil
}

func (t Base) NetworkID() uint32 { return t.o.Uint32(baseNetworkIDOff) }
func (t Base) BlockchainID() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(baseBlockchainIDOff, 32))
	return out
}
func (t Base) Outs() zap.List { return t.o.List(baseOutsOff) }

// OutsAt returns element i of Outs. Out of range returns the zero view.
func (t Base) OutsAt(i int) Ptr { return Ptr{o: t.o.List(baseOutsOff).Object(i, ptrSize)} }
func (t Base) Ins() zap.List    { return t.o.List(baseInsOff) }

// InsAt returns element i of Ins. Out of range returns the zero view.
func (t Base) InsAt(i int) Ptr { return Ptr{o: t.o.List(baseInsOff).Object(i, ptrSize)} }
func (t Base) Memo() []byte    { return t.o.Bytes(baseMemoOff) }

// BaseInput collects the field values for NewBase.
type BaseInput struct {
	NetworkID    uint32
	BlockchainID [32]byte
	Outs         [][]byte
	Ins          [][]byte
	Memo         []byte
}

// PutBase writes a Base into b and returns where its object landed.
//
// What a field points AT is written first, in field order, and the fixed
// section last: a pointer always leads backward, to bytes already placed.
func PutBase(b *zap.Builder, in BaseInput) int {
	outsLB := b.StartList(0)
	for _, elem := range in.Outs {
		outsLB.AddBytes(elem)
	}
	atOuts := outsLB.FinishOffset()
	insLB := b.StartList(0)
	for _, elem := range in.Ins {
		insLB.AddBytes(elem)
	}
	atIns := insLB.FinishOffset()
	ob := b.StartObject(baseSize)
	ob.SetUint32(baseNetworkIDOff, in.NetworkID)
	ob.SetBytesFixed(baseBlockchainIDOff, in.BlockchainID[:])
	ob.SetList(baseOutsOff, atOuts, len(in.Outs))
	ob.SetList(baseInsOff, atIns, len(in.Ins))
	ob.SetBytes(baseMemoOff, in.Memo)
	return ob.Finish()
}

// NewBase builds a ZAP-encoded Base message from in and returns the bytes.
func NewBase(in BaseInput) []byte {
	b := zap.NewBuilderV2(256)
	b.SetRoot(PutBase(b, in))
	return b.Finish()
}

const (
	ptrOffsetOff = 0
	ptrSize      = 4
)

// Ptr is a zero-copy view into a ZAP-encoded Ptr message.
type Ptr struct{ o zap.Object }

// WrapPtr parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapPtr(b []byte) (Ptr, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Ptr{}, err
	}
	return Ptr{o: m.Root()}, nil
}

func (t Ptr) Offset() uint32 { return t.o.Uint32(ptrOffsetOff) }

// PtrInput collects the field values for NewPtr.
type PtrInput struct {
	Offset uint32
}

// PackPtr returns Ptr as the ptrSize bytes one element of a list holds.
func PackPtr(in PtrInput) [ptrSize]byte {
	var r [ptrSize]byte
	binary.LittleEndian.PutUint32(r[ptrOffsetOff:], in.Offset)
	return r
}

// PutPtr writes a Ptr into b and returns where its object landed.
//
// What a field points AT is written first, in field order, and the fixed
// section last: a pointer always leads backward, to bytes already placed.
func PutPtr(b *zap.Builder, in PtrInput) int {
	ob := b.StartObject(ptrSize)
	ob.SetUint32(ptrOffsetOff, in.Offset)
	return ob.Finish()
}

// NewPtr builds a ZAP-encoded Ptr message from in and returns the bytes.
func NewPtr(in PtrInput) []byte {
	b := zap.NewBuilderV2(256)
	b.SetRoot(PutPtr(b, in))
	return b.Finish()
}

const (
	blockParentOff    = 0
	blockHeightOff    = 32
	blockTimeOff      = 40
	blockRootOff      = 48
	blockTxLengthsOff = 80
	blockTxBlobOff    = 88
	blockSize         = 96
)

// Block is a zero-copy view into a ZAP-encoded Block message.
type Block struct{ o zap.Object }

// WrapBlock parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapBlock(b []byte) (Block, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Block{}, err
	}
	return Block{o: m.Root()}, nil
}

func (t Block) Parent() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(blockParentOff, 32))
	return out
}
func (t Block) Height() uint64 { return t.o.Uint64(blockHeightOff) }
func (t Block) Time() uint64   { return t.o.Uint64(blockTimeOff) }
func (t Block) Root() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(blockRootOff, 32))
	return out
}
func (t Block) TxLengths() zap.List { return t.o.List(blockTxLengthsOff) }

// TxLengthsAt returns element i of TxLengths. Out of range returns the zero view.
func (t Block) TxLengthsAt(i int) Ptr { return Ptr{o: t.o.List(blockTxLengthsOff).Object(i, ptrSize)} }
func (t Block) TxBlob() []byte        { return t.o.Bytes(blockTxBlobOff) }

// BlockInput collects the field values for NewBlock.
type BlockInput struct {
	Parent    [32]byte
	Height    uint64
	Time      uint64
	Root      [32]byte
	TxLengths [][]byte
	TxBlob    []byte
}

// PutBlock writes a Block into b and returns where its object landed.
//
// What a field points AT is written first, in field order, and the fixed
// section last: a pointer always leads backward, to bytes already placed.
func PutBlock(b *zap.Builder, in BlockInput) int {
	txLengthsLB := b.StartList(0)
	for _, elem := range in.TxLengths {
		txLengthsLB.AddBytes(elem)
	}
	atTxLengths := txLengthsLB.FinishOffset()
	ob := b.StartObject(blockSize)
	ob.SetBytesFixed(blockParentOff, in.Parent[:])
	ob.SetUint64(blockHeightOff, in.Height)
	ob.SetUint64(blockTimeOff, in.Time)
	ob.SetBytesFixed(blockRootOff, in.Root[:])
	ob.SetList(blockTxLengthsOff, atTxLengths, len(in.TxLengths))
	ob.SetBytes(blockTxBlobOff, in.TxBlob)
	return ob.Finish()
}

// NewBlock builds a ZAP-encoded Block message from in and returns the bytes.
func NewBlock(in BlockInput) []byte {
	b := zap.NewBuilderV2(256)
	b.SetRoot(PutBlock(b, in))
	return b.Finish()
}
