// Code generated by zapgen; DO NOT EDIT.
// source: xchain.zap

package xchain

import (
	zap "github.com/zap-proto/go"
)

const (
	signedUnsignedOff        = 0
	signedCredentialCountOff = 8
	signedCredentialBytesOff = 12
	signedSize               = 20
)

// Signed is a zero-copy view into a ZAP-encoded Signed message.
type Signed struct{ o zap.Object }

// WrapSigned parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapSigned(b []byte) (Signed, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Signed{}, err
	}
	return Signed{o: m.Root()}, nil
}

func (t Signed) Unsigned() []byte        { return t.o.Bytes(signedUnsignedOff) }
func (t Signed) CredentialCount() uint32 { return t.o.Uint32(signedCredentialCountOff) }
func (t Signed) CredentialBytes() []byte { return t.o.Bytes(signedCredentialBytesOff) }

// SignedInput collects the field values for NewSigned.
type SignedInput struct {
	Unsigned        []byte
	CredentialCount uint32
	CredentialBytes []byte
}

// NewSigned builds a ZAP-encoded Signed message from in and returns the bytes.
func NewSigned(in SignedInput) []byte {
	b := zap.NewBuilderV2(256)
	ob := b.StartObject(signedSize)
	ob.SetBytes(signedUnsignedOff, in.Unsigned)
	ob.SetUint32(signedCredentialCountOff, in.CredentialCount)
	ob.SetBytes(signedCredentialBytesOff, in.CredentialBytes)
	ob.FinishAsRoot()
	return b.Finish()
}

const (
	txKindOff   = 0
	txBaseTxOff = 8
	txSize      = 16
)

// Tx is a zero-copy view into a ZAP-encoded Tx message.
type Tx struct{ o zap.Object }

// WrapTx parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapTx(b []byte) (Tx, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Tx{}, err
	}
	return Tx{o: m.Root()}, nil
}

func (t Tx) Kind() uint8    { return t.o.Uint8(txKindOff) }
func (t Tx) BaseTx() []byte { return t.o.Bytes(txBaseTxOff) }

// TxInput collects the field values for NewTx.
type TxInput struct {
	Kind   uint8
	BaseTx []byte
}

// NewTx builds a ZAP-encoded Tx message from in and returns the bytes.
func NewTx(in TxInput) []byte {
	b := zap.NewBuilderV2(256)
	ob := b.StartObject(txSize)
	ob.SetUint8(txKindOff, in.Kind)
	ob.SetBytes(txBaseTxOff, in.BaseTx)
	ob.FinishAsRoot()
	return b.Finish()
}

const (
	baseNetworkIDOff    = 0
	baseBlockchainIDOff = 8
	baseOutsOff         = 40
	baseInsOff          = 48
	baseMemoOff         = 56
	baseSize            = 64
)

// Base is a zero-copy view into a ZAP-encoded Base message.
type Base struct{ o zap.Object }

// WrapBase parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapBase(b []byte) (Base, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Base{}, err
	}
	return Base{o: m.Root()}, nil
}

func (t Base) NetworkID() uint32 { return t.o.Uint32(baseNetworkIDOff) }
func (t Base) BlockchainID() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(baseBlockchainIDOff, 32))
	return out
}
func (t Base) Outs() TransferableOutList {
	return TransferableOutList{l: t.o.ListStride(baseOutsOff, 4)}
}
func (t Base) Ins() TransferableInList { return TransferableInList{l: t.o.ListStride(baseInsOff, 4)} }
func (t Base) Memo() []byte            { return t.o.Bytes(baseMemoOff) }

// BaseInput collects the field values for NewBase.
type BaseInput struct {
	NetworkID    uint32
	BlockchainID [32]byte
	Outs         [][]byte
	Ins          [][]byte
	Memo         []byte
}

// NewBase builds a ZAP-encoded Base message from in and returns the bytes.
func NewBase(in BaseInput) []byte {
	b := zap.NewBuilderV2(256)
	outsAt := 0
	if len(in.Outs) > 0 {
		aims := make([]int, 0, len(in.Outs))
		for _, elem := range in.Outs {
			aims = append(aims, b.Embed(elem))
		}
		lb := b.StartList(4)
		for _, aim := range aims {
			lb.AddObjectPtr(aim)
		}
		outsAt = lb.FinishOffset()
	}
	insAt := 0
	if len(in.Ins) > 0 {
		aims := make([]int, 0, len(in.Ins))
		for _, elem := range in.Ins {
			aims = append(aims, b.Embed(elem))
		}
		lb := b.StartList(4)
		for _, aim := range aims {
			lb.AddObjectPtr(aim)
		}
		insAt = lb.FinishOffset()
	}
	ob := b.StartObject(baseSize)
	ob.SetUint32(baseNetworkIDOff, in.NetworkID)
	ob.SetBytesFixed(baseBlockchainIDOff, in.BlockchainID[:])
	ob.SetList(baseOutsOff, outsAt, len(in.Outs))
	ob.SetList(baseInsOff, insAt, len(in.Ins))
	ob.SetBytes(baseMemoOff, in.Memo)
	ob.FinishAsRoot()
	return b.Finish()
}

const (
	transferableOutAssetIDOff = 0
	transferableOutOutputOff  = 32
	transferableOutSize       = 40
)

// TransferableOut is a zero-copy view into a ZAP-encoded TransferableOut message.
type TransferableOut struct{ o zap.Object }

// WrapTransferableOut parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapTransferableOut(b []byte) (TransferableOut, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return TransferableOut{}, err
	}
	return TransferableOut{o: m.Root()}, nil
}

func (t TransferableOut) AssetID() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(transferableOutAssetIDOff, 32))
	return out
}
func (t TransferableOut) Output() []byte { return t.o.Bytes(transferableOutOutputOff) }

// TransferableOutList is a run of four-byte offsets, each aiming at one TransferableOut.
type TransferableOutList struct{ l zap.List }

// Len is how many elements the list holds.
func (x TransferableOutList) Len() int { return x.l.Len() }

// At is element i, or the absent TransferableOut past the end.
func (x TransferableOutList) At(i int) TransferableOut { return TransferableOut{o: x.l.ObjectPtr(i)} }

// TransferableOutInput collects the field values for NewTransferableOut.
type TransferableOutInput struct {
	AssetID [32]byte
	Output  []byte
}

// NewTransferableOut builds a ZAP-encoded TransferableOut message from in and returns the bytes.
func NewTransferableOut(in TransferableOutInput) []byte {
	b := zap.NewBuilderV2(256)
	ob := b.StartObject(transferableOutSize)
	ob.SetBytesFixed(transferableOutAssetIDOff, in.AssetID[:])
	ob.SetBytes(transferableOutOutputOff, in.Output)
	ob.FinishAsRoot()
	return b.Finish()
}

const (
	transferableInTxIDOff        = 0
	transferableInOutputIndexOff = 32
	transferableInAssetIDOff     = 36
	transferableInInputOff       = 68
	transferableInSize           = 76
)

// TransferableIn is a zero-copy view into a ZAP-encoded TransferableIn message.
type TransferableIn struct{ o zap.Object }

// WrapTransferableIn parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapTransferableIn(b []byte) (TransferableIn, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return TransferableIn{}, err
	}
	return TransferableIn{o: m.Root()}, nil
}

func (t TransferableIn) TxID() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(transferableInTxIDOff, 32))
	return out
}
func (t TransferableIn) OutputIndex() uint32 { return t.o.Uint32(transferableInOutputIndexOff) }
func (t TransferableIn) AssetID() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(transferableInAssetIDOff, 32))
	return out
}
func (t TransferableIn) Input() []byte { return t.o.Bytes(transferableInInputOff) }

// TransferableInList is a run of four-byte offsets, each aiming at one TransferableIn.
type TransferableInList struct{ l zap.List }

// Len is how many elements the list holds.
func (x TransferableInList) Len() int { return x.l.Len() }

// At is element i, or the absent TransferableIn past the end.
func (x TransferableInList) At(i int) TransferableIn { return TransferableIn{o: x.l.ObjectPtr(i)} }

// TransferableInInput collects the field values for NewTransferableIn.
type TransferableInInput struct {
	TxID        [32]byte
	OutputIndex uint32
	AssetID     [32]byte
	Input       []byte
}

// NewTransferableIn builds a ZAP-encoded TransferableIn message from in and returns the bytes.
func NewTransferableIn(in TransferableInInput) []byte {
	b := zap.NewBuilderV2(256)
	ob := b.StartObject(transferableInSize)
	ob.SetBytesFixed(transferableInTxIDOff, in.TxID[:])
	ob.SetUint32(transferableInOutputIndexOff, in.OutputIndex)
	ob.SetBytesFixed(transferableInAssetIDOff, in.AssetID[:])
	ob.SetBytes(transferableInInputOff, in.Input)
	ob.FinishAsRoot()
	return b.Finish()
}

const (
	blockParentOff    = 0
	blockHeightOff    = 32
	blockTimeOff      = 40
	blockRootOff      = 48
	blockTxLengthsOff = 80
	blockTxBlobOff    = 88
	blockSize         = 96
)

// Block is a zero-copy view into a ZAP-encoded Block message.
type Block struct{ o zap.Object }

// WrapBlock parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapBlock(b []byte) (Block, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Block{}, err
	}
	return Block{o: m.Root()}, nil
}

func (t Block) Parent() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(blockParentOff, 32))
	return out
}
func (t Block) Height() uint64 { return t.o.Uint64(blockHeightOff) }
func (t Block) Time() uint64   { return t.o.Uint64(blockTimeOff) }
func (t Block) Root() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(blockRootOff, 32))
	return out
}
func (t Block) TxLengths() zap.List { return t.o.ListStride(blockTxLengthsOff, 4) }
func (t Block) TxBlob() []byte      { return t.o.Bytes(blockTxBlobOff) }

// BlockInput collects the field values for NewBlock.
type BlockInput struct {
	Parent    [32]byte
	Height    uint64
	Time      uint64
	Root      [32]byte
	TxLengths [][]byte
	TxBlob    []byte
}

// NewBlock builds a ZAP-encoded Block message from in and returns the bytes.
func NewBlock(in BlockInput) []byte {
	b := zap.NewBuilderV2(256)
	txLengthsAt := 0
	if len(in.TxLengths) > 0 {
		lb := b.StartList(4)
		for _, elem := range in.TxLengths {
			var rec [4]byte
			copy(rec[:], elem)
			lb.AddBytes(rec[:])
		}
		txLengthsAt = lb.FinishOffset()
	}
	ob := b.StartObject(blockSize)
	ob.SetBytesFixed(blockParentOff, in.Parent[:])
	ob.SetUint64(blockHeightOff, in.Height)
	ob.SetUint64(blockTimeOff, in.Time)
	ob.SetBytesFixed(blockRootOff, in.Root[:])
	ob.SetList(blockTxLengthsOff, txLengthsAt, len(in.TxLengths))
	ob.SetBytes(blockTxBlobOff, in.TxBlob)
	ob.FinishAsRoot()
	return b.Finish()
}
