// Code generated by capnpc-go. DO NOT EDIT.
// Regenerate with: capnp compile -I$GOPATH/src/capnproto.org/go/capnp/std -ogo zap.capnp

package zap

import (
	"context"

	"capnproto.org/go/capnp/v3"
)

// Schema file ID
const Schema_b2a3f4c5d6e7f8a9 = uint64(0xb2a3f4c5d6e7f8a9)

// Timestamp represents a point in time.
type Timestamp capnp.Struct

func (s Timestamp) Seconds() int64       { return int64(capnp.Struct(s).Uint64(0)) }
func (s Timestamp) SetSeconds(v int64)   { capnp.Struct(s).SetUint64(0, uint64(v)) }
func (s Timestamp) Nanos() uint32        { return capnp.Struct(s).Uint32(8) }
func (s Timestamp) SetNanos(v uint32)    { capnp.Struct(s).SetUint32(8, v) }

// Metadata represents key-value metadata.
type Metadata capnp.Struct

func (s Metadata) Entries() (Metadata_Entry_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Metadata_Entry_List(p.List()), err
}

// Metadata_Entry represents a single metadata entry.
type Metadata_Entry capnp.Struct

func (s Metadata_Entry) Key() (string, error)   { return capnp.Struct(s).Text(0, "") }
func (s Metadata_Entry) SetKey(v string) error  { return capnp.Struct(s).SetText(0, v) }
func (s Metadata_Entry) Value() (string, error) { return capnp.Struct(s).Text(1, "") }
func (s Metadata_Entry) SetValue(v string) error { return capnp.Struct(s).SetText(1, v) }

type Metadata_Entry_List = capnp.StructList[Metadata_Entry]

// Tool represents a tool definition.
type Tool capnp.Struct

func (s Tool) Name() (string, error)        { return capnp.Struct(s).Text(0, "") }
func (s Tool) SetName(v string) error       { return capnp.Struct(s).SetText(0, v) }
func (s Tool) Description() (string, error) { return capnp.Struct(s).Text(1, "") }
func (s Tool) SetDescription(v string) error { return capnp.Struct(s).SetText(1, v) }
func (s Tool) Schema() ([]byte, error)      { return capnp.Struct(s).Data(2) }
func (s Tool) SetSchema(v []byte) error     { return capnp.Struct(s).SetData(2, v) }
func (s Tool) Annotations() (Metadata, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return Metadata(p.Struct()), err
}

type Tool_List = capnp.StructList[Tool]

// ToolList wraps a list of tools.
type ToolList capnp.Struct

func (s ToolList) Tools() (Tool_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Tool_List(p.List()), err
}

// ToolCall represents a tool invocation.
type ToolCall capnp.Struct

func (s ToolCall) Id() (string, error)     { return capnp.Struct(s).Text(0, "") }
func (s ToolCall) SetId(v string) error    { return capnp.Struct(s).SetText(0, v) }
func (s ToolCall) Name() (string, error)   { return capnp.Struct(s).Text(1, "") }
func (s ToolCall) SetName(v string) error  { return capnp.Struct(s).SetText(1, v) }
func (s ToolCall) Args() ([]byte, error)   { return capnp.Struct(s).Data(2) }
func (s ToolCall) SetArgs(v []byte) error  { return capnp.Struct(s).SetData(2, v) }
func (s ToolCall) Metadata() (Metadata, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return Metadata(p.Struct()), err
}

// ToolResult represents the result of a tool call.
type ToolResult capnp.Struct

func (s ToolResult) Id() (string, error)       { return capnp.Struct(s).Text(0, "") }
func (s ToolResult) SetId(v string) error      { return capnp.Struct(s).SetText(0, v) }
func (s ToolResult) Content() ([]byte, error)  { return capnp.Struct(s).Data(1) }
func (s ToolResult) SetContent(v []byte) error { return capnp.Struct(s).SetData(1, v) }
func (s ToolResult) Error() (string, error)    { return capnp.Struct(s).Text(2, "") }
func (s ToolResult) SetError(v string) error   { return capnp.Struct(s).SetText(2, v) }
func (s ToolResult) Metadata() (Metadata, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return Metadata(p.Struct()), err
}

// Resource represents a resource definition.
type Resource capnp.Struct

func (s Resource) Uri() (string, error)         { return capnp.Struct(s).Text(0, "") }
func (s Resource) SetUri(v string) error        { return capnp.Struct(s).SetText(0, v) }
func (s Resource) Name() (string, error)        { return capnp.Struct(s).Text(1, "") }
func (s Resource) SetName(v string) error       { return capnp.Struct(s).SetText(1, v) }
func (s Resource) Description() (string, error) { return capnp.Struct(s).Text(2, "") }
func (s Resource) SetDescription(v string) error { return capnp.Struct(s).SetText(2, v) }
func (s Resource) MimeType() (string, error)    { return capnp.Struct(s).Text(3, "") }
func (s Resource) SetMimeType(v string) error   { return capnp.Struct(s).SetText(3, v) }
func (s Resource) Annotations() (Metadata, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return Metadata(p.Struct()), err
}

type Resource_List = capnp.StructList[Resource]

// ResourceList wraps a list of resources.
type ResourceList capnp.Struct

func (s ResourceList) Resources() (Resource_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Resource_List(p.List()), err
}

// ResourceContent represents resource content.
type ResourceContent capnp.Struct

func (s ResourceContent) Uri() (string, error)      { return capnp.Struct(s).Text(0, "") }
func (s ResourceContent) SetUri(v string) error     { return capnp.Struct(s).SetText(0, v) }
func (s ResourceContent) MimeType() (string, error) { return capnp.Struct(s).Text(1, "") }
func (s ResourceContent) SetMimeType(v string) error { return capnp.Struct(s).SetText(1, v) }

type ResourceContent_content capnp.Struct

const (
	ResourceContent_content_Which_text = iota
	ResourceContent_content_Which_blob
)

func (s ResourceContent) Content() ResourceContent_content {
	return ResourceContent_content(s)
}

func (s ResourceContent_content) Which() uint16 { return capnp.Struct(s).Uint16(0) }
func (s ResourceContent_content) Text() (string, error) { return capnp.Struct(s).Text(2, "") }
func (s ResourceContent_content) Blob() ([]byte, error) { return capnp.Struct(s).Data(2) }

// Prompt represents a prompt definition.
type Prompt capnp.Struct

func (s Prompt) Name() (string, error)        { return capnp.Struct(s).Text(0, "") }
func (s Prompt) SetName(v string) error       { return capnp.Struct(s).SetText(0, v) }
func (s Prompt) Description() (string, error) { return capnp.Struct(s).Text(1, "") }
func (s Prompt) SetDescription(v string) error { return capnp.Struct(s).SetText(1, v) }
func (s Prompt) Arguments() (Prompt_Argument_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return Prompt_Argument_List(p.List()), err
}

type Prompt_List = capnp.StructList[Prompt]

// Prompt_Argument represents a prompt argument.
type Prompt_Argument capnp.Struct

func (s Prompt_Argument) Name() (string, error)        { return capnp.Struct(s).Text(0, "") }
func (s Prompt_Argument) SetName(v string) error       { return capnp.Struct(s).SetText(0, v) }
func (s Prompt_Argument) Description() (string, error) { return capnp.Struct(s).Text(1, "") }
func (s Prompt_Argument) SetDescription(v string) error { return capnp.Struct(s).SetText(1, v) }
func (s Prompt_Argument) Required() bool               { return capnp.Struct(s).Bit(0) }
func (s Prompt_Argument) SetRequired(v bool)           { capnp.Struct(s).SetBit(0, v) }

type Prompt_Argument_List = capnp.StructList[Prompt_Argument]

// PromptList wraps a list of prompts.
type PromptList capnp.Struct

func (s PromptList) Prompts() (Prompt_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Prompt_List(p.List()), err
}

// PromptMessage represents a message in a prompt.
type PromptMessage capnp.Struct

type PromptMessage_Role uint16

const (
	PromptMessage_Role_user PromptMessage_Role = iota
	PromptMessage_Role_assistant
	PromptMessage_Role_system
)

func (s PromptMessage) Role() PromptMessage_Role { return PromptMessage_Role(capnp.Struct(s).Uint16(0)) }
func (s PromptMessage) SetRole(v PromptMessage_Role) { capnp.Struct(s).SetUint16(0, uint16(v)) }

type PromptMessage_Content capnp.Struct

const (
	PromptMessage_Content_Which_text = iota
	PromptMessage_Content_Which_image
	PromptMessage_Content_Which_resource
)

func (s PromptMessage) Content() (PromptMessage_Content, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return PromptMessage_Content(p.Struct()), err
}

func (s PromptMessage_Content) Which() uint16        { return capnp.Struct(s).Uint16(0) }
func (s PromptMessage_Content) Text() (string, error) { return capnp.Struct(s).Text(0, "") }
func (s PromptMessage_Content) Image() (PromptMessage_ImageContent, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return PromptMessage_ImageContent(p.Struct()), err
}
func (s PromptMessage_Content) Resource() (ResourceContent, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ResourceContent(p.Struct()), err
}

type PromptMessage_ImageContent capnp.Struct

func (s PromptMessage_ImageContent) Data() ([]byte, error)     { return capnp.Struct(s).Data(0) }
func (s PromptMessage_ImageContent) MimeType() (string, error) { return capnp.Struct(s).Text(1, "") }

type PromptMessage_List = capnp.StructList[PromptMessage]

// ServerInfo represents server information.
type ServerInfo capnp.Struct

func (s ServerInfo) Name() (string, error)    { return capnp.Struct(s).Text(0, "") }
func (s ServerInfo) SetName(v string) error   { return capnp.Struct(s).SetText(0, v) }
func (s ServerInfo) Version() (string, error) { return capnp.Struct(s).Text(1, "") }
func (s ServerInfo) SetVersion(v string) error { return capnp.Struct(s).SetText(1, v) }
func (s ServerInfo) Capabilities() (ServerInfo_Capabilities, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return ServerInfo_Capabilities(p.Struct()), err
}

// ServerInfo_Capabilities represents server capabilities.
type ServerInfo_Capabilities capnp.Struct

func (s ServerInfo_Capabilities) Tools() bool     { return capnp.Struct(s).Bit(0) }
func (s ServerInfo_Capabilities) Resources() bool { return capnp.Struct(s).Bit(1) }
func (s ServerInfo_Capabilities) Prompts() bool   { return capnp.Struct(s).Bit(2) }
func (s ServerInfo_Capabilities) Logging() bool   { return capnp.Struct(s).Bit(3) }

// ClientInfo represents client information.
type ClientInfo capnp.Struct

func (s ClientInfo) Name() (string, error)     { return capnp.Struct(s).Text(0, "") }
func (s ClientInfo) SetName(v string) error    { return capnp.Struct(s).SetText(0, v) }
func (s ClientInfo) Version() (string, error)  { return capnp.Struct(s).Text(1, "") }
func (s ClientInfo) SetVersion(v string) error { return capnp.Struct(s).SetText(1, v) }

// Zap is the main ZAP RPC interface.
type Zap capnp.Client

type Zap_LogLevel uint16

const (
	Zap_LogLevel_debug Zap_LogLevel = iota
	Zap_LogLevel_info
	Zap_LogLevel_warn
	Zap_LogLevel_error
)

// Zap_init_Params
type Zap_init_Params capnp.Struct

func (s Zap_init_Params) Client() (ClientInfo, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ClientInfo(p.Struct()), err
}
func (s Zap_init_Params) NewClient() (ClientInfo, error) {
	ss, err := capnp.NewStruct(capnp.Struct(s).Segment(), capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	if err != nil {
		return ClientInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, ss.ToPtr())
	return ClientInfo(ss), err
}

// Zap_init_Results
type Zap_init_Results capnp.Struct

func (s Zap_init_Results) Server() (ServerInfo, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ServerInfo(p.Struct()), err
}

// Zap_listTools_Results
type Zap_listTools_Results capnp.Struct

func (s Zap_listTools_Results) Tools() (ToolList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ToolList(p.Struct()), err
}

// Zap_callTool_Params
type Zap_callTool_Params capnp.Struct

func (s Zap_callTool_Params) Call() (ToolCall, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ToolCall(p.Struct()), err
}
func (s Zap_callTool_Params) NewCall() (ToolCall, error) {
	ss, err := capnp.NewStruct(capnp.Struct(s).Segment(), capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	if err != nil {
		return ToolCall{}, err
	}
	err = capnp.Struct(s).SetPtr(0, ss.ToPtr())
	return ToolCall(ss), err
}

// Zap_callTool_Results
type Zap_callTool_Results capnp.Struct

func (s Zap_callTool_Results) Result() (ToolResult, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ToolResult(p.Struct()), err
}

// Zap_listResources_Results
type Zap_listResources_Results capnp.Struct

func (s Zap_listResources_Results) Resources() (ResourceList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ResourceList(p.Struct()), err
}

// Zap_readResource_Params
type Zap_readResource_Params capnp.Struct

func (s Zap_readResource_Params) Uri() (string, error) { return capnp.Struct(s).Text(0, "") }
func (s Zap_readResource_Params) SetUri(v string) error { return capnp.Struct(s).SetText(0, v) }

// Zap_readResource_Results
type Zap_readResource_Results capnp.Struct

func (s Zap_readResource_Results) Content() (ResourceContent, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ResourceContent(p.Struct()), err
}

// Zap_listPrompts_Results
type Zap_listPrompts_Results capnp.Struct

func (s Zap_listPrompts_Results) Prompts() (PromptList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return PromptList(p.Struct()), err
}

// Zap_getPrompt_Params
type Zap_getPrompt_Params capnp.Struct

func (s Zap_getPrompt_Params) Name() (string, error)   { return capnp.Struct(s).Text(0, "") }
func (s Zap_getPrompt_Params) SetName(v string) error  { return capnp.Struct(s).SetText(0, v) }
func (s Zap_getPrompt_Params) Args() (Metadata, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return Metadata(p.Struct()), err
}
func (s Zap_getPrompt_Params) NewArgs() (Metadata, error) {
	ss, err := capnp.NewStruct(capnp.Struct(s).Segment(), capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	if err != nil {
		return Metadata{}, err
	}
	err = capnp.Struct(s).SetPtr(1, ss.ToPtr())
	return Metadata(ss), err
}

// Zap_getPrompt_Results
type Zap_getPrompt_Results capnp.Struct

func (s Zap_getPrompt_Results) Messages() (PromptMessage_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return PromptMessage_List(p.List()), err
}

// Zap_log_Params
type Zap_log_Params capnp.Struct

func (s Zap_log_Params) Level() Zap_LogLevel        { return Zap_LogLevel(capnp.Struct(s).Uint16(0)) }
func (s Zap_log_Params) SetLevel(v Zap_LogLevel)    { capnp.Struct(s).SetUint16(0, uint16(v)) }
func (s Zap_log_Params) Message() (string, error)   { return capnp.Struct(s).Text(0, "") }
func (s Zap_log_Params) SetMessage(v string) error  { return capnp.Struct(s).SetText(0, v) }
func (s Zap_log_Params) Data() ([]byte, error)      { return capnp.Struct(s).Data(1) }
func (s Zap_log_Params) SetData(v []byte) error     { return capnp.Struct(s).SetData(1, v) }

// RPC method implementations
func (c Zap) Init(ctx context.Context, params func(Zap_init_Params) error) (Zap_init_Results_Future, capnp.ReleaseFunc) {
	// Implementation would use capnp RPC
	return Zap_init_Results_Future{}, func() {}
}

func (c Zap) ListTools(ctx context.Context, params func(struct{}) error) (Zap_listTools_Results_Future, capnp.ReleaseFunc) {
	return Zap_listTools_Results_Future{}, func() {}
}

func (c Zap) CallTool(ctx context.Context, params func(Zap_callTool_Params) error) (Zap_callTool_Results_Future, capnp.ReleaseFunc) {
	return Zap_callTool_Results_Future{}, func() {}
}

func (c Zap) ListResources(ctx context.Context, params func(struct{}) error) (Zap_listResources_Results_Future, capnp.ReleaseFunc) {
	return Zap_listResources_Results_Future{}, func() {}
}

func (c Zap) ReadResource(ctx context.Context, params func(Zap_readResource_Params) error) (Zap_readResource_Results_Future, capnp.ReleaseFunc) {
	return Zap_readResource_Results_Future{}, func() {}
}

func (c Zap) ListPrompts(ctx context.Context, params func(struct{}) error) (Zap_listPrompts_Results_Future, capnp.ReleaseFunc) {
	return Zap_listPrompts_Results_Future{}, func() {}
}

func (c Zap) GetPrompt(ctx context.Context, params func(Zap_getPrompt_Params) error) (Zap_getPrompt_Results_Future, capnp.ReleaseFunc) {
	return Zap_getPrompt_Results_Future{}, func() {}
}

func (c Zap) Log(ctx context.Context, params func(Zap_log_Params) error) (Zap_log_Results_Future, capnp.ReleaseFunc) {
	return Zap_log_Results_Future{}, func() {}
}

// Future types for async RPC calls
type Zap_init_Results_Future struct{ *capnp.Future }
func (f Zap_init_Results_Future) Struct() (Zap_init_Results, error) { return Zap_init_Results{}, nil }

type Zap_listTools_Results_Future struct{ *capnp.Future }
func (f Zap_listTools_Results_Future) Struct() (Zap_listTools_Results, error) { return Zap_listTools_Results{}, nil }

type Zap_callTool_Results_Future struct{ *capnp.Future }
func (f Zap_callTool_Results_Future) Struct() (Zap_callTool_Results, error) { return Zap_callTool_Results{}, nil }

type Zap_listResources_Results_Future struct{ *capnp.Future }
func (f Zap_listResources_Results_Future) Struct() (Zap_listResources_Results, error) { return Zap_listResources_Results{}, nil }

type Zap_readResource_Results_Future struct{ *capnp.Future }
func (f Zap_readResource_Results_Future) Struct() (Zap_readResource_Results, error) { return Zap_readResource_Results{}, nil }

type Zap_listPrompts_Results_Future struct{ *capnp.Future }
func (f Zap_listPrompts_Results_Future) Struct() (Zap_listPrompts_Results, error) { return Zap_listPrompts_Results{}, nil }

type Zap_getPrompt_Results_Future struct{ *capnp.Future }
func (f Zap_getPrompt_Results_Future) Struct() (Zap_getPrompt_Results, error) { return Zap_getPrompt_Results{}, nil }

type Zap_log_Results_Future struct{ *capnp.Future }
func (f Zap_log_Results_Future) Struct() (struct{}, error) { return struct{}{}, nil }
