// Code generated by zapgen; DO NOT EDIT.
// source: kitchen.zap

package kitchen

import (
	zap "github.com/zap-proto/go"
)

const (
	leafTagOff  = 0
	leafNoteOff = 4
	leafSize    = 12
)

// Leaf is a zero-copy view into a ZAP-encoded Leaf message.
type Leaf struct{ o zap.Object }

// WrapLeaf parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapLeaf(b []byte) (Leaf, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Leaf{}, err
	}
	return Leaf{o: m.Root()}, nil
}

func (t Leaf) Tag() uint32  { return t.o.Uint32(leafTagOff) }
func (t Leaf) Note() string { return t.o.Text(leafNoteOff) }

// LeafInput collects the field values for NewLeaf.
type LeafInput struct {
	Tag  uint32
	Note string
}

// NewLeaf builds a ZAP-encoded Leaf message from in and returns the bytes.
func NewLeaf(in LeafInput) []byte {
	b := zap.NewBuilder(256)
	ob := b.StartObject(leafSize)
	ob.SetUint32(leafTagOff, in.Tag)
	ob.SetText(leafNoteOff, in.Note)
	ob.FinishAsRoot()
	return b.Finish()
}

const (
	allFlagOff  = 0
	allA8Off    = 1
	allA16Off   = 2
	allA32Off   = 4
	allA64Off   = 8
	allS8Off    = 16
	allS16Off   = 18
	allS32Off   = 20
	allS64Off   = 24
	allF32Off   = 32
	allF64Off   = 40
	allNameOff  = 48
	allBlobOff  = 56
	allIdOff    = 64
	allItemsOff = 80
	allInnerOff = 88
	allSize     = 92
)

// All is a zero-copy view into a ZAP-encoded All message.
type All struct{ o zap.Object }

// WrapAll parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapAll(b []byte) (All, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return All{}, err
	}
	return All{o: m.Root()}, nil
}

func (t All) Flag() bool   { return t.o.Bool(allFlagOff) }
func (t All) A8() uint8    { return t.o.Uint8(allA8Off) }
func (t All) A16() uint16  { return t.o.Uint16(allA16Off) }
func (t All) A32() uint32  { return t.o.Uint32(allA32Off) }
func (t All) A64() uint64  { return t.o.Uint64(allA64Off) }
func (t All) S8() int8     { return t.o.Int8(allS8Off) }
func (t All) S16() int16   { return t.o.Int16(allS16Off) }
func (t All) S32() int32   { return t.o.Int32(allS32Off) }
func (t All) S64() int64   { return t.o.Int64(allS64Off) }
func (t All) F32() float32 { return t.o.Float32(allF32Off) }
func (t All) F64() float64 { return t.o.Float64(allF64Off) }
func (t All) Name() string { return t.o.Text(allNameOff) }
func (t All) Blob() []byte { return t.o.Bytes(allBlobOff) }
func (t All) Id() [16]byte {
	var out [16]byte
	copy(out[:], t.o.BytesFixed(allIdOff, 16))
	return out
}
func (t All) Items() zap.List { return t.o.List(allItemsOff) }
func (t All) Inner() Leaf     { return Leaf{o: t.o.Object(allInnerOff)} }

// AllInput collects the field values for NewAll.
type AllInput struct {
	Flag  bool
	A8    uint8
	A16   uint16
	A32   uint32
	A64   uint64
	S8    int8
	S16   int16
	S32   int32
	S64   int64
	F32   float32
	F64   float64
	Name  string
	Blob  []byte
	Id    [16]byte
	Items [][]byte
	Inner []byte
}

// NewAll builds a ZAP-encoded All message from in and returns the bytes.
func NewAll(in AllInput) []byte {
	b := zap.NewBuilder(256)
	ob := b.StartObject(allSize)
	ob.SetBool(allFlagOff, in.Flag)
	ob.SetUint8(allA8Off, in.A8)
	ob.SetUint16(allA16Off, in.A16)
	ob.SetUint32(allA32Off, in.A32)
	ob.SetUint64(allA64Off, in.A64)
	ob.SetUint8(allS8Off, uint8(in.S8))
	ob.SetUint16(allS16Off, uint16(in.S16))
	ob.SetUint32(allS32Off, uint32(in.S32))
	ob.SetUint64(allS64Off, uint64(in.S64))
	ob.SetFloat32(allF32Off, in.F32)
	ob.SetFloat64(allF64Off, in.F64)
	ob.SetText(allNameOff, in.Name)
	ob.SetBytes(allBlobOff, in.Blob)
	ob.SetBytesFixed(allIdOff, in.Id[:])
	itemsLB := b.StartList(0)
	for _, elem := range in.Items {
		itemsLB.AddObjectBytes(elem)
	}
	ob.SetList(allItemsOff, itemsLB.FinishOffset(), len(in.Items))
	ob.SetObject(allInnerOff, b.Embed(in.Inner))
	ob.FinishAsRoot()
	return b.Finish()
}
