// Copyright (C) 2025, Lux Industries Inc. All rights reserved.
// See the file LICENSE for licensing terms.

// Package echo is a self-contained demo of zapgen interface (RPC) codegen.
//
// echo.zap declares two structs (Ping, Pong) and an Echo service with four
// methods covering every shape: request+response, request-only (void
// return), response-only (no request), and bare (no params). The *_zap.go
// files are generated by zapgen and checked in; echo_test.go drives the
// generated EchoClient through DispatchEcho against a hand-written
// EchoHandler over an in-memory channel, proving the ordinal-routed call
// envelope round-trips.
//
//go:generate go run github.com/zap-proto/go/cmd/zapgen -out . echo.zap
package echo
