// Code generated by zapgen; DO NOT EDIT.
// source: echo.zap

package echo

import (
	"fmt"
	"github.com/zap-proto/go/rpc"
)

// Method ordinals for the Echo service (stable 1-based wire ids).
const (
	EchoPingOrdinal     uint32 = 1
	EchoNotifyOrdinal   uint32 = 2
	EchoHealthOrdinal   uint32 = 3
	EchoShutdownOrdinal uint32 = 4
)

// EchoChannel ships one Call envelope and awaits its correlated Response.
type EchoChannel interface {
	Call(envelope []byte) (rpc.Response, error)
}

// EchoClient is a typed RPC client for the Echo service over a ZAP call channel.
type EchoClient struct {
	ch  EchoChannel
	cap []byte
}

// NewEchoClient returns a client that issues calls over ch, attaching cap
// (which may be nil) to every request.
func NewEchoClient(ch EchoChannel, capability []byte) *EchoClient {
	return &EchoClient{ch: ch, cap: capability}
}

func (c *EchoClient) Ping(req []byte) ([]byte, error) {
	resp, err := c.ch.Call(rpc.BuildRequest(rpc.Call{
		Method:  EchoPingOrdinal,
		Target:  rpc.NoTarget,
		Cap:     c.cap,
		Payload: req,
	}))
	if err != nil {
		return nil, err
	}
	if resp.Status != rpc.StatusOK {
		return nil, fmt.Errorf("Echo.Ping: status %d", resp.Status)
	}
	return resp.Body, nil
}

func (c *EchoClient) Notify(req []byte) error {
	resp, err := c.ch.Call(rpc.BuildRequest(rpc.Call{
		Method:  EchoNotifyOrdinal,
		Target:  rpc.NoTarget,
		Cap:     c.cap,
		Payload: req,
	}))
	if err != nil {
		return err
	}
	if resp.Status != rpc.StatusOK {
		return fmt.Errorf("Echo.Notify: status %d", resp.Status)
	}
	return nil
}

func (c *EchoClient) Health() ([]byte, error) {
	resp, err := c.ch.Call(rpc.BuildRequest(rpc.Call{
		Method:  EchoHealthOrdinal,
		Target:  rpc.NoTarget,
		Cap:     c.cap,
		Payload: nil,
	}))
	if err != nil {
		return nil, err
	}
	if resp.Status != rpc.StatusOK {
		return nil, fmt.Errorf("Echo.Health: status %d", resp.Status)
	}
	return resp.Body, nil
}

func (c *EchoClient) Shutdown() error {
	resp, err := c.ch.Call(rpc.BuildRequest(rpc.Call{
		Method:  EchoShutdownOrdinal,
		Target:  rpc.NoTarget,
		Cap:     c.cap,
		Payload: nil,
	}))
	if err != nil {
		return err
	}
	if resp.Status != rpc.StatusOK {
		return fmt.Errorf("Echo.Shutdown: status %d", resp.Status)
	}
	return nil
}

// EchoHandler is the server contract for the Echo service. Implement each
// method, then route requests to it with DispatchEcho.
type EchoHandler interface {
	Ping(req []byte) ([]byte, error)
	Notify(req []byte) error
	Health() ([]byte, error)
	Shutdown() error
}

// DispatchEcho decodes a Call envelope, routes it by method ordinal to h,
// and returns the response envelope. An unknown ordinal yields a
// StatusNotFound response; a handler error yields StatusInternal.
func DispatchEcho(h EchoHandler, envelope []byte) ([]byte, error) {
	call, err := rpc.ParseRequest(envelope)
	if err != nil {
		return nil, err
	}
	switch call.Method {
	case EchoPingOrdinal:
		body, err := h.Ping(call.Payload)
		if err != nil {
			return rpc.BuildResponse(rpc.StatusInternal, call.PromiseID, nil), nil
		}
		return rpc.BuildResponse(rpc.StatusOK, call.PromiseID, body), nil
	case EchoNotifyOrdinal:
		if err := h.Notify(call.Payload); err != nil {
			return rpc.BuildResponse(rpc.StatusInternal, call.PromiseID, nil), nil
		}
		return rpc.BuildResponse(rpc.StatusOK, call.PromiseID, nil), nil
	case EchoHealthOrdinal:
		body, err := h.Health()
		if err != nil {
			return rpc.BuildResponse(rpc.StatusInternal, call.PromiseID, nil), nil
		}
		return rpc.BuildResponse(rpc.StatusOK, call.PromiseID, body), nil
	case EchoShutdownOrdinal:
		if err := h.Shutdown(); err != nil {
			return rpc.BuildResponse(rpc.StatusInternal, call.PromiseID, nil), nil
		}
		return rpc.BuildResponse(rpc.StatusOK, call.PromiseID, nil), nil
	default:
		return rpc.BuildResponse(rpc.StatusNotFound, call.PromiseID, nil), nil
	}
}
