// Copyright (C) 2025, Lux Industries Inc. All rights reserved.
// See the file LICENSE for licensing terms.

package main

import (
	"bytes"
	"fmt"
	"strings"
)

// emit_ts.go is the TypeScript code target for zapgen. It mirrors emit.go's
// structure field-for-field but produces TS classes over the @hanzo/zap
// runtime instead of Go accessors over github.com/zap-proto/go.
//
// The byte layout is identical (same offsets, same fixed-section size, same
// variable-tail encoding), so a buffer built by the generated Go builder is
// readable by the generated TS view and vice versa. The two emitters share the
// schema AST, the offset model (Type.SlotSize), and the validate() pass — only
// the surface language differs. The Go emitter behavior is untouched.
//
// One file per schema (EmitTS), mirroring EmitSingle: TS modules naturally
// group related classes, and the consuming side imports them by name.

// EmitTS emits one combined .ts file containing every struct's View + Builder
// from f. Returns (basename, bytes). The basename is derived from the schema
// source filename: strip .zap, append _zap.ts (mirrors EmitSingle's _zap.go).
func EmitTS(f *File) (string, []byte, error) {
	if len(f.Structs) == 0 {
		return "", nil, fmt.Errorf("no structs to emit")
	}
	source := f.Source
	if source == "" {
		source = f.Package + ".zap"
	}
	base := source
	if i := strings.LastIndex(base, "."); i >= 0 {
		base = base[:i]
	}
	outName := base + "_zap.ts"

	var w bytes.Buffer
	w.WriteString("// Code generated by zapgen --target=ts; DO NOT EDIT.\n")
	fmt.Fprintf(&w, "// source: %s\n\n", source)
	// Import only what the emitted code references, so the file type-checks
	// under strict noUnusedLocals. ListView is a type-only import; it is needed
	// iff any field is a list.
	w.WriteString("import {\n")
	w.WriteString("  Builder,\n")
	w.WriteString("  Message,\n")
	w.WriteString("  StructView,\n")
	if fileHasList(f) {
		w.WriteString("  type ListView,\n")
	}
	w.WriteString("} from \"@hanzo/zap\";\n\n")

	// Named-type aliases (type id32 = bytes_fixed[32] etc) become branded
	// Uint8Array aliases. Only fixed-byte aliases get a brand; other aliases
	// resolve to their primitive at field sites, so nothing to emit for them.
	emitTSAliases(&w, f)

	for _, s := range f.Structs {
		if err := validate(s); err != nil {
			return "", nil, err
		}
		emitTSOffsets(&w, s)
		emitTSView(&w, s)
		emitTSBuilder(&w, s)
		w.WriteString("\n")
	}
	return outName, w.Bytes(), nil
}

// emitTSAliases writes a branded Uint8Array type per bytes_fixed alias.
// Iterates the file's aliases in declaration-stable order by scanning the
// source is overkill; the map is small and TS type-alias ordering is
// irrelevant, so we sort names for deterministic output.
func emitTSAliases(w *bytes.Buffer, f *File) {
	names := sortedAliasNames(f)
	wrote := false
	for _, name := range names {
		t := f.Aliases[name]
		if t.Kind != KindBytesFixed {
			continue
		}
		fmt.Fprintf(w, "export type %s = Uint8Array & { readonly __brand: %q };\n", name, name)
		wrote = true
	}
	if wrote {
		w.WriteString("\n")
	}
}

func sortedAliasNames(f *File) []string {
	names := make([]string, 0, len(f.Aliases))
	for n := range f.Aliases {
		names = append(names, n)
	}
	// Simple insertion sort — small N, no import of sort needed elsewhere.
	for i := 1; i < len(names); i++ {
		for j := i; j > 0 && names[j] < names[j-1]; j-- {
			names[j], names[j-1] = names[j-1], names[j]
		}
	}
	return names
}

// emitTSOffsets emits the per-field offset constants + total size as a const
// object. Mirrors emitOffsets (the Go `const ( fooOff = N … )` block).
func emitTSOffsets(w *bytes.Buffer, s *Struct) {
	lower := lowerFirst(s.Name)
	fmt.Fprintf(w, "const %sOff = {\n", lower)
	for _, f := range s.Fields {
		fmt.Fprintf(w, "  %s: %d,\n", f.Name, f.Offset)
	}
	w.WriteString("} as const;\n")
	fmt.Fprintf(w, "const %sSize = %d;\n\n", lower, structSize(s))
}

// emitTSView emits the zero-copy view class. Mirrors emitReader: a wrap()
// static that parses + roots, plus one getter per field.
func emitTSView(w *bytes.Buffer, s *Struct) {
	lower := lowerFirst(s.Name)
	fmt.Fprintf(w, "/** Zero-copy view into a ZAP-encoded %s message. */\n", s.Name)
	fmt.Fprintf(w, "export class %s extends StructView {\n", s.Name)

	// wrap(bytes) — parse the full message and root the view. Mirrors
	// WrapXxx(b []byte) (Xxx, error): on a wire-level failure Message.parse
	// throws, which is the TS analogue of returning the error.
	fmt.Fprintf(w, "  /** Parse `b` and return a typed view. Throws on a wire-level check failure (magic, version, size). */\n")
	fmt.Fprintf(w, "  static wrap(b: Uint8Array): %s {\n", s.Name)
	w.WriteString("    const root = Message.parse(b).root();\n")
	fmt.Fprintf(w, "    return new %s(root.data, root.offset);\n", s.Name)
	w.WriteString("  }\n\n")

	for _, f := range s.Fields {
		emitTSFieldGetter(w, lower, f)
	}
	w.WriteString("}\n\n")
}

func emitTSFieldGetter(w *bytes.Buffer, lower string, f *Field) {
	off := fmt.Sprintf("%sOff.%s", lower, f.Name)
	switch f.Type.Kind {
	case KindBool:
		fmt.Fprintf(w, "  get %s(): boolean { return this.bool(%s); }\n", camelLower(f.Name), off)
	case KindU8:
		fmt.Fprintf(w, "  get %s(): number { return this.u8(%s); }\n", camelLower(f.Name), off)
	case KindU16:
		fmt.Fprintf(w, "  get %s(): number { return this.u16(%s); }\n", camelLower(f.Name), off)
	case KindU32:
		fmt.Fprintf(w, "  get %s(): number { return this.u32(%s); }\n", camelLower(f.Name), off)
	case KindU64:
		fmt.Fprintf(w, "  get %s(): bigint { return this.u64(%s); }\n", camelLower(f.Name), off)
	case KindI8:
		fmt.Fprintf(w, "  get %s(): number { return this.i8(%s); }\n", camelLower(f.Name), off)
	case KindI16:
		fmt.Fprintf(w, "  get %s(): number { return this.i16(%s); }\n", camelLower(f.Name), off)
	case KindI32:
		fmt.Fprintf(w, "  get %s(): number { return this.i32(%s); }\n", camelLower(f.Name), off)
	case KindI64:
		fmt.Fprintf(w, "  get %s(): bigint { return this.i64(%s); }\n", camelLower(f.Name), off)
	case KindF32:
		fmt.Fprintf(w, "  get %s(): number { return this.f32(%s); }\n", camelLower(f.Name), off)
	case KindF64:
		fmt.Fprintf(w, "  get %s(): number { return this.f64(%s); }\n", camelLower(f.Name), off)
	case KindText:
		fmt.Fprintf(w, "  get %s(): string { return this.text(%s); }\n", camelLower(f.Name), off)
	case KindBytes:
		fmt.Fprintf(w, "  get %s(): Uint8Array { return this.bytes(%s); }\n", camelLower(f.Name), off)
	case KindBytesFixed:
		fmt.Fprintf(w, "  get %s(): Uint8Array { return this.bytesFixed(%s, %d); }\n",
			camelLower(f.Name), off, f.Type.FixedSize)
	case KindList:
		fmt.Fprintf(w, "  get %s(): ListView { return this.list(%s); }\n", camelLower(f.Name), off)
	case KindStruct:
		fmt.Fprintf(w, "  get %s(): %s {\n", camelLower(f.Name), f.Type.StructName)
		fmt.Fprintf(w, "    const o = this.object(%s);\n", off)
		fmt.Fprintf(w, "    return new %s(o.data, o.offset);\n", f.Type.StructName)
		w.WriteString("  }\n")
	}
}

// emitTSBuilder emits the input interface + the New<Name> builder function.
// Mirrors emitBuilder: an Input shape and a New<Name>(in): Uint8Array that
// drives the @hanzo/zap Builder identically to the Go path.
func emitTSBuilder(w *bytes.Buffer, s *Struct) {
	lower := lowerFirst(s.Name)

	// Input interface.
	fmt.Fprintf(w, "/** Field values for new%s. */\n", s.Name)
	fmt.Fprintf(w, "export interface %sInput {\n", s.Name)
	for _, f := range s.Fields {
		fmt.Fprintf(w, "  %s: %s;\n", camelLower(f.Name), tsInputType(f.Type))
	}
	w.WriteString("}\n\n")

	// Builder function.
	fmt.Fprintf(w, "/** Build a ZAP-encoded %s message from `in` and return the bytes. */\n", s.Name)
	fmt.Fprintf(w, "export function new%s(in_: %sInput): Uint8Array {\n", s.Name, s.Name)
	w.WriteString("  const b = new Builder(256);\n")
	fmt.Fprintf(w, "  const ob = b.startObject(%sSize);\n", lower)
	for _, f := range s.Fields {
		emitTSFieldWriter(w, lower, f)
	}
	w.WriteString("  ob.finishAsRoot();\n")
	w.WriteString("  return b.finish();\n")
	w.WriteString("}\n\n")
}

func emitTSFieldWriter(w *bytes.Buffer, lower string, f *Field) {
	off := fmt.Sprintf("%sOff.%s", lower, f.Name)
	name := camelLower(f.Name)
	switch f.Type.Kind {
	case KindBool:
		fmt.Fprintf(w, "  ob.setBool(%s, in_.%s);\n", off, name)
	case KindU8:
		fmt.Fprintf(w, "  ob.setU8(%s, in_.%s);\n", off, name)
	case KindU16:
		fmt.Fprintf(w, "  ob.setU16(%s, in_.%s);\n", off, name)
	case KindU32:
		fmt.Fprintf(w, "  ob.setU32(%s, in_.%s);\n", off, name)
	case KindU64:
		fmt.Fprintf(w, "  ob.setU64(%s, in_.%s);\n", off, name)
	case KindI8:
		fmt.Fprintf(w, "  ob.setI8(%s, in_.%s);\n", off, name)
	case KindI16:
		fmt.Fprintf(w, "  ob.setI16(%s, in_.%s);\n", off, name)
	case KindI32:
		fmt.Fprintf(w, "  ob.setI32(%s, in_.%s);\n", off, name)
	case KindI64:
		fmt.Fprintf(w, "  ob.setI64(%s, in_.%s);\n", off, name)
	case KindF32:
		fmt.Fprintf(w, "  ob.setF32(%s, in_.%s);\n", off, name)
	case KindF64:
		fmt.Fprintf(w, "  ob.setF64(%s, in_.%s);\n", off, name)
	case KindText:
		fmt.Fprintf(w, "  ob.setText(%s, in_.%s);\n", off, name)
	case KindBytes:
		fmt.Fprintf(w, "  ob.setBytes(%s, in_.%s);\n", off, name)
	case KindBytesFixed:
		fmt.Fprintf(w, "  ob.setBytesFixed(%s, in_.%s);\n", off, name)
	case KindList:
		listVar := camelLower(f.Name) + "LB"
		fmt.Fprintf(w, "  const %s = b.startList();\n", listVar)
		fmt.Fprintf(w, "  for (const elem of in_.%s) %s.addObjectBytes(elem);\n", name, listVar)
		fmt.Fprintf(w, "  ob.setList(%s, %s.finishOffset(), in_.%s.length);\n", off, listVar, name)
	case KindStruct:
		// Nested struct: caller passes a pre-built sub-buffer; embed it inline.
		// Mirrors the Go path (StartObject(len) + SetBytesFixed(0, …) + SetObject).
		fmt.Fprintf(w, "  if (in_.%s.length > 0) {\n", name)
		fmt.Fprintf(w, "    const nested = b.startObject(in_.%s.length);\n", name)
		fmt.Fprintf(w, "    nested.setBytesFixed(0, in_.%s);\n", name)
		fmt.Fprintf(w, "    ob.setObject(%s, nested.finish());\n", off)
		w.WriteString("  }\n")
	}
}

// tsInputType returns the TS type used in the Input interface. Mirrors
// goInputType: scalars map to number/bigint/boolean, variable bytes/text to
// Uint8Array/string, list<T> to Uint8Array[] (pre-built sub-buffers), nested
// struct to Uint8Array (pre-built sub-buffer).
func tsInputType(t Type) string {
	switch t.Kind {
	case KindBool:
		return "boolean"
	case KindU8, KindU16, KindU32, KindI8, KindI16, KindI32, KindF32, KindF64:
		return "number"
	case KindU64, KindI64:
		return "bigint"
	case KindText:
		return "string"
	case KindBytes, KindBytesFixed:
		return "Uint8Array"
	case KindList:
		return "Uint8Array[]"
	case KindStruct:
		return "Uint8Array"
	}
	return "unknown"
}

// fileHasList reports whether any struct field is a list<T> — gates the
// type-only ListView import.
func fileHasList(f *File) bool {
	for _, s := range f.Structs {
		for _, fld := range s.Fields {
			if fld.Type.Kind == KindList {
				return true
			}
		}
	}
	return false
}

// camelLower lowercases the first byte of a field name for the TS surface
// (TS convention is camelCase members; the schema uses PascalCase fields).
// ASCII-only, matching lowerFirst's domain.
func camelLower(s string) string {
	return lowerFirst(s)
}
