// Copyright (C) 2025, Lux Industries Inc. All rights reserved.
// See the file LICENSE for licensing terms.

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

// Emit emits one .go file per struct AND one per interface in f. Returns a
// map of basename → gofmt-clean bytes, ready to write. The basename is the
// lowercase snake-cased struct/interface name plus "_zap.go" (matches the
// spec convention).
func Emit(f *File) (map[string][]byte, error) {
	out := make(map[string][]byte, len(f.Structs)+len(f.Interfaces))
	for _, s := range f.Structs {
		buf, err := emitStruct(f, s)
		if err != nil {
			return nil, fmt.Errorf("emit %s: %w", s.Name, err)
		}
		clean, err := format.Source(buf)
		if err != nil {
			return nil, fmt.Errorf("gofmt %s: %w\n--- raw ---\n%s\n--- end ---", s.Name, err, buf)
		}
		out[snakeCase(s.Name)+"_zap.go"] = clean
	}
	for _, iface := range f.Interfaces {
		buf, err := emitInterfaceFile(f, iface)
		if err != nil {
			return nil, fmt.Errorf("emit %s: %w", iface.Name, err)
		}
		clean, err := format.Source(buf)
		if err != nil {
			return nil, fmt.Errorf("gofmt %s: %w\n--- raw ---\n%s\n--- end ---", iface.Name, err, buf)
		}
		out[snakeCase(iface.Name)+"_zap.go"] = clean
	}
	return out, nil
}

// EmitSingle emits one combined .go file containing all structs and
// interfaces from f. Returns the basename (derived from the schema source
// filename) and the gofmt-clean bytes. Used by callers that prefer one
// file per schema over one file per struct.
func EmitSingle(f *File) (string, []byte, error) {
	if len(f.Structs) == 0 && len(f.Interfaces) == 0 {
		return "", nil, fmt.Errorf("no structs or interfaces to emit")
	}
	source := f.Source
	if source == "" {
		source = f.Package + ".zap"
	}
	// Output filename: strip the .zap extension, snake_case, append _zap.go.
	base := source
	if i := strings.LastIndex(base, "."); i >= 0 {
		base = base[:i]
	}
	outName := base + "_zap.go"

	var w bytes.Buffer
	writeFileHeader(&w, f.Package, source, len(f.Structs) > 0, len(f.Interfaces) > 0)

	for _, s := range f.Structs {
		if err := validate(s); err != nil {
			return "", nil, err
		}
		emitOffsets(&w, s)
		emitReader(&w, s)
		emitBuilder(&w, s)
		w.WriteString("\n")
	}
	for _, iface := range f.Interfaces {
		if err := validateInterface(f, iface); err != nil {
			return "", nil, err
		}
		emitInterface(&w, iface)
	}
	clean, err := format.Source(w.Bytes())
	if err != nil {
		return "", nil, fmt.Errorf("gofmt: %w\n--- raw ---\n%s\n--- end ---", err, w.Bytes())
	}
	return outName, clean, nil
}

// writeFileHeader writes the generated-file banner, package clause, and
// import block. Only the imports actually used by the emitted code are
// written: structs reference zap; interfaces reference fmt + rpc. A
// combined file with both gets all three. Go rejects unused imports, so
// these flags must match what the body emits.
func writeFileHeader(w *bytes.Buffer, pkg, source string, needsZap, needsRPC bool) {
	w.WriteString("// Code generated by zapgen; DO NOT EDIT.\n")
	fmt.Fprintf(w, "// source: %s\n\n", source)
	fmt.Fprintf(w, "package %s\n\n", pkg)
	w.WriteString("import (\n")
	if needsRPC {
		// The generated Client reports a non-OK status via fmt.Errorf.
		w.WriteString("\t\"fmt\"\n")
	}
	if needsZap {
		w.WriteString("\tzap \"github.com/zap-proto/go\"\n")
	}
	if needsRPC {
		w.WriteString("\t\"github.com/zap-proto/go/rpc\"\n")
	}
	w.WriteString(")\n\n")
}

// structSize returns the total fixed-section size for s. The size is
// max(field.Offset + field.SlotSize()) over all fields, rounded up to
// the alignment boundary if needed. We do NOT round here — the spec is
// explicit-offset, author-controlled; the reported size equals
// max(end-of-field).
func structSize(s *Struct) int {
	size := 0
	for _, f := range s.Fields {
		end := f.Offset + f.Type.SlotSize()
		if end > size {
			size = end
		}
	}
	return size
}

func emitStruct(f *File, s *Struct) ([]byte, error) {
	if err := validate(s); err != nil {
		return nil, err
	}
	var w bytes.Buffer
	writeFileHeader(&w, f.Package, sourceName(f), true, false)
	emitOffsets(&w, s)
	emitReader(&w, s)
	emitBuilder(&w, s)
	return w.Bytes(), nil
}

// emitInterfaceFile emits one standalone .go file for a single interface
// (the per-interface output of Emit). It imports rpc for the call envelope.
func emitInterfaceFile(f *File, iface *Interface) ([]byte, error) {
	if err := validateInterface(f, iface); err != nil {
		return nil, err
	}
	var w bytes.Buffer
	writeFileHeader(&w, f.Package, sourceName(f), false, true)
	emitInterface(&w, iface)
	return w.Bytes(), nil
}

// sourceName returns the recorded source basename, or a fallback derived
// from the package for callers that build a File directly without Parse.
func sourceName(f *File) string {
	if f.Source != "" {
		return f.Source
	}
	return f.Package + ".zap"
}

// validateInterface checks that every method param references a struct
// declared in the same file (method payloads are ZAP structs) and that
// method names are unique within the interface. Fail fast and loud.
func validateInterface(f *File, iface *Interface) error {
	if len(iface.Methods) == 0 {
		return fmt.Errorf("interface %s: no methods", iface.Name)
	}
	known := make(map[string]bool, len(f.Structs))
	for _, s := range f.Structs {
		known[s.Name] = true
	}
	seen := make(map[string]bool, len(iface.Methods))
	for _, m := range iface.Methods {
		if seen[m.Name] {
			return fmt.Errorf("interface %s: duplicate method %s", iface.Name, m.Name)
		}
		seen[m.Name] = true
		for _, p := range []*Param{m.Request, m.Response} {
			if p == nil {
				continue
			}
			if !known[p.StructName] {
				return fmt.Errorf("interface %s method %s: unknown struct %q in param %q",
					iface.Name, m.Name, p.StructName, p.Name)
			}
		}
	}
	return nil
}

// validate checks for offset overlap and bad field types. Fail fast and
// loud — the schema author is responsible for the layout, but a typo
// shouldn't silently emit broken code.
func validate(s *Struct) error {
	size := structSize(s)
	if size == 0 {
		return fmt.Errorf("struct %s: no fields", s.Name)
	}
	owner := make([]string, size)
	for _, f := range s.Fields {
		sz := f.Type.SlotSize()
		if sz == 0 {
			return fmt.Errorf("struct %s field %s: unsupported type %s", s.Name, f.Name, f.Type.Kind)
		}
		if f.Offset < 0 {
			return fmt.Errorf("struct %s field %s: negative offset %d", s.Name, f.Name, f.Offset)
		}
		for i := 0; i < sz; i++ {
			pos := f.Offset + i
			if owner[pos] != "" {
				return fmt.Errorf("struct %s: field %s at offset %d overlaps field %s",
					s.Name, f.Name, pos, owner[pos])
			}
			owner[pos] = f.Name
		}
	}
	return nil
}

func emitOffsets(w *bytes.Buffer, s *Struct) {
	w.WriteString("const (\n")
	lower := lowerFirst(s.Name)
	for _, f := range s.Fields {
		fmt.Fprintf(w, "\t%s%sOff = %d\n", lower, f.Name, f.Offset)
	}
	fmt.Fprintf(w, "\t%sSize = %d\n", lower, structSize(s))
	w.WriteString(")\n\n")
}

func emitReader(w *bytes.Buffer, s *Struct) {
	fmt.Fprintf(w, "// %s is a zero-copy view into a ZAP-encoded %s message.\n", s.Name, s.Name)
	fmt.Fprintf(w, "type %s struct{ o zap.Object }\n\n", s.Name)

	fmt.Fprintf(w, "// Wrap%s parses b and returns a typed view. Returns an error if the\n", s.Name)
	w.WriteString("// wire-level checks (magic, version, size) fail.\n")
	fmt.Fprintf(w, "func Wrap%s(b []byte) (%s, error) {\n", s.Name, s.Name)
	w.WriteString("\tm, err := zap.Parse(b)\n")
	w.WriteString("\tif err != nil {\n")
	fmt.Fprintf(w, "\t\treturn %s{}, err\n", s.Name)
	w.WriteString("\t}\n")
	fmt.Fprintf(w, "\treturn %s{o: m.Root()}, nil\n", s.Name)
	w.WriteString("}\n\n")

	lower := lowerFirst(s.Name)
	for _, f := range s.Fields {
		emitFieldReader(w, s.Name, lower, f)
	}
}

func emitFieldReader(w *bytes.Buffer, structName, lower string, f *Field) {
	offsetConst := fmt.Sprintf("%s%sOff", lower, f.Name)
	switch f.Type.Kind {
	case KindBool:
		fmt.Fprintf(w, "func (t %s) %s() bool { return t.o.Bool(%s) }\n", structName, f.Name, offsetConst)
	case KindU8:
		fmt.Fprintf(w, "func (t %s) %s() uint8 { return t.o.Uint8(%s) }\n", structName, f.Name, offsetConst)
	case KindU16:
		fmt.Fprintf(w, "func (t %s) %s() uint16 { return t.o.Uint16(%s) }\n", structName, f.Name, offsetConst)
	case KindU32:
		fmt.Fprintf(w, "func (t %s) %s() uint32 { return t.o.Uint32(%s) }\n", structName, f.Name, offsetConst)
	case KindU64:
		fmt.Fprintf(w, "func (t %s) %s() uint64 { return t.o.Uint64(%s) }\n", structName, f.Name, offsetConst)
	case KindI8:
		fmt.Fprintf(w, "func (t %s) %s() int8 { return t.o.Int8(%s) }\n", structName, f.Name, offsetConst)
	case KindI16:
		fmt.Fprintf(w, "func (t %s) %s() int16 { return t.o.Int16(%s) }\n", structName, f.Name, offsetConst)
	case KindI32:
		fmt.Fprintf(w, "func (t %s) %s() int32 { return t.o.Int32(%s) }\n", structName, f.Name, offsetConst)
	case KindI64:
		fmt.Fprintf(w, "func (t %s) %s() int64 { return t.o.Int64(%s) }\n", structName, f.Name, offsetConst)
	case KindF32:
		fmt.Fprintf(w, "func (t %s) %s() float32 { return t.o.Float32(%s) }\n", structName, f.Name, offsetConst)
	case KindF64:
		fmt.Fprintf(w, "func (t %s) %s() float64 { return t.o.Float64(%s) }\n", structName, f.Name, offsetConst)
	case KindText:
		fmt.Fprintf(w, "func (t %s) %s() string { return t.o.Text(%s) }\n", structName, f.Name, offsetConst)
	case KindBytes:
		fmt.Fprintf(w, "func (t %s) %s() []byte { return t.o.Bytes(%s) }\n", structName, f.Name, offsetConst)
	case KindBytesFixed:
		fmt.Fprintf(w, "func (t %s) %s() [%d]byte {\n", structName, f.Name, f.Type.FixedSize)
		fmt.Fprintf(w, "\tvar out [%d]byte\n", f.Type.FixedSize)
		fmt.Fprintf(w, "\tcopy(out[:], t.o.BytesFixed(%s, %d))\n", offsetConst, f.Type.FixedSize)
		w.WriteString("\treturn out\n")
		w.WriteString("}\n")
	case KindList:
		fmt.Fprintf(w, "func (t %s) %s() zap.List { return t.o.List(%s) }\n", structName, f.Name, offsetConst)
	case KindStruct:
		fmt.Fprintf(w, "func (t %s) %s() %s { return %s{o: t.o.Object(%s)} }\n",
			structName, f.Name, f.Type.StructName, f.Type.StructName, offsetConst)
	}
}

func emitBuilder(w *bytes.Buffer, s *Struct) {
	// Input struct.
	fmt.Fprintf(w, "\n// %sInput collects the field values for New%s.\n", s.Name, s.Name)
	fmt.Fprintf(w, "type %sInput struct {\n", s.Name)
	for _, f := range s.Fields {
		fmt.Fprintf(w, "\t%s %s\n", f.Name, goInputType(f.Type))
	}
	w.WriteString("}\n\n")

	// Constructor.
	fmt.Fprintf(w, "// New%s builds a ZAP-encoded %s message from in and returns the bytes.\n", s.Name, s.Name)
	fmt.Fprintf(w, "func New%s(in %sInput) []byte {\n", s.Name, s.Name)
	w.WriteString("\tb := zap.NewBuilder(256)\n")
	lower := lowerFirst(s.Name)
	fmt.Fprintf(w, "\tob := b.StartObject(%sSize)\n", lower)

	// Two-pass: fixed-section first, then variable-tail (lists last so we
	// don't interleave list-element writes with deferred-bytes writes).
	for _, f := range s.Fields {
		emitFieldWriter(w, lower, f)
	}

	w.WriteString("\tob.FinishAsRoot()\n")
	w.WriteString("\treturn b.Finish()\n")
	w.WriteString("}\n")
}

// goInputType returns the Go type used in the Input struct.
func goInputType(t Type) string {
	switch t.Kind {
	case KindBool:
		return "bool"
	case KindU8:
		return "uint8"
	case KindU16:
		return "uint16"
	case KindU32:
		return "uint32"
	case KindU64:
		return "uint64"
	case KindI8:
		return "int8"
	case KindI16:
		return "int16"
	case KindI32:
		return "int32"
	case KindI64:
		return "int64"
	case KindF32:
		return "float32"
	case KindF64:
		return "float64"
	case KindText:
		return "string"
	case KindBytes:
		return "[]byte"
	case KindBytesFixed:
		return fmt.Sprintf("[%d]byte", t.FixedSize)
	case KindList:
		// Variable-element list: each entry is a pre-built sub-buffer.
		return "[][]byte"
	case KindStruct:
		// Nested struct: caller passes a pre-built sub-buffer.
		return "[]byte"
	}
	return "any"
}

func emitFieldWriter(w *bytes.Buffer, lower string, f *Field) {
	offsetConst := fmt.Sprintf("%s%sOff", lower, f.Name)
	switch f.Type.Kind {
	case KindBool:
		fmt.Fprintf(w, "\tob.SetBool(%s, in.%s)\n", offsetConst, f.Name)
	case KindU8:
		fmt.Fprintf(w, "\tob.SetUint8(%s, in.%s)\n", offsetConst, f.Name)
	case KindU16:
		fmt.Fprintf(w, "\tob.SetUint16(%s, in.%s)\n", offsetConst, f.Name)
	case KindU32:
		fmt.Fprintf(w, "\tob.SetUint32(%s, in.%s)\n", offsetConst, f.Name)
	case KindU64:
		fmt.Fprintf(w, "\tob.SetUint64(%s, in.%s)\n", offsetConst, f.Name)
	case KindI8:
		fmt.Fprintf(w, "\tob.SetUint8(%s, uint8(in.%s))\n", offsetConst, f.Name)
	case KindI16:
		fmt.Fprintf(w, "\tob.SetUint16(%s, uint16(in.%s))\n", offsetConst, f.Name)
	case KindI32:
		fmt.Fprintf(w, "\tob.SetUint32(%s, uint32(in.%s))\n", offsetConst, f.Name)
	case KindI64:
		fmt.Fprintf(w, "\tob.SetUint64(%s, uint64(in.%s))\n", offsetConst, f.Name)
	case KindF32:
		fmt.Fprintf(w, "\tob.SetFloat32(%s, in.%s)\n", offsetConst, f.Name)
	case KindF64:
		fmt.Fprintf(w, "\tob.SetFloat64(%s, in.%s)\n", offsetConst, f.Name)
	case KindText:
		fmt.Fprintf(w, "\tob.SetText(%s, in.%s)\n", offsetConst, f.Name)
	case KindBytes:
		fmt.Fprintf(w, "\tob.SetBytes(%s, in.%s)\n", offsetConst, f.Name)
	case KindBytesFixed:
		fmt.Fprintf(w, "\tob.SetBytesFixed(%s, in.%s[:])\n", offsetConst, f.Name)
	case KindList:
		listVar := lowerFirst(f.Name) + "LB"
		fmt.Fprintf(w, "\t%s := b.StartList(0)\n", listVar)
		fmt.Fprintf(w, "\tfor _, elem := range in.%s {\n", f.Name)
		fmt.Fprintf(w, "\t\t%s.AddObjectBytes(elem)\n", listVar)
		w.WriteString("\t}\n")
		fmt.Fprintf(w, "\tob.SetList(%s, %s.FinishOffset(), len(in.%s))\n",
			offsetConst, listVar, f.Name)
	case KindStruct:
		// Nested struct: caller passes a built sub-buffer; embed it inline.
		// We allocate via b.StartObject(len(in.X)) and copy the bytes.
		fmt.Fprintf(w, "\tif len(in.%s) > 0 {\n", f.Name)
		fmt.Fprintf(w, "\t\tnested := b.StartObject(len(in.%s))\n", f.Name)
		fmt.Fprintf(w, "\t\tnested.SetBytesFixed(0, in.%s)\n", f.Name)
		fmt.Fprintf(w, "\t\tob.SetObject(%s, nested.Finish())\n", offsetConst)
		w.WriteString("\t}\n")
	}
}

// --- service emission (interface → ordinal table + Client + Server) ---------

// emitInterface emits, for one interface:
//   - a method-ordinal const table (<Iface><Method>Ordinal)
//   - a Channel interface (the transport seam the Client ships calls over)
//   - a typed Client (one method per declared method)
//   - a Handler interface (the abstract server contract) plus a
//     Dispatch<Iface> function that decodes the ordinal and routes to it.
//
// Ordinals are 1, 2, 3, … by declaration order, baked from the AST so the
// wire ordinal never shifts when a method is appended. The wire envelope
// is the runtime rpc package, shared with every other language runtime.
func emitInterface(w *bytes.Buffer, iface *Interface) {
	emitOrdinals(w, iface)
	emitClient(w, iface)
	emitServer(w, iface)
}

func emitOrdinals(w *bytes.Buffer, iface *Interface) {
	fmt.Fprintf(w, "// Method ordinals for the %s service (stable 1-based wire ids).\n", iface.Name)
	w.WriteString("const (\n")
	for _, m := range iface.Methods {
		fmt.Fprintf(w, "\t%s uint32 = %d\n", ordinalName(iface, m), m.Ordinal)
	}
	w.WriteString(")\n\n")
}

// ordinalName is the exported const holding a method's wire ordinal,
// e.g. interface Echo + method ping -> EchoPingOrdinal.
func ordinalName(iface *Interface, m *Method) string {
	return iface.Name + exportIdent(m.Name) + "Ordinal"
}

// exportIdent upper-cases the first letter of a (possibly lowercase)
// schema method name so the generated Go identifier is exported. Schema
// method names are written lowercase (`ping`) per the spec; the generated
// client/handler methods and ordinal consts must be exported so consumers
// in other packages can reach them.
func exportIdent(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	if r[0] >= 'a' && r[0] <= 'z' {
		r[0] -= 'a' - 'A'
	}
	return string(r)
}

func emitClient(w *bytes.Buffer, iface *Interface) {
	// Channel: the seam the Client ships an envelope over and awaits a
	// correlated response. A transport (e.g. a TCP RPC connection) supplies it.
	fmt.Fprintf(w, "// %sChannel ships one Call envelope and awaits its correlated Response.\n", iface.Name)
	fmt.Fprintf(w, "type %sChannel interface {\n", iface.Name)
	w.WriteString("\tCall(envelope []byte) (rpc.Response, error)\n")
	w.WriteString("}\n\n")

	// Client.
	fmt.Fprintf(w, "// %sClient is a typed RPC client for the %s service over a ZAP call channel.\n", iface.Name, iface.Name)
	fmt.Fprintf(w, "type %sClient struct {\n", iface.Name)
	fmt.Fprintf(w, "\tch  %sChannel\n", iface.Name)
	w.WriteString("\tcap []byte\n")
	w.WriteString("}\n\n")

	fmt.Fprintf(w, "// New%sClient returns a client that issues calls over ch, attaching cap\n", iface.Name)
	w.WriteString("// (which may be nil) to every request.\n")
	fmt.Fprintf(w, "func New%sClient(ch %sChannel, capability []byte) *%sClient {\n", iface.Name, iface.Name, iface.Name)
	fmt.Fprintf(w, "\treturn &%sClient{ch: ch, cap: capability}\n", iface.Name)
	w.WriteString("}\n\n")

	for _, m := range iface.Methods {
		emitClientMethod(w, iface, m)
	}
}

func emitClientMethod(w *bytes.Buffer, iface *Interface, m *Method) {
	mname := exportIdent(m.Name)
	arg, payload := methodArg(m)
	ret := "error"
	if m.Response != nil {
		ret = "([]byte, error)"
	}
	fmt.Fprintf(w, "func (c *%sClient) %s(%s) %s {\n", iface.Name, mname, arg, ret)
	w.WriteString("\tresp, err := c.ch.Call(rpc.BuildRequest(rpc.Call{\n")
	fmt.Fprintf(w, "\t\tMethod:  %s,\n", ordinalName(iface, m))
	w.WriteString("\t\tTarget:  rpc.NoTarget,\n")
	w.WriteString("\t\tCap:     c.cap,\n")
	fmt.Fprintf(w, "\t\tPayload: %s,\n", payload)
	w.WriteString("\t}))\n")
	if m.Response != nil {
		w.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
		w.WriteString("\tif resp.Status != rpc.StatusOK {\n")
		fmt.Fprintf(w, "\t\treturn nil, fmt.Errorf(\"%s.%s: status %%d\", resp.Status)\n", iface.Name, mname)
		w.WriteString("\t}\n")
		w.WriteString("\treturn resp.Body, nil\n")
	} else {
		w.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
		w.WriteString("\tif resp.Status != rpc.StatusOK {\n")
		fmt.Fprintf(w, "\t\treturn fmt.Errorf(\"%s.%s: status %%d\", resp.Status)\n", iface.Name, mname)
		w.WriteString("\t}\n")
		w.WriteString("\treturn nil\n")
	}
	w.WriteString("}\n\n")
}

// methodArg returns the Go parameter list and the payload expression for a
// method's request: ("req []byte", "req") when it has a request param, or
// ("", "nil") for a void request.
func methodArg(m *Method) (arg, payload string) {
	if m.Request == nil {
		return "", "nil"
	}
	return m.Request.Name + " []byte", m.Request.Name
}

func emitServer(w *bytes.Buffer, iface *Interface) {
	// Handler: the abstract server contract — one method per RPC method.
	fmt.Fprintf(w, "// %sHandler is the server contract for the %s service. Implement each\n", iface.Name, iface.Name)
	fmt.Fprintf(w, "// method, then route requests to it with Dispatch%s.\n", iface.Name)
	fmt.Fprintf(w, "type %sHandler interface {\n", iface.Name)
	for _, m := range iface.Methods {
		arg, _ := methodArg(m)
		ret := "error"
		if m.Response != nil {
			ret = "([]byte, error)"
		}
		fmt.Fprintf(w, "\t%s(%s) %s\n", exportIdent(m.Name), arg, ret)
	}
	w.WriteString("}\n\n")

	// Dispatch: decode the request envelope, route by ordinal, build the
	// response envelope.
	fmt.Fprintf(w, "// Dispatch%s decodes a Call envelope, routes it by method ordinal to h,\n", iface.Name)
	w.WriteString("// and returns the response envelope. An unknown ordinal yields a\n")
	w.WriteString("// StatusNotFound response; a handler error yields StatusInternal.\n")
	fmt.Fprintf(w, "func Dispatch%s(h %sHandler, envelope []byte) ([]byte, error) {\n", iface.Name, iface.Name)
	w.WriteString("\tcall, err := rpc.ParseRequest(envelope)\n")
	w.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	w.WriteString("\tswitch call.Method {\n")
	for _, m := range iface.Methods {
		fmt.Fprintf(w, "\tcase %s:\n", ordinalName(iface, m))
		emitDispatchCase(w, m)
	}
	w.WriteString("\tdefault:\n")
	w.WriteString("\t\treturn rpc.BuildResponse(rpc.StatusNotFound, call.PromiseID, nil), nil\n")
	w.WriteString("\t}\n")
	w.WriteString("}\n\n")
}

// emitDispatchCase emits the body of one ordinal case in Dispatch<Iface>.
func emitDispatchCase(w *bytes.Buffer, m *Method) {
	mname := exportIdent(m.Name)
	callArg := ""
	if m.Request != nil {
		callArg = "call.Payload"
	}
	if m.Response != nil {
		fmt.Fprintf(w, "\t\tbody, err := h.%s(%s)\n", mname, callArg)
		w.WriteString("\t\tif err != nil {\n")
		w.WriteString("\t\t\treturn rpc.BuildResponse(rpc.StatusInternal, call.PromiseID, nil), nil\n")
		w.WriteString("\t\t}\n")
		w.WriteString("\t\treturn rpc.BuildResponse(rpc.StatusOK, call.PromiseID, body), nil\n")
	} else {
		fmt.Fprintf(w, "\t\tif err := h.%s(%s); err != nil {\n", mname, callArg)
		w.WriteString("\t\t\treturn rpc.BuildResponse(rpc.StatusInternal, call.PromiseID, nil), nil\n")
		w.WriteString("\t\t}\n")
		w.WriteString("\t\treturn rpc.BuildResponse(rpc.StatusOK, call.PromiseID, nil), nil\n")
	}
}

// snakeCase converts CamelCase / PascalCase to snake_case. ASCII only —
// our schema identifiers are Go identifiers.
func snakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		if r >= 'A' && r <= 'Z' {
			b.WriteRune(r + ('a' - 'A'))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// lowerFirst returns s with the first byte lowercased (ASCII). Used to
// build "baseTxFooOff" constants from struct name "BaseTx" + field
// "Foo".
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	if r[0] >= 'A' && r[0] <= 'Z' {
		r[0] = r[0] + ('a' - 'A')
	}
	return string(r)
}
