// SPDX-License-Identifier: BSD-3-Clause-Eco
// Copyright (C) 2025, Lux Industries Inc. All rights reserved.
// See the file LICENSE for licensing terms.

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"strings"
)

// The Rust backend. It shares the parser, the desugar and the schema model
// with the Go backend and differs only in what it writes: one module per
// schema, holding a zero-copy view and a builder for every struct, and the
// ordinals, client and dispatch for every interface.
//
// Rust's compilation unit is the module, not the directory, so a schema
// emits ONE .rs file — the per-struct file split the Go backend uses would
// oblige every consumer to write a `mod` line per struct.
//
// The runtime the emitted code calls travels with the generator (rust/zap.rs
// and, for interfaces, rust/rpc.rs) and is written out beside the module. It
// is the one piece of Rust in the toolchain that is not derived from a
// schema, so it is fixed here once for every language consumer at a time.

//go:embed rust/zap.rs
var rustRuntime []byte

//go:embed rust/rpc.rs
var rustCallRuntime []byte

// EmitRust returns basename → file bytes for f: the schema's module plus
// the runtime files it calls. runtimePath is the Rust module path the
// generated code reaches the runtime through (e.g. "crate::zap").
func EmitRust(f *File, runtimePath string) (map[string][]byte, error) {
	if len(f.Structs) == 0 && len(f.Interfaces) == 0 {
		return nil, fmt.Errorf("no structs or interfaces to emit")
	}
	if runtimePath == "" {
		runtimePath = defaultRustRuntime
	}
	body, err := emitRustModule(f, runtimePath)
	if err != nil {
		return nil, err
	}
	out := map[string][]byte{rustModuleName(f): body}
	if runtimePath != defaultRustRuntime {
		// The runtime lives in the crate the caller named, which already
		// holds it. A second copy beside the module would be a second
		// runtime that compiles.
		return out, nil
	}
	out["zap.rs"] = rustRuntime
	if len(f.Interfaces) > 0 {
		out["rpc.rs"] = rustCallRuntime
	}
	return out, nil
}

// defaultRustRuntime is where the emitted code looks for the runtime when
// the caller does not say: the crate root, which is where the emitted
// zap.rs and rpc.rs belong unless a crate files them elsewhere.
const defaultRustRuntime = "crate"

// rustModuleName is the emitted module's filename: the schema's basename
// with the .zap extension replaced by _zap.rs.
func rustModuleName(f *File) string {
	base := f.Source
	if base == "" {
		base = f.Package + ".zap"
	}
	if i := strings.LastIndex(base, "."); i >= 0 {
		base = base[:i]
	}
	return base + "_zap.rs"
}

func emitRustModule(f *File, runtimePath string) ([]byte, error) {
	var w bytes.Buffer
	source := sourceName(f)
	w.WriteString("// Code generated by zapgen; DO NOT EDIT.\n")
	fmt.Fprintf(&w, "// source: %s\n\n", source)
	fmt.Fprintf(&w, "//! ZAP schema `%s`, package `%s`.\n", source, f.Package)
	w.WriteString("//!\n")
	w.WriteString("//! Every view here borrows the buffer it reads: a field is a bounds-checked\n")
	w.WriteString("//! look at bytes already in hand, never a decode into an owned struct. The\n")
	w.WriteString("//! builders write into one buffer and hand it over at the end.\n\n")
	// A schema declares a whole shape; a consumer uses the part it needs.
	// The rest is not dead code, it is the shape.
	w.WriteString("#![allow(dead_code)]\n\n")
	// Alphabetical, which is where rustfmt would put them.
	if len(f.Interfaces) > 0 {
		fmt.Fprintf(&w, "use %s::rpc;\n", runtimePath)
	}
	fmt.Fprintf(&w, "use %s::zap;\n", runtimePath)
	w.WriteString("\n")

	for _, s := range f.Structs {
		if err := validate(s); err != nil {
			return nil, err
		}
		emitRustOffsets(&w, s)
		emitRustReader(&w, f, s)
		emitRustBuilder(&w, f, s)
	}
	for _, iface := range f.Interfaces {
		if err := validateInterface(f, iface); err != nil {
			return nil, err
		}
		emitRustOrdinals(&w, iface)
		emitRustClient(&w, iface)
		emitRustServer(&w, iface)
	}
	return w.Bytes(), nil
}

// --- structs ---------------------------------------------------------------

func emitRustOffsets(w *bytes.Buffer, s *Struct) {
	fmt.Fprintf(w, "// %s — field offsets, in bytes, and the fixed section's size.\n", s.Name)
	prefix := screamCase(s.Name)
	for _, f := range s.Fields {
		fmt.Fprintf(w, "pub const %s_%s: usize = %d;\n", prefix, screamCase(f.Name), f.Offset)
	}
	fmt.Fprintf(w, "pub const %s_SIZE: usize = %d;\n\n", prefix, structSize(s))
}

func emitRustReader(w *bytes.Buffer, f *File, s *Struct) {
	fmt.Fprintf(w, "/// A view of a ZAP-encoded %s. Reading a field costs a bounds check.\n", s.Name)
	w.WriteString("#[derive(Clone, Copy, Debug)]\n")
	fmt.Fprintf(w, "pub struct %s<'a> {\n", s.Name)
	w.WriteString("    o: zap::Object<'a>,\n")
	w.WriteString("}\n\n")

	fmt.Fprintf(w, "impl<'a> %s<'a> {\n", s.Name)
	fmt.Fprintf(w, "    /// Take `data` as a %s message. Fails only on the wire-level\n", s.Name)
	w.WriteString("    /// checks — magic, version, declared size.\n")
	w.WriteString("    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {\n")
	fmt.Fprintf(w, "        Ok(%s {\n", s.Name)
	w.WriteString("            o: zap::Message::parse(data)?.root(),\n")
	w.WriteString("        })\n")
	w.WriteString("    }\n\n")
	fmt.Fprintf(w, "    /// A view of an object already located in a message — a nested\n")
	w.WriteString("    /// field, or one element of a list.\n")
	w.WriteString("    pub fn new(o: zap::Object<'a>) -> Self {\n")
	fmt.Fprintf(w, "        %s { o }\n", s.Name)
	w.WriteString("    }\n\n")
	w.WriteString("    /// The object this view reads.\n")
	w.WriteString("    pub fn object(&self) -> zap::Object<'a> {\n")
	w.WriteString("        self.o\n")
	w.WriteString("    }\n")

	prefix := screamCase(s.Name)
	for _, fld := range s.Fields {
		w.WriteString("\n")
		emitRustFieldReader(w, f, prefix, fld)
		emitRustElemReader(w, f, prefix, fld)
	}
	w.WriteString("}\n\n")
}

// emitRustElemReader emits the typed element accessor of a list of structs,
// so a caller reads one element by name instead of by stride. An inline
// element sits at i*Size in the list's own run; one with a tail is its own
// message, and the list holds those end to end.
func emitRustElemReader(w *bytes.Buffer, f *File, prefix string, fld *Field) {
	if fld.Type.Kind != KindList || fld.Type.ListElem == nil {
		return
	}
	name := rustIdent(snakeCase2(fld.Name))
	if aimed := f.PtrElem(fld.Type); aimed != nil {
		fmt.Fprintf(w, "\n    /// Element `i` of `%s`, the object its pointer names.\n", name)
		fmt.Fprintf(w, "    pub fn %s_at(&self, i: usize) -> %s<'a> {\n", name, aimed.Name)
		fmt.Fprintf(w, "        %s::new(self.%s().object_ptr(i))\n", aimed.Name, name)
		w.WriteString("    }\n")
		return
	}
	if fld.Type.ListElem.Kind != KindStruct {
		return
	}
	elem := f.Find(fld.Type.ListElem.StructName)
	if elem == nil {
		return
	}
	fmt.Fprintf(w, "\n    /// Element `i` of `%s`. Out of range answers the zero view.\n", name)
	fmt.Fprintf(w, "    pub fn %s_at(&self, i: usize) -> %s<'a> {\n", name, elem.Name)
	if elem.Inline() {
		fmt.Fprintf(w, "        %s::new(self.%s().object(i, %s_SIZE))\n",
			elem.Name, name, screamCase(elem.Name))
	} else {
		fmt.Fprintf(w, "        %s::new(self.%s().object_at(i))\n", elem.Name, name)
	}
	w.WriteString("    }\n")
}

func emitRustFieldReader(w *bytes.Buffer, file *File, prefix string, f *Field) {
	off := prefix + "_" + screamCase(f.Name)
	name := rustIdent(snakeCase2(f.Name))
	switch f.Type.Kind {
	case KindBool:
		fmt.Fprintf(w, "    pub fn %s(&self) -> bool {\n        self.o.bool(%s)\n    }\n", name, off)
	case KindU8, KindU16, KindU32, KindU64, KindI8, KindI16, KindI32, KindI64, KindF32, KindF64:
		call := rustScalarCall(f.Type.Kind)
		fmt.Fprintf(w, "    pub fn %s(&self) -> %s {\n        self.o.%s(%s)\n    }\n",
			name, rustScalar(f.Type.Kind), call, off)
	case KindText:
		fmt.Fprintf(w, "    pub fn %s(&self) -> &'a str {\n        self.o.text(%s)\n    }\n", name, off)
	case KindBytes:
		fmt.Fprintf(w, "    pub fn %s(&self) -> &'a [u8] {\n        self.o.bytes(%s)\n    }\n", name, off)
	case KindBytesFixed:
		n := f.Type.FixedSize
		fmt.Fprintf(w, "    /// The %d inline bytes at `%s`; zeros if the span runs off the buffer.\n", n, off)
		fmt.Fprintf(w, "    pub fn %s(&self) -> &'a [u8; %d] {\n", name, n)
		w.WriteString("        self.o\n")
		fmt.Fprintf(w, "            .bytes_fixed(%s, %d)\n", off, n)
		w.WriteString("            .try_into()\n")
		fmt.Fprintf(w, "            .unwrap_or(&[0u8; %d])\n", n)
		w.WriteString("    }\n")
	case KindList:
		fmt.Fprintf(w, "    pub fn %s(&self) -> zap::List<'a> {\n        self.o.list_stride(%s, %d)\n    }\n",
			name, off, elemWidth(file, f.Type))
	case KindStruct:
		fmt.Fprintf(w, "    pub fn %s(&self) -> %s<'a> {\n        %s::new(self.o.object(%s))\n    }\n",
			name, f.Type.StructName, f.Type.StructName, off)
	}
}

func emitRustBuilder(w *bytes.Buffer, f *File, s *Struct) {
	borrows := structBorrows(s)
	life := ""
	if borrows {
		life = "<'a>"
	}
	input := s.Name + "Input"

	fmt.Fprintf(w, "/// The field values [`%s`] writes.\n", rustBuildName(s))
	w.WriteString("#[derive(Clone, Copy, Debug)]\n")
	fmt.Fprintf(w, "pub struct %s%s {\n", input, life)
	for _, fld := range s.Fields {
		fmt.Fprintf(w, "    pub %s: %s,\n", rustIdent(snakeCase2(fld.Name)), rustInputType(f, fld.Type))
	}
	w.WriteString("}\n\n")

	// An explicit Default, not a derived one: a borrowed fixed-width field
	// has no Default of its own, and one written zero array is clearer than
	// a rule about which fields can be derived.
	fmt.Fprintf(w, "impl%s Default for %s%s {\n", life, input, life)
	w.WriteString("    fn default() -> Self {\n")
	fmt.Fprintf(w, "        %s {\n", input)
	for _, fld := range s.Fields {
		fmt.Fprintf(w, "            %s: %s,\n", rustIdent(snakeCase2(fld.Name)), rustZero(fld.Type))
	}
	w.WriteString("        }\n")
	w.WriteString("    }\n")
	w.WriteString("}\n\n")

	emitRustPack(w, s)

	prefix := screamCase(s.Name)
	fmt.Fprintf(w, "/// Write a %s into `b` and answer where its object landed.\n", s.Name)
	w.WriteString("///\n")
	w.WriteString("/// What a field points AT is written first, in field order, and the\n")
	w.WriteString("/// fixed section last: a pointer always leads backward, to bytes\n")
	w.WriteString("/// already placed.\n")
	fmt.Fprintf(w, "pub fn %s(b: &mut zap::Builder, input: &%s%s) -> usize {\n",
		rustPutName(s), input, rustAnonLife(borrows))
	for _, fld := range s.Fields {
		emitRustLeaf(w, f, fld)
	}
	for _, fld := range s.Fields {
		emitRustList(w, f, fld)
	}
	fmt.Fprintf(w, "    let mut ob = b.start_object(%s_SIZE);\n", prefix)
	for _, fld := range s.Fields {
		emitRustFieldWriter(w, prefix, fld)
	}
	w.WriteString("    ob.finish(b)\n")
	w.WriteString("}\n\n")

	fmt.Fprintf(w, "/// Write a %s message and answer its bytes.\n", s.Name)
	fmt.Fprintf(w, "pub fn %s(input: &%s%s) -> Vec<u8> {\n", rustBuildName(s), input, rustAnonLife(borrows))
	w.WriteString("    let mut b = zap::Builder::new_v2(256);\n")
	fmt.Fprintf(w, "    let at = %s(&mut b, input);\n", rustPutName(s))
	w.WriteString("    b.set_root(at);\n")
	w.WriteString("    b.finish()\n")
	w.WriteString("}\n\n")
}

// rustPutName is the free function that writes one struct into a builder in
// progress: struct Out -> put_out. new_out is that plus a message around it.
func rustPutName(s *Struct) string { return "put_" + snakeCase2(s.Name) }

// rustLife is the lifetime a struct's Input type carries, if it borrows.
func rustLife(s *Struct) string {
	if structBorrows(s) {
		return "<'a>"
	}
	return ""
}

// emitRustPack emits the record form of an inline struct: its Size bytes,
// which is what one element of a list of it looks like on the wire. A struct
// with a tail has no record form — it is written as its own message.
func emitRustPack(w *bytes.Buffer, s *Struct) {
	if !s.Inline() {
		return
	}
	prefix := screamCase(s.Name)
	borrows := structBorrows(s)
	fmt.Fprintf(w, "/// %s as the %s_SIZE bytes one element of a list holds.\n", s.Name, prefix)
	fmt.Fprintf(w, "pub fn %s(input: &%sInput%s) -> [u8; %s_SIZE] {\n",
		rustPackName(s), s.Name, rustAnonLife(borrows), prefix)
	fmt.Fprintf(w, "    let mut r = [0u8; %s_SIZE];\n", prefix)
	for _, fld := range s.Fields {
		off := prefix + "_" + screamCase(fld.Name)
		name := rustIdent(snakeCase2(fld.Name))
		switch fld.Type.Kind {
		case KindBool:
			fmt.Fprintf(w, "    r[%s] = input.%s as u8;\n", off, name)
		case KindU8:
			fmt.Fprintf(w, "    r[%s] = input.%s;\n", off, name)
		case KindI8:
			fmt.Fprintf(w, "    r[%s] = input.%s as u8;\n", off, name)
		case KindBytesFixed:
			fmt.Fprintf(w, "    r[%s..%s + %d].copy_from_slice(input.%s);\n",
				off, off, fld.Type.FixedSize, name)
		default:
			n := fld.Type.SlotSize()
			fmt.Fprintf(w, "    r[%s..%s + %d].copy_from_slice(&input.%s.to_le_bytes());\n",
				off, off, n, name)
		}
	}
	w.WriteString("    r\n")
	w.WriteString("}\n\n")
}

// rustPackName is the free function that writes one inline struct's record:
// struct Out -> pack_out.
func rustPackName(s *Struct) string { return "pack_" + snakeCase2(s.Name) }

// emitRustLeaf writes the objects a field's pointers will name, before any
// pointer run exists. Every one of them is written first, in field order,
// which is where the reference wire puts them.
func emitRustLeaf(w *bytes.Buffer, f *File, fld *Field) {
	name := rustIdent(snakeCase2(fld.Name))
	switch fld.Type.Kind {
	case KindStruct:
		// The caller passes a message it built already. Embed copies it and
		// answers where its ROOT lands — a pointer to the head of the copy
		// would name the copy's header, not its first field.
		fmt.Fprintf(w, "    let at_%s = b.embed(input.%s);\n", name, name)
	case KindList:
		elem := f.PtrElem(fld.Type)
		if elem == nil {
			return
		}
		fmt.Fprintf(w, "    let mut offs_%s: Vec<usize> = Vec::with_capacity(input.%s.len());\n", name, name)
		fmt.Fprintf(w, "    for elem in input.%s {\n", name)
		fmt.Fprintf(w, "        offs_%s.push(%s(b, elem));\n", name, rustPutName(elem))
		w.WriteString("    }\n")
	}
}

// emitRustList lays down one list's run of elements: records end to end for
// an inline element, a length before each entry for one with a tail, and a
// signed offset per element for a list of pointers.
func emitRustList(w *bytes.Buffer, f *File, fld *Field) {
	if fld.Type.Kind != KindList {
		return
	}
	name := rustIdent(snakeCase2(fld.Name))
	fmt.Fprintf(w, "    let mut list_%s = b.start_list();\n", name)
	switch {
	case f.PtrElem(fld.Type) != nil:
		fmt.Fprintf(w, "    for at in &offs_%s {\n", name)
		fmt.Fprintf(w, "        list_%s.add_object_ptr(b, *at);\n", name)
	case fld.Type.ListElem.Kind == KindBytesFixed:
		fmt.Fprintf(w, "    for elem in input.%s {\n", name)
		fmt.Fprintf(w, "        list_%s.add_bytes(b, elem);\n", name)
	case fld.Type.ListElem.Kind == KindU8 || fld.Type.ListElem.Kind == KindU32 ||
		fld.Type.ListElem.Kind == KindU64:
		fmt.Fprintf(w, "    for elem in input.%s {\n", name)
		fmt.Fprintf(w, "        list_%s.add_%s(b, *elem);\n", name, rustScalarCall(fld.Type.ListElem.Kind))
	case f.InlineElem(fld.Type) != nil:
		// Inline elements lie end to end, so the count the pointer carries
		// is the caller's own element count, not a byte total.
		fmt.Fprintf(w, "    for elem in input.%s {\n", name)
		fmt.Fprintf(w, "        list_%s.add_bytes(b, elem);\n", name)
	default:
		fmt.Fprintf(w, "    for elem in input.%s {\n", name)
		fmt.Fprintf(w, "        list_%s.add_object_bytes(b, elem);\n", name)
	}
	w.WriteString("    }\n")
	fmt.Fprintf(w, "    let at_%s = list_%s.finish_offset();\n", name, name)
}

// emitRustFieldWriter sets one field of the fixed section. A pointer field
// names what emitRustTail already placed.
func emitRustFieldWriter(w *bytes.Buffer, prefix string, f *Field) {
	off := prefix + "_" + screamCase(f.Name)
	name := rustIdent(snakeCase2(f.Name))
	switch f.Type.Kind {
	case KindBool:
		fmt.Fprintf(w, "    ob.set_bool(b, %s, input.%s);\n", off, name)
	case KindU8, KindU16, KindU32, KindU64, KindI8, KindI16, KindI32, KindI64, KindF32, KindF64:
		fmt.Fprintf(w, "    ob.set_%s(b, %s, input.%s);\n", rustScalarCall(f.Type.Kind), off, name)
	case KindText:
		fmt.Fprintf(w, "    ob.set_text(b, %s, input.%s);\n", off, name)
	case KindBytes:
		fmt.Fprintf(w, "    ob.set_bytes(b, %s, input.%s);\n", off, name)
	case KindBytesFixed:
		fmt.Fprintf(w, "    ob.set_bytes_fixed(b, %s, input.%s);\n", off, name)
	case KindList:
		fmt.Fprintf(w, "    ob.set_list(b, %s, at_%s, input.%s.len());\n", off, name, name)
	case KindStruct:
		fmt.Fprintf(w, "    ob.set_object(b, %s, at_%s);\n", off, name)
	}
}

// rustBuildName is the free function that writes one struct's message:
// struct BaseTx -> new_base_tx, the same word the Go backend uses.
func rustBuildName(s *Struct) string { return "new_" + snakeCase2(s.Name) }

// structBorrows reports whether any field carries a borrowed value, which
// decides whether the Input type needs a lifetime at all — an unused one
// does not compile.
func structBorrows(s *Struct) bool {
	for _, f := range s.Fields {
		switch f.Type.Kind {
		case KindText, KindBytes, KindBytesFixed, KindList, KindStruct:
			return true
		}
	}
	return false
}

func rustAnonLife(borrows bool) string {
	if borrows {
		return "<'_>"
	}
	return ""
}

func rustScalar(k TypeKind) string {
	switch k {
	case KindU8:
		return "u8"
	case KindU16:
		return "u16"
	case KindU32:
		return "u32"
	case KindU64:
		return "u64"
	case KindI8:
		return "i8"
	case KindI16:
		return "i16"
	case KindI32:
		return "i32"
	case KindI64:
		return "i64"
	case KindF32:
		return "f32"
	case KindF64:
		return "f64"
	}
	return ""
}

// rustScalarCall is the runtime accessor for a scalar kind. It is the type's
// own name — u32() reads a u32 — so one table serves both directions.
func rustScalarCall(k TypeKind) string { return rustScalar(k) }

func rustInputType(f *File, t Type) string {
	switch t.Kind {
	case KindBool:
		return "bool"
	case KindText:
		return "&'a str"
	case KindBytes:
		return "&'a [u8]"
	case KindBytesFixed:
		return fmt.Sprintf("&'a [u8; %d]", t.FixedSize)
	case KindList:
		if elem := f.PtrElem(t); elem != nil {
			// The elements are written into this same buffer, so they
			// arrive as values rather than as bytes.
			return "&'a [" + elem.Name + "Input" + rustLife(elem) + "]"
		}
		switch t.ListElem.Kind {
		case KindBytesFixed:
			return fmt.Sprintf("&'a [[u8; %d]]", t.ListElem.FixedSize)
		case KindU8, KindU32, KindU64:
			return "&'a [" + rustScalar(t.ListElem.Kind) + "]"
		}
		// Each element arrives already written: a record for an inline
		// element, its own message for one with a tail.
		return "&'a [&'a [u8]]"
	case KindStruct:
		// A nested struct arrives already written, as its own message.
		return "&'a [u8]"
	}
	return rustScalar(t.Kind)
}

func rustZero(t Type) string {
	switch t.Kind {
	case KindBool:
		return "false"
	case KindText:
		return `""`
	case KindBytes, KindList, KindStruct:
		return "&[]"
	case KindBytesFixed:
		return fmt.Sprintf("&[0u8; %d]", t.FixedSize)
	case KindF32, KindF64:
		return "0.0"
	}
	return "0"
}

// --- interfaces ------------------------------------------------------------

func emitRustOrdinals(w *bytes.Buffer, iface *Interface) {
	fmt.Fprintf(w, "// %s — method ordinals, the 1-based wire ids. Appending a method\n", iface.Name)
	w.WriteString("// never moves an earlier one.\n")
	for _, m := range iface.Methods {
		fmt.Fprintf(w, "pub const %s: u32 = %d;\n", rustOrdinalName(iface, m), m.Ordinal)
	}
	w.WriteString("\n")
}

func rustOrdinalName(iface *Interface, m *Method) string {
	return screamCase(iface.Name) + "_" + screamCase(m.Name) + "_ORDINAL"
}

func emitRustClient(w *bytes.Buffer, iface *Interface) {
	fmt.Fprintf(w, "/// Ships one %s call and answers with the response envelope.\n", iface.Name)
	fmt.Fprintf(w, "pub trait %sChannel {\n", iface.Name)
	w.WriteString("    fn call(&mut self, envelope: &[u8]) -> Result<Vec<u8>, rpc::CallError>;\n")
	w.WriteString("}\n\n")

	fmt.Fprintf(w, "/// A typed client for the %s service. Each call takes a fresh promise;\n", iface.Name)
	w.WriteString("/// the `_on` form of a method targets an earlier one, so the server\n")
	w.WriteString("/// chains them without a round trip in between.\n")
	w.WriteString("#[derive(Debug)]\n")
	fmt.Fprintf(w, "pub struct %sClient<C: %sChannel> {\n", iface.Name, iface.Name)
	w.WriteString("    channel: C,\n")
	w.WriteString("    cap: Vec<u8>,\n")
	w.WriteString("    session: rpc::Session,\n")
	w.WriteString("}\n\n")

	fmt.Fprintf(w, "impl<C: %sChannel> %sClient<C> {\n", iface.Name, iface.Name)
	w.WriteString("    /// A client that issues calls over `channel`, attaching `cap`\n")
	w.WriteString("    /// (which may be empty) to every request.\n")
	w.WriteString("    pub fn new(channel: C, cap: &[u8]) -> Self {\n")
	fmt.Fprintf(w, "        %sClient {\n", iface.Name)
	w.WriteString("            channel,\n")
	w.WriteString("            cap: cap.to_vec(),\n")
	w.WriteString("            session: rpc::Session::new(),\n")
	w.WriteString("        }\n")
	w.WriteString("    }\n")
	for _, m := range iface.Methods {
		emitRustClientMethod(w, iface, m)
	}
	w.WriteString("}\n\n")
}

func emitRustClientMethod(w *bytes.Buffer, iface *Interface, m *Method) {
	name := rustIdent(snakeCase2(m.Name))
	ret := rustCallResult(m)
	arg := ""
	payload := "&[]"
	if m.Request != nil {
		arg = fmt.Sprintf(", %s: &[u8]", rustIdent(snakeCase2(m.Request.Name)))
		payload = rustIdent(snakeCase2(m.Request.Name))
	}

	fmt.Fprintf(w, "\n    /// `%s`, as an originating call.\n", m.Name)
	fmt.Fprintf(w, "    pub fn %s(&mut self%s) -> %s {\n", name, arg, ret)
	fmt.Fprintf(w, "        self.invoke_%s(rpc::NO_TARGET, %s)\n", name, payload)
	w.WriteString("    }\n\n")

	fmt.Fprintf(w, "    /// `%s`, pipelined on `on`: the server substitutes on's answer for\n", m.Name)
	w.WriteString("    /// this call's payload, so it ships before on comes back.\n")
	fmt.Fprintf(w, "    pub fn %s_on(&mut self, on: rpc::Promise) -> %s {\n", name, ret)
	fmt.Fprintf(w, "        self.invoke_%s(on.id, &[])\n", name)
	w.WriteString("    }\n\n")

	fmt.Fprintf(w, "    fn invoke_%s(&mut self, target: u32, payload: &[u8]) -> %s {\n", name, ret)
	w.WriteString("        let p = self.session.next();\n")
	w.WriteString("        let envelope = rpc::build_request(&rpc::Call {\n")
	fmt.Fprintf(w, "            method: %s,\n", rustOrdinalName(iface, m))
	w.WriteString("            promise_id: p.id,\n")
	w.WriteString("            target,\n")
	w.WriteString("            cap: &self.cap,\n")
	w.WriteString("            payload,\n")
	w.WriteString("        });\n")
	w.WriteString("        let answer = match self.channel.call(&envelope) {\n")
	w.WriteString("            Ok(a) => a,\n")
	w.WriteString("            Err(e) => return (p, Err(e)),\n")
	w.WriteString("        };\n")
	w.WriteString("        let resp = match rpc::parse_response(&answer) {\n")
	w.WriteString("            Ok(r) => r,\n")
	w.WriteString("            Err(e) => return (p, Err(e.into())),\n")
	w.WriteString("        };\n")
	w.WriteString("        if resp.status != rpc::STATUS_OK {\n")
	w.WriteString("            return (p, Err(rpc::CallError::Status(resp.status)));\n")
	w.WriteString("        }\n")
	if m.Response != nil {
		w.WriteString("        (p, Ok(resp.body.to_vec()))\n")
	} else {
		w.WriteString("        (p, Ok(()))\n")
	}
	w.WriteString("    }\n")
}

// rustCallResult is a client method's answer: the call's own promise, so a
// chain longer than two links can name it, alongside what the method returns.
func rustCallResult(m *Method) string {
	if m.Response != nil {
		return "(rpc::Promise, Result<Vec<u8>, rpc::CallError>)"
	}
	return "(rpc::Promise, Result<(), rpc::CallError>)"
}

func emitRustServer(w *bytes.Buffer, iface *Interface) {
	fmt.Fprintf(w, "/// The server contract for %s. Implement it, then route calls to it\n", iface.Name)
	fmt.Fprintf(w, "/// with [`%s`].\n", rustDispatchName(iface))
	fmt.Fprintf(w, "pub trait %sHandler {\n", iface.Name)
	for _, m := range iface.Methods {
		arg := ""
		if m.Request != nil {
			arg = fmt.Sprintf(", %s: &[u8]", rustIdent(snakeCase2(m.Request.Name)))
		}
		ret := "Result<(), rpc::Fault>"
		if m.Response != nil {
			ret = "Result<Vec<u8>, rpc::Fault>"
		}
		fmt.Fprintf(w, "    fn %s(&mut self%s) -> %s;\n", rustIdent(snakeCase2(m.Name)), arg, ret)
	}
	w.WriteString("}\n\n")

	fmt.Fprintf(w, "/// Read one call envelope, route it by ordinal to `h`, and write the\n")
	w.WriteString("/// response envelope. An unknown ordinal answers not-found; a handler\n")
	w.WriteString("/// fault answers internal.\n")
	fmt.Fprintf(w, "pub fn %s<H: %sHandler>(h: &mut H, envelope: &[u8]) -> Result<Vec<u8>, zap::Error> {\n",
		rustDispatchName(iface), iface.Name)
	w.WriteString("    let call = rpc::parse_request(envelope)?;\n")
	w.WriteString("    let answer = match call.method {\n")
	for _, m := range iface.Methods {
		arg := ""
		if m.Request != nil {
			arg = "call.payload"
		}
		fmt.Fprintf(w, "        %s => match h.%s(%s) {\n", rustOrdinalName(iface, m), rustIdent(snakeCase2(m.Name)), arg)
		if m.Response != nil {
			w.WriteString("            Ok(body) => rpc::build_response(rpc::STATUS_OK, call.promise_id, &body),\n")
		} else {
			w.WriteString("            Ok(()) => rpc::build_response(rpc::STATUS_OK, call.promise_id, &[]),\n")
		}
		w.WriteString("            Err(_) => rpc::build_response(rpc::STATUS_INTERNAL, call.promise_id, &[]),\n")
		w.WriteString("        },\n")
	}
	w.WriteString("        _ => rpc::build_response(rpc::STATUS_NOT_FOUND, call.promise_id, &[]),\n")
	w.WriteString("    };\n")
	w.WriteString("    Ok(answer)\n")
	w.WriteString("}\n\n")
}

func rustDispatchName(iface *Interface) string { return "dispatch_" + snakeCase2(iface.Name) }

// --- names -----------------------------------------------------------------

// snakeCase2 lowercases a schema identifier into Rust's word shape. It reads
// a run of capitals as one word, so NetworkID is network_id and IDList is
// id_list — the plain "underscore before every capital" rule the Go backend
// uses for filenames would say network_i_d.
func snakeCase2(s string) string {
	r := []rune(s)
	var b strings.Builder
	for i, c := range r {
		if isUpper(c) {
			prevLower := i > 0 && (isLower(r[i-1]) || isDigit(r[i-1]))
			nextLower := i+1 < len(r) && isLower(r[i+1])
			prevUpper := i > 0 && isUpper(r[i-1])
			if prevLower || (prevUpper && nextLower) {
				b.WriteByte('_')
			}
			b.WriteRune(c + ('a' - 'A'))
			continue
		}
		b.WriteRune(c)
	}
	return b.String()
}

// screamCase is snakeCase2 in capitals — the shape Rust wants for a const.
func screamCase(s string) string { return strings.ToUpper(snakeCase2(s)) }

func isUpper(r rune) bool { return r >= 'A' && r <= 'Z' }
func isLower(r rune) bool { return r >= 'a' && r <= 'z' }
func isDigit(r rune) bool { return r >= '0' && r <= '9' }

// rustKeywords are the words a generated identifier may not be. A schema
// field named `type` or `match` is legal; the emitted Rust says r#type.
var rustKeywords = map[string]bool{
	"as": true, "break": true, "const": true, "continue": true, "crate": true,
	"dyn": true, "else": true, "enum": true, "extern": true, "false": true,
	"fn": true, "for": true, "if": true, "impl": true, "in": true, "let": true,
	"loop": true, "match": true, "mod": true, "move": true, "mut": true,
	"pub": true, "ref": true, "return": true, "static": true, "struct": true,
	"trait": true, "true": true, "type": true, "unsafe": true, "use": true,
	"where": true, "while": true, "async": true, "await": true, "abstract": true,
	"become": true, "box": true, "do": true, "final": true, "macro": true,
	"override": true, "priv": true, "typeof": true, "unsized": true,
	"virtual": true, "yield": true, "try": true, "gen": true,
}

// rustReserved are the words that cannot even take the r# escape.
var rustReserved = map[string]string{
	"self":  "self_",
	"Self":  "self_ty",
	"super": "super_",
}

func rustIdent(s string) string {
	if alt, ok := rustReserved[s]; ok {
		return alt
	}
	if rustKeywords[s] {
		return "r#" + s
	}
	return s
}
