// Copyright (C) 2025, Lux Industries Inc. All rights reserved.
// See the file LICENSE for licensing terms.

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

// Emit emits one .go file per struct in f. Returns a map of basename →
// gofmt-clean bytes, ready to write. The basename is the lowercase
// snake-cased struct name plus "_zap.go" (matches the spec convention).
func Emit(f *File) (map[string][]byte, error) {
	out := make(map[string][]byte, len(f.Structs))
	for _, s := range f.Structs {
		buf, err := emitStruct(f, s)
		if err != nil {
			return nil, fmt.Errorf("emit %s: %w", s.Name, err)
		}
		clean, err := format.Source(buf)
		if err != nil {
			return nil, fmt.Errorf("gofmt %s: %w\n--- raw ---\n%s\n--- end ---", s.Name, err, buf)
		}
		out[snakeCase(s.Name)+"_zap.go"] = clean
	}
	return out, nil
}

// EmitSingle emits one combined .go file containing all structs from f.
// Returns the basename (derived from the schema source filename) and the
// gofmt-clean bytes. Used by callers that prefer one file per schema over
// one file per struct.
func EmitSingle(f *File) (string, []byte, error) {
	if len(f.Structs) == 0 {
		return "", nil, fmt.Errorf("no structs to emit")
	}
	source := f.Source
	if source == "" {
		source = f.Package + ".zap"
	}
	// Output filename: strip the .zap extension, snake_case, append _zap.go.
	base := source
	if i := strings.LastIndex(base, "."); i >= 0 {
		base = base[:i]
	}
	outName := base + "_zap.go"

	var w bytes.Buffer
	w.WriteString("// Code generated by zapgen; DO NOT EDIT.\n")
	fmt.Fprintf(&w, "// source: %s\n\n", source)
	fmt.Fprintf(&w, "package %s\n\n", f.Package)
	w.WriteString("import (\n")
	w.WriteString("\tzap \"github.com/zap-proto/go\"\n")
	w.WriteString(")\n\n")

	for _, s := range f.Structs {
		if err := validate(s); err != nil {
			return "", nil, err
		}
		emitOffsets(&w, s)
		emitReader(&w, s)
		emitBuilder(&w, s)
		w.WriteString("\n")
	}
	clean, err := format.Source(w.Bytes())
	if err != nil {
		return "", nil, fmt.Errorf("gofmt: %w\n--- raw ---\n%s\n--- end ---", err, w.Bytes())
	}
	return outName, clean, nil
}

// structSize returns the total fixed-section size for s. The size is
// max(field.Offset + field.SlotSize()) over all fields, rounded up to
// the alignment boundary if needed. We do NOT round here — the spec is
// explicit-offset, author-controlled; the reported size equals
// max(end-of-field).
func structSize(s *Struct) int {
	size := 0
	for _, f := range s.Fields {
		end := f.Offset + f.Type.SlotSize()
		if end > size {
			size = end
		}
	}
	return size
}

func emitStruct(f *File, s *Struct) ([]byte, error) {
	if err := validate(s); err != nil {
		return nil, err
	}
	var w bytes.Buffer
	source := f.Source
	if source == "" {
		// Fallback for callers that build a File directly without going
		// through Parse. Mirrors the historical behavior of naming the
		// source after the package.
		source = f.Package + ".zap"
	}
	w.WriteString("// Code generated by zapgen; DO NOT EDIT.\n")
	fmt.Fprintf(&w, "// source: %s\n\n", source)
	fmt.Fprintf(&w, "package %s\n\n", f.Package)
	w.WriteString("import (\n")
	w.WriteString("\tzap \"github.com/zap-proto/go\"\n")
	w.WriteString(")\n\n")

	emitOffsets(&w, s)
	emitReader(&w, s)
	emitBuilder(&w, s)
	return w.Bytes(), nil
}

// validate checks for offset overlap and bad field types. Fail fast and
// loud — the schema author is responsible for the layout, but a typo
// shouldn't silently emit broken code.
func validate(s *Struct) error {
	size := structSize(s)
	if size == 0 {
		return fmt.Errorf("struct %s: no fields", s.Name)
	}
	owner := make([]string, size)
	for _, f := range s.Fields {
		sz := f.Type.SlotSize()
		if sz == 0 {
			return fmt.Errorf("struct %s field %s: unsupported type %s", s.Name, f.Name, f.Type.Kind)
		}
		if f.Offset < 0 {
			return fmt.Errorf("struct %s field %s: negative offset %d", s.Name, f.Name, f.Offset)
		}
		for i := 0; i < sz; i++ {
			pos := f.Offset + i
			if owner[pos] != "" {
				return fmt.Errorf("struct %s: field %s at offset %d overlaps field %s",
					s.Name, f.Name, pos, owner[pos])
			}
			owner[pos] = f.Name
		}
	}
	return nil
}

func emitOffsets(w *bytes.Buffer, s *Struct) {
	w.WriteString("const (\n")
	lower := lowerFirst(s.Name)
	for _, f := range s.Fields {
		fmt.Fprintf(w, "\t%s%sOff = %d\n", lower, f.Name, f.Offset)
	}
	fmt.Fprintf(w, "\t%sSize = %d\n", lower, structSize(s))
	w.WriteString(")\n\n")
}

func emitReader(w *bytes.Buffer, s *Struct) {
	fmt.Fprintf(w, "// %s is a zero-copy view into a ZAP-encoded %s message.\n", s.Name, s.Name)
	fmt.Fprintf(w, "type %s struct{ o zap.Object }\n\n", s.Name)

	fmt.Fprintf(w, "// Wrap%s parses b and returns a typed view. Returns an error if the\n", s.Name)
	w.WriteString("// wire-level checks (magic, version, size) fail.\n")
	fmt.Fprintf(w, "func Wrap%s(b []byte) (%s, error) {\n", s.Name, s.Name)
	w.WriteString("\tm, err := zap.Parse(b)\n")
	w.WriteString("\tif err != nil {\n")
	fmt.Fprintf(w, "\t\treturn %s{}, err\n", s.Name)
	w.WriteString("\t}\n")
	fmt.Fprintf(w, "\treturn %s{o: m.Root()}, nil\n", s.Name)
	w.WriteString("}\n\n")

	lower := lowerFirst(s.Name)
	for _, f := range s.Fields {
		emitFieldReader(w, s.Name, lower, f)
	}
}

func emitFieldReader(w *bytes.Buffer, structName, lower string, f *Field) {
	offsetConst := fmt.Sprintf("%s%sOff", lower, f.Name)
	switch f.Type.Kind {
	case KindBool:
		fmt.Fprintf(w, "func (t %s) %s() bool { return t.o.Bool(%s) }\n", structName, f.Name, offsetConst)
	case KindU8:
		fmt.Fprintf(w, "func (t %s) %s() uint8 { return t.o.Uint8(%s) }\n", structName, f.Name, offsetConst)
	case KindU16:
		fmt.Fprintf(w, "func (t %s) %s() uint16 { return t.o.Uint16(%s) }\n", structName, f.Name, offsetConst)
	case KindU32:
		fmt.Fprintf(w, "func (t %s) %s() uint32 { return t.o.Uint32(%s) }\n", structName, f.Name, offsetConst)
	case KindU64:
		fmt.Fprintf(w, "func (t %s) %s() uint64 { return t.o.Uint64(%s) }\n", structName, f.Name, offsetConst)
	case KindI8:
		fmt.Fprintf(w, "func (t %s) %s() int8 { return t.o.Int8(%s) }\n", structName, f.Name, offsetConst)
	case KindI16:
		fmt.Fprintf(w, "func (t %s) %s() int16 { return t.o.Int16(%s) }\n", structName, f.Name, offsetConst)
	case KindI32:
		fmt.Fprintf(w, "func (t %s) %s() int32 { return t.o.Int32(%s) }\n", structName, f.Name, offsetConst)
	case KindI64:
		fmt.Fprintf(w, "func (t %s) %s() int64 { return t.o.Int64(%s) }\n", structName, f.Name, offsetConst)
	case KindF32:
		fmt.Fprintf(w, "func (t %s) %s() float32 { return t.o.Float32(%s) }\n", structName, f.Name, offsetConst)
	case KindF64:
		fmt.Fprintf(w, "func (t %s) %s() float64 { return t.o.Float64(%s) }\n", structName, f.Name, offsetConst)
	case KindText:
		fmt.Fprintf(w, "func (t %s) %s() string { return t.o.Text(%s) }\n", structName, f.Name, offsetConst)
	case KindBytes:
		fmt.Fprintf(w, "func (t %s) %s() []byte { return t.o.Bytes(%s) }\n", structName, f.Name, offsetConst)
	case KindBytesFixed:
		fmt.Fprintf(w, "func (t %s) %s() [%d]byte {\n", structName, f.Name, f.Type.FixedSize)
		fmt.Fprintf(w, "\tvar out [%d]byte\n", f.Type.FixedSize)
		fmt.Fprintf(w, "\tcopy(out[:], t.o.BytesFixed(%s, %d))\n", offsetConst, f.Type.FixedSize)
		w.WriteString("\treturn out\n")
		w.WriteString("}\n")
	case KindList:
		fmt.Fprintf(w, "func (t %s) %s() zap.List { return t.o.List(%s) }\n", structName, f.Name, offsetConst)
	case KindStruct:
		fmt.Fprintf(w, "func (t %s) %s() %s { return %s{o: t.o.Object(%s)} }\n",
			structName, f.Name, f.Type.StructName, f.Type.StructName, offsetConst)
	}
}

func emitBuilder(w *bytes.Buffer, s *Struct) {
	// Input struct.
	fmt.Fprintf(w, "\n// %sInput collects the field values for New%s.\n", s.Name, s.Name)
	fmt.Fprintf(w, "type %sInput struct {\n", s.Name)
	for _, f := range s.Fields {
		fmt.Fprintf(w, "\t%s %s\n", f.Name, goInputType(f.Type))
	}
	w.WriteString("}\n\n")

	// Constructor.
	fmt.Fprintf(w, "// New%s builds a ZAP-encoded %s message from in and returns the bytes.\n", s.Name, s.Name)
	fmt.Fprintf(w, "func New%s(in %sInput) []byte {\n", s.Name, s.Name)
	w.WriteString("\tb := zap.NewBuilder(256)\n")
	lower := lowerFirst(s.Name)
	fmt.Fprintf(w, "\tob := b.StartObject(%sSize)\n", lower)

	// Two-pass: fixed-section first, then variable-tail (lists last so we
	// don't interleave list-element writes with deferred-bytes writes).
	for _, f := range s.Fields {
		emitFieldWriter(w, lower, f)
	}

	w.WriteString("\tob.FinishAsRoot()\n")
	w.WriteString("\treturn b.Finish()\n")
	w.WriteString("}\n")
}

// goInputType returns the Go type used in the Input struct.
func goInputType(t Type) string {
	switch t.Kind {
	case KindBool:
		return "bool"
	case KindU8:
		return "uint8"
	case KindU16:
		return "uint16"
	case KindU32:
		return "uint32"
	case KindU64:
		return "uint64"
	case KindI8:
		return "int8"
	case KindI16:
		return "int16"
	case KindI32:
		return "int32"
	case KindI64:
		return "int64"
	case KindF32:
		return "float32"
	case KindF64:
		return "float64"
	case KindText:
		return "string"
	case KindBytes:
		return "[]byte"
	case KindBytesFixed:
		return fmt.Sprintf("[%d]byte", t.FixedSize)
	case KindList:
		// Variable-element list: each entry is a pre-built sub-buffer.
		return "[][]byte"
	case KindStruct:
		// Nested struct: caller passes a pre-built sub-buffer.
		return "[]byte"
	}
	return "any"
}

func emitFieldWriter(w *bytes.Buffer, lower string, f *Field) {
	offsetConst := fmt.Sprintf("%s%sOff", lower, f.Name)
	switch f.Type.Kind {
	case KindBool:
		fmt.Fprintf(w, "\tob.SetBool(%s, in.%s)\n", offsetConst, f.Name)
	case KindU8:
		fmt.Fprintf(w, "\tob.SetUint8(%s, in.%s)\n", offsetConst, f.Name)
	case KindU16:
		fmt.Fprintf(w, "\tob.SetUint16(%s, in.%s)\n", offsetConst, f.Name)
	case KindU32:
		fmt.Fprintf(w, "\tob.SetUint32(%s, in.%s)\n", offsetConst, f.Name)
	case KindU64:
		fmt.Fprintf(w, "\tob.SetUint64(%s, in.%s)\n", offsetConst, f.Name)
	case KindI8:
		fmt.Fprintf(w, "\tob.SetUint8(%s, uint8(in.%s))\n", offsetConst, f.Name)
	case KindI16:
		fmt.Fprintf(w, "\tob.SetUint16(%s, uint16(in.%s))\n", offsetConst, f.Name)
	case KindI32:
		fmt.Fprintf(w, "\tob.SetUint32(%s, uint32(in.%s))\n", offsetConst, f.Name)
	case KindI64:
		fmt.Fprintf(w, "\tob.SetUint64(%s, uint64(in.%s))\n", offsetConst, f.Name)
	case KindF32:
		fmt.Fprintf(w, "\tob.SetFloat32(%s, in.%s)\n", offsetConst, f.Name)
	case KindF64:
		fmt.Fprintf(w, "\tob.SetFloat64(%s, in.%s)\n", offsetConst, f.Name)
	case KindText:
		fmt.Fprintf(w, "\tob.SetText(%s, in.%s)\n", offsetConst, f.Name)
	case KindBytes:
		fmt.Fprintf(w, "\tob.SetBytes(%s, in.%s)\n", offsetConst, f.Name)
	case KindBytesFixed:
		fmt.Fprintf(w, "\tob.SetBytesFixed(%s, in.%s[:])\n", offsetConst, f.Name)
	case KindList:
		listVar := lowerFirst(f.Name) + "LB"
		fmt.Fprintf(w, "\t%s := b.StartList(0)\n", listVar)
		fmt.Fprintf(w, "\tfor _, elem := range in.%s {\n", f.Name)
		fmt.Fprintf(w, "\t\t%s.AddObjectBytes(elem)\n", listVar)
		w.WriteString("\t}\n")
		fmt.Fprintf(w, "\tob.SetList(%s, %s.FinishOffset(), len(in.%s))\n",
			offsetConst, listVar, f.Name)
	case KindStruct:
		// Nested struct: caller passes a built sub-buffer; embed it inline.
		// We allocate via b.StartObject(len(in.X)) and copy the bytes.
		fmt.Fprintf(w, "\tif len(in.%s) > 0 {\n", f.Name)
		fmt.Fprintf(w, "\t\tnested := b.StartObject(len(in.%s))\n", f.Name)
		fmt.Fprintf(w, "\t\tnested.SetBytesFixed(0, in.%s)\n", f.Name)
		fmt.Fprintf(w, "\t\tob.SetObject(%s, nested.Finish())\n", offsetConst)
		w.WriteString("\t}\n")
	}
}

// snakeCase converts CamelCase / PascalCase to snake_case. ASCII only —
// our schema identifiers are Go identifiers.
func snakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		if r >= 'A' && r <= 'Z' {
			b.WriteRune(r + ('a' - 'A'))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// lowerFirst returns s with the first byte lowercased (ASCII). Used to
// build "baseTxFooOff" constants from struct name "BaseTx" + field
// "Foo".
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	if r[0] >= 'A' && r[0] <= 'Z' {
		r[0] = r[0] + ('a' - 'A')
	}
	return string(r)
}
