// Code generated by zapgen; DO NOT EDIT.
// source: pchain.zap

package pchain

import (
	zap "github.com/zap-proto/go"
)

const (
	spendKindOff         = 0
	spendNetworkIDOff    = 1
	spendBlockchainIDOff = 5
	spendOutsOff         = 37
	spendOwnerAddrsOff   = 45
	spendInsOff          = 53
	spendSigIndicesOff   = 61
	spendMemoOff         = 69
	spendSize            = 77
)

// Spend is a zero-copy view into a ZAP-encoded Spend message.
type Spend struct{ o zap.Object }

// WrapSpend parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapSpend(b []byte) (Spend, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Spend{}, err
	}
	return Spend{o: m.Root()}, nil
}

func (t Spend) Kind() uint8       { return t.o.Uint8(spendKindOff) }
func (t Spend) NetworkID() uint32 { return t.o.Uint32(spendNetworkIDOff) }
func (t Spend) BlockchainID() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(spendBlockchainIDOff, 32))
	return out
}
func (t Spend) Outs() OutList { return OutList{l: t.o.ListStride(spendOutsOff, outSize)} }
func (t Spend) OwnerAddrs() AddrList {
	return AddrList{l: t.o.ListStride(spendOwnerAddrsOff, addrSize)}
}
func (t Spend) Ins() InList         { return InList{l: t.o.ListStride(spendInsOff, inSize)} }
func (t Spend) SigIndices() SigList { return SigList{l: t.o.ListStride(spendSigIndicesOff, sigSize)} }
func (t Spend) Memo() []byte        { return t.o.Bytes(spendMemoOff) }

// SpendInput collects the field values for NewSpend.
type SpendInput struct {
	Kind         uint8
	NetworkID    uint32
	BlockchainID [32]byte
	Outs         [][]byte
	OwnerAddrs   [][]byte
	Ins          [][]byte
	SigIndices   [][]byte
	Memo         []byte
}

// NewSpend builds a ZAP-encoded Spend message from in and returns the bytes.
func NewSpend(in SpendInput) []byte {
	b := zap.NewBuilderV2(256)
	outsAt := 0
	if len(in.Outs) > 0 {
		lb := b.StartList(outSize)
		for _, elem := range in.Outs {
			var rec [outSize]byte
			copy(rec[:], elem)
			lb.AddBytes(rec[:])
		}
		outsAt = lb.FinishOffset()
	}
	ownerAddrsAt := 0
	if len(in.OwnerAddrs) > 0 {
		lb := b.StartList(addrSize)
		for _, elem := range in.OwnerAddrs {
			var rec [addrSize]byte
			copy(rec[:], elem)
			lb.AddBytes(rec[:])
		}
		ownerAddrsAt = lb.FinishOffset()
	}
	insAt := 0
	if len(in.Ins) > 0 {
		lb := b.StartList(inSize)
		for _, elem := range in.Ins {
			var rec [inSize]byte
			copy(rec[:], elem)
			lb.AddBytes(rec[:])
		}
		insAt = lb.FinishOffset()
	}
	sigIndicesAt := 0
	if len(in.SigIndices) > 0 {
		lb := b.StartList(sigSize)
		for _, elem := range in.SigIndices {
			var rec [sigSize]byte
			copy(rec[:], elem)
			lb.AddBytes(rec[:])
		}
		sigIndicesAt = lb.FinishOffset()
	}
	ob := b.StartObject(spendSize)
	ob.SetUint8(spendKindOff, in.Kind)
	ob.SetUint32(spendNetworkIDOff, in.NetworkID)
	ob.SetBytesFixed(spendBlockchainIDOff, in.BlockchainID[:])
	ob.SetList(spendOutsOff, outsAt, len(in.Outs))
	ob.SetList(spendOwnerAddrsOff, ownerAddrsAt, len(in.OwnerAddrs))
	ob.SetList(spendInsOff, insAt, len(in.Ins))
	ob.SetList(spendSigIndicesOff, sigIndicesAt, len(in.SigIndices))
	ob.SetBytes(spendMemoOff, in.Memo)
	ob.FinishAsRoot()
	return b.Finish()
}

const (
	outAssetOff     = 0
	outStakeLockOff = 32
	outAmountOff    = 40
	outThresholdOff = 48
	outOwnerLockOff = 52
	outAddrStartOff = 60
	outAddrCountOff = 64
	outPadOff       = 68
	outSize         = 72
)

// Out is a zero-copy view into a ZAP-encoded Out message.
type Out struct{ o zap.Object }

// WrapOut parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapOut(b []byte) (Out, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Out{}, err
	}
	return Out{o: m.Root()}, nil
}

func (t Out) Asset() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(outAssetOff, 32))
	return out
}
func (t Out) StakeLock() uint64 { return t.o.Uint64(outStakeLockOff) }
func (t Out) Amount() uint64    { return t.o.Uint64(outAmountOff) }
func (t Out) Threshold() uint32 { return t.o.Uint32(outThresholdOff) }
func (t Out) OwnerLock() uint64 { return t.o.Uint64(outOwnerLockOff) }
func (t Out) AddrStart() uint32 { return t.o.Uint32(outAddrStartOff) }
func (t Out) AddrCount() uint32 { return t.o.Uint32(outAddrCountOff) }
func (t Out) Pad() [4]byte {
	var out [4]byte
	copy(out[:], t.o.BytesFixed(outPadOff, 4))
	return out
}

// Record is the outSize bytes this Out occupies where it lies.
func (t Out) Record() []byte { return t.o.BytesFixed(0, outSize) }

// OutList is a run of Out records, outSize bytes each.
type OutList struct{ l zap.List }

// Len is how many elements the list holds.
func (x OutList) Len() int { return x.l.Len() }

// At is element i, or the absent Out past the end.
func (x OutList) At(i int) Out { return Out{o: x.l.Object(i, outSize)} }

// OutInput collects the field values for NewOut.
type OutInput struct {
	Asset     [32]byte
	StakeLock uint64
	Amount    uint64
	Threshold uint32
	OwnerLock uint64
	AddrStart uint32
	AddrCount uint32
	Pad       [4]byte
}

// NewOut builds a ZAP-encoded Out message from in and returns the bytes.
func NewOut(in OutInput) []byte {
	b := zap.NewBuilderV2(256)
	ob := b.StartObject(outSize)
	ob.SetBytesFixed(outAssetOff, in.Asset[:])
	ob.SetUint64(outStakeLockOff, in.StakeLock)
	ob.SetUint64(outAmountOff, in.Amount)
	ob.SetUint32(outThresholdOff, in.Threshold)
	ob.SetUint64(outOwnerLockOff, in.OwnerLock)
	ob.SetUint32(outAddrStartOff, in.AddrStart)
	ob.SetUint32(outAddrCountOff, in.AddrCount)
	ob.SetBytesFixed(outPadOff, in.Pad[:])
	ob.FinishAsRoot()
	return b.Finish()
}

const (
	inTxIDOff        = 0
	inOutputIndexOff = 32
	inAssetOff       = 36
	inStakeLockOff   = 68
	inAmountOff      = 76
	inSigStartOff    = 84
	inSigCountOff    = 88
	inPadOff         = 92
	inSize           = 96
)

// In is a zero-copy view into a ZAP-encoded In message.
type In struct{ o zap.Object }

// WrapIn parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapIn(b []byte) (In, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return In{}, err
	}
	return In{o: m.Root()}, nil
}

func (t In) TxID() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(inTxIDOff, 32))
	return out
}
func (t In) OutputIndex() uint32 { return t.o.Uint32(inOutputIndexOff) }
func (t In) Asset() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(inAssetOff, 32))
	return out
}
func (t In) StakeLock() uint64 { return t.o.Uint64(inStakeLockOff) }
func (t In) Amount() uint64    { return t.o.Uint64(inAmountOff) }
func (t In) SigStart() uint32  { return t.o.Uint32(inSigStartOff) }
func (t In) SigCount() uint32  { return t.o.Uint32(inSigCountOff) }
func (t In) Pad() [4]byte {
	var out [4]byte
	copy(out[:], t.o.BytesFixed(inPadOff, 4))
	return out
}

// Record is the inSize bytes this In occupies where it lies.
func (t In) Record() []byte { return t.o.BytesFixed(0, inSize) }

// InList is a run of In records, inSize bytes each.
type InList struct{ l zap.List }

// Len is how many elements the list holds.
func (x InList) Len() int { return x.l.Len() }

// At is element i, or the absent In past the end.
func (x InList) At(i int) In { return In{o: x.l.Object(i, inSize)} }

// InInput collects the field values for NewIn.
type InInput struct {
	TxID        [32]byte
	OutputIndex uint32
	Asset       [32]byte
	StakeLock   uint64
	Amount      uint64
	SigStart    uint32
	SigCount    uint32
	Pad         [4]byte
}

// NewIn builds a ZAP-encoded In message from in and returns the bytes.
func NewIn(in InInput) []byte {
	b := zap.NewBuilderV2(256)
	ob := b.StartObject(inSize)
	ob.SetBytesFixed(inTxIDOff, in.TxID[:])
	ob.SetUint32(inOutputIndexOff, in.OutputIndex)
	ob.SetBytesFixed(inAssetOff, in.Asset[:])
	ob.SetUint64(inStakeLockOff, in.StakeLock)
	ob.SetUint64(inAmountOff, in.Amount)
	ob.SetUint32(inSigStartOff, in.SigStart)
	ob.SetUint32(inSigCountOff, in.SigCount)
	ob.SetBytesFixed(inPadOff, in.Pad[:])
	ob.FinishAsRoot()
	return b.Finish()
}

const (
	addrBytesOff = 0
	addrSize     = 20
)

// Addr is a zero-copy view into a ZAP-encoded Addr message.
type Addr struct{ o zap.Object }

// WrapAddr parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapAddr(b []byte) (Addr, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Addr{}, err
	}
	return Addr{o: m.Root()}, nil
}

func (t Addr) Bytes() [20]byte {
	var out [20]byte
	copy(out[:], t.o.BytesFixed(addrBytesOff, 20))
	return out
}

// Record is the addrSize bytes this Addr occupies where it lies.
func (t Addr) Record() []byte { return t.o.BytesFixed(0, addrSize) }

// AddrList is a run of Addr records, addrSize bytes each.
type AddrList struct{ l zap.List }

// Len is how many elements the list holds.
func (x AddrList) Len() int { return x.l.Len() }

// At is element i, or the absent Addr past the end.
func (x AddrList) At(i int) Addr { return Addr{o: x.l.Object(i, addrSize)} }

// AddrInput collects the field values for NewAddr.
type AddrInput struct {
	Bytes [20]byte
}

// NewAddr builds a ZAP-encoded Addr message from in and returns the bytes.
func NewAddr(in AddrInput) []byte {
	b := zap.NewBuilderV2(256)
	ob := b.StartObject(addrSize)
	ob.SetBytesFixed(addrBytesOff, in.Bytes[:])
	ob.FinishAsRoot()
	return b.Finish()
}

const (
	sigIndexOff = 0
	sigSize     = 4
)

// Sig is a zero-copy view into a ZAP-encoded Sig message.
type Sig struct{ o zap.Object }

// WrapSig parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapSig(b []byte) (Sig, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Sig{}, err
	}
	return Sig{o: m.Root()}, nil
}

func (t Sig) Index() uint32 { return t.o.Uint32(sigIndexOff) }

// Record is the sigSize bytes this Sig occupies where it lies.
func (t Sig) Record() []byte { return t.o.BytesFixed(0, sigSize) }

// SigList is a run of Sig records, sigSize bytes each.
type SigList struct{ l zap.List }

// Len is how many elements the list holds.
func (x SigList) Len() int { return x.l.Len() }

// At is element i, or the absent Sig past the end.
func (x SigList) At(i int) Sig { return Sig{o: x.l.Object(i, sigSize)} }

// SigInput collects the field values for NewSig.
type SigInput struct {
	Index uint32
}

// NewSig builds a ZAP-encoded Sig message from in and returns the bytes.
func NewSig(in SigInput) []byte {
	b := zap.NewBuilderV2(256)
	ob := b.StartObject(sigSize)
	ob.SetUint32(sigIndexOff, in.Index)
	ob.FinishAsRoot()
	return b.Finish()
}

const (
	blockKindOff       = 0
	blockParentOff     = 1
	blockHeightOff     = 33
	blockTimeOff       = 41
	blockTxLengthsOff  = 49
	blockTxBlobOff     = 57
	blockProposalTxOff = 65
	blockSize          = 73
)

// Block is a zero-copy view into a ZAP-encoded Block message.
type Block struct{ o zap.Object }

// WrapBlock parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapBlock(b []byte) (Block, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Block{}, err
	}
	return Block{o: m.Root()}, nil
}

func (t Block) Kind() uint8 { return t.o.Uint8(blockKindOff) }
func (t Block) Parent() [32]byte {
	var out [32]byte
	copy(out[:], t.o.BytesFixed(blockParentOff, 32))
	return out
}
func (t Block) Height() uint64     { return t.o.Uint64(blockHeightOff) }
func (t Block) Time() uint64       { return t.o.Uint64(blockTimeOff) }
func (t Block) TxLengths() SigList { return SigList{l: t.o.ListStride(blockTxLengthsOff, sigSize)} }
func (t Block) TxBlob() []byte     { return t.o.Bytes(blockTxBlobOff) }
func (t Block) ProposalTx() []byte { return t.o.Bytes(blockProposalTxOff) }

// BlockInput collects the field values for NewBlock.
type BlockInput struct {
	Kind       uint8
	Parent     [32]byte
	Height     uint64
	Time       uint64
	TxLengths  [][]byte
	TxBlob     []byte
	ProposalTx []byte
}

// NewBlock builds a ZAP-encoded Block message from in and returns the bytes.
func NewBlock(in BlockInput) []byte {
	b := zap.NewBuilderV2(256)
	txLengthsAt := 0
	if len(in.TxLengths) > 0 {
		lb := b.StartList(sigSize)
		for _, elem := range in.TxLengths {
			var rec [sigSize]byte
			copy(rec[:], elem)
			lb.AddBytes(rec[:])
		}
		txLengthsAt = lb.FinishOffset()
	}
	ob := b.StartObject(blockSize)
	ob.SetUint8(blockKindOff, in.Kind)
	ob.SetBytesFixed(blockParentOff, in.Parent[:])
	ob.SetUint64(blockHeightOff, in.Height)
	ob.SetUint64(blockTimeOff, in.Time)
	ob.SetList(blockTxLengthsOff, txLengthsAt, len(in.TxLengths))
	ob.SetBytes(blockTxBlobOff, in.TxBlob)
	ob.SetBytes(blockProposalTxOff, in.ProposalTx)
	ob.FinishAsRoot()
	return b.Finish()
}
