// Code generated by zapgen; DO NOT EDIT.
// source: kitchen.zap

//! ZAP schema `kitchen.zap`, package `kitchen`.
//!
//! Every view here borrows the buffer it reads: a field is a bounds-checked
//! look at bytes already in hand, never a decode into an owned struct. The
//! builders write into one buffer and hand it over at the end.

#![allow(dead_code)]

use crate::zap;

// Leaf — field offsets, in bytes, and the fixed section's size.
pub const LEAF_TAG: usize = 0;
pub const LEAF_NOTE: usize = 4;
pub const LEAF_SIZE: usize = 12;

/// A view of a ZAP-encoded Leaf. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Leaf<'a> {
    o: zap::Object<'a>,
}

impl<'a> Leaf<'a> {
    /// Take `data` as a Leaf message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Leaf {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Leaf { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn tag(&self) -> u32 {
        self.o.u32(LEAF_TAG)
    }

    pub fn note(&self) -> &'a str {
        self.o.text(LEAF_NOTE)
    }
}

/// A run of Leaf entries, each behind its length.
#[derive(Clone, Copy, Debug)]
pub struct LeafList<'a> {
    l: zap::List<'a>,
}

impl<'a> LeafList<'a> {
    /// How many elements the list holds.
    pub fn len(&self) -> usize {
        self.l.len()
    }

    /// Whether the list holds none.
    pub fn is_empty(&self) -> bool {
        self.l.len() == 0
    }

    /// Element `i`, or the absent Leaf past the end.
    pub fn at(&self, i: usize) -> Leaf<'a> {
        Leaf::new(self.l.object_at(i))
    }
}

/// The field values [`new_leaf`] writes.
#[derive(Clone, Copy, Debug)]
pub struct LeafInput<'a> {
    pub tag: u32,
    pub note: &'a str,
}

impl<'a> Default for LeafInput<'a> {
    fn default() -> Self {
        LeafInput {
            tag: 0,
            note: "",
        }
    }
}

/// Write a Leaf message and answer its bytes.
pub fn new_leaf(input: &LeafInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut ob = b.start_object(LEAF_SIZE);
    ob.set_u32(&mut b, LEAF_TAG, input.tag);
    ob.set_text(&mut b, LEAF_NOTE, input.note);
    ob.finish_as_root(&mut b);
    b.finish()
}

// All — field offsets, in bytes, and the fixed section's size.
pub const ALL_FLAG: usize = 0;
pub const ALL_A8: usize = 1;
pub const ALL_A16: usize = 2;
pub const ALL_A32: usize = 4;
pub const ALL_A64: usize = 8;
pub const ALL_S8: usize = 16;
pub const ALL_S16: usize = 18;
pub const ALL_S32: usize = 20;
pub const ALL_S64: usize = 24;
pub const ALL_F32: usize = 32;
pub const ALL_F64: usize = 40;
pub const ALL_NAME: usize = 48;
pub const ALL_BLOB: usize = 56;
pub const ALL_ID: usize = 64;
pub const ALL_ITEMS: usize = 80;
pub const ALL_INNER: usize = 88;
pub const ALL_SIZE: usize = 92;

/// A view of a ZAP-encoded All. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct All<'a> {
    o: zap::Object<'a>,
}

impl<'a> All<'a> {
    /// Take `data` as a All message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(All {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        All { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn flag(&self) -> bool {
        self.o.bool(ALL_FLAG)
    }

    pub fn a8(&self) -> u8 {
        self.o.u8(ALL_A8)
    }

    pub fn a16(&self) -> u16 {
        self.o.u16(ALL_A16)
    }

    pub fn a32(&self) -> u32 {
        self.o.u32(ALL_A32)
    }

    pub fn a64(&self) -> u64 {
        self.o.u64(ALL_A64)
    }

    pub fn s8(&self) -> i8 {
        self.o.i8(ALL_S8)
    }

    pub fn s16(&self) -> i16 {
        self.o.i16(ALL_S16)
    }

    pub fn s32(&self) -> i32 {
        self.o.i32(ALL_S32)
    }

    pub fn s64(&self) -> i64 {
        self.o.i64(ALL_S64)
    }

    pub fn f32(&self) -> f32 {
        self.o.f32(ALL_F32)
    }

    pub fn f64(&self) -> f64 {
        self.o.f64(ALL_F64)
    }

    pub fn name(&self) -> &'a str {
        self.o.text(ALL_NAME)
    }

    pub fn blob(&self) -> &'a [u8] {
        self.o.bytes(ALL_BLOB)
    }

    /// The 16 inline bytes at `ALL_ID`; zeros if the span runs off the buffer.
    pub fn id(&self) -> &'a [u8; 16] {
        self.o
            .bytes_fixed(ALL_ID, 16)
            .try_into()
            .unwrap_or(&[0u8; 16])
    }

    pub fn items(&self) -> LeafList<'a> {
        LeafList { l: self.o.list(ALL_ITEMS) }
    }

    pub fn inner(&self) -> Leaf<'a> {
        Leaf::new(self.o.object(ALL_INNER))
    }
}

/// The field values [`new_all`] writes.
#[derive(Clone, Copy, Debug)]
pub struct AllInput<'a> {
    pub flag: bool,
    pub a8: u8,
    pub a16: u16,
    pub a32: u32,
    pub a64: u64,
    pub s8: i8,
    pub s16: i16,
    pub s32: i32,
    pub s64: i64,
    pub f32: f32,
    pub f64: f64,
    pub name: &'a str,
    pub blob: &'a [u8],
    pub id: &'a [u8; 16],
    pub items: &'a [&'a [u8]],
    pub inner: &'a [u8],
}

impl<'a> Default for AllInput<'a> {
    fn default() -> Self {
        AllInput {
            flag: false,
            a8: 0,
            a16: 0,
            a32: 0,
            a64: 0,
            s8: 0,
            s16: 0,
            s32: 0,
            s64: 0,
            f32: 0.0,
            f64: 0.0,
            name: "",
            blob: &[],
            id: &[0u8; 16],
            items: &[],
            inner: &[],
        }
    }
}

/// Write a All message and answer its bytes.
pub fn new_all(input: &AllInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut at_items = 0;
    if !input.items.is_empty() {
        let mut lb = b.start_list();
        for elem in input.items {
            lb.add_object_bytes(&mut b, elem);
        }
        at_items = lb.finish_offset();
    }
    let at_inner = b.embed(input.inner);
    let mut ob = b.start_object(ALL_SIZE);
    ob.set_bool(&mut b, ALL_FLAG, input.flag);
    ob.set_u8(&mut b, ALL_A8, input.a8);
    ob.set_u16(&mut b, ALL_A16, input.a16);
    ob.set_u32(&mut b, ALL_A32, input.a32);
    ob.set_u64(&mut b, ALL_A64, input.a64);
    ob.set_i8(&mut b, ALL_S8, input.s8);
    ob.set_i16(&mut b, ALL_S16, input.s16);
    ob.set_i32(&mut b, ALL_S32, input.s32);
    ob.set_i64(&mut b, ALL_S64, input.s64);
    ob.set_f32(&mut b, ALL_F32, input.f32);
    ob.set_f64(&mut b, ALL_F64, input.f64);
    ob.set_text(&mut b, ALL_NAME, input.name);
    ob.set_bytes(&mut b, ALL_BLOB, input.blob);
    ob.set_bytes_fixed(&mut b, ALL_ID, input.id);
    ob.set_list(&mut b, ALL_ITEMS, at_items, input.items.len());
    ob.set_object(&mut b, ALL_INNER, at_inner);
    ob.finish_as_root(&mut b);
    b.finish()
}

