// Code generated by zapgen; DO NOT EDIT.
// source: pchain.zap

//! ZAP schema `pchain.zap`, package `pchain`.
//!
//! Every view here borrows the buffer it reads: a field is a bounds-checked
//! look at bytes already in hand, never a decode into an owned struct. The
//! builders write into one buffer and hand it over at the end.

#![allow(dead_code)]

use crate::zap;

// Spend — field offsets, in bytes, and the fixed section's size.
pub const SPEND_KIND: usize = 0;
pub const SPEND_NETWORK_ID: usize = 1;
pub const SPEND_BLOCKCHAIN_ID: usize = 5;
pub const SPEND_OUTS: usize = 37;
pub const SPEND_OWNER_ADDRS: usize = 45;
pub const SPEND_INS: usize = 53;
pub const SPEND_SIG_INDICES: usize = 61;
pub const SPEND_MEMO: usize = 69;
pub const SPEND_SIZE: usize = 77;

/// A view of a ZAP-encoded Spend. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Spend<'a> {
    o: zap::Object<'a>,
}

impl<'a> Spend<'a> {
    /// Take `data` as a Spend message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Spend {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Spend { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn kind(&self) -> u8 {
        self.o.u8(SPEND_KIND)
    }

    pub fn network_id(&self) -> u32 {
        self.o.u32(SPEND_NETWORK_ID)
    }

    /// The 32 inline bytes at `SPEND_BLOCKCHAIN_ID`; zeros if the span runs off the buffer.
    pub fn blockchain_id(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(SPEND_BLOCKCHAIN_ID, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn outs(&self) -> zap::List<'a> {
        self.o.list(SPEND_OUTS)
    }

    pub fn owner_addrs(&self) -> zap::List<'a> {
        self.o.list(SPEND_OWNER_ADDRS)
    }

    pub fn ins(&self) -> zap::List<'a> {
        self.o.list(SPEND_INS)
    }

    pub fn sig_indices(&self) -> zap::List<'a> {
        self.o.list(SPEND_SIG_INDICES)
    }

    pub fn memo(&self) -> &'a [u8] {
        self.o.bytes(SPEND_MEMO)
    }
}

/// The field values [`new_spend`] writes.
#[derive(Clone, Copy, Debug)]
pub struct SpendInput<'a> {
    pub kind: u8,
    pub network_id: u32,
    pub blockchain_id: &'a [u8; 32],
    pub outs: &'a [&'a [u8]],
    pub owner_addrs: &'a [&'a [u8]],
    pub ins: &'a [&'a [u8]],
    pub sig_indices: &'a [&'a [u8]],
    pub memo: &'a [u8],
}

impl<'a> Default for SpendInput<'a> {
    fn default() -> Self {
        SpendInput {
            kind: 0,
            network_id: 0,
            blockchain_id: &[0u8; 32],
            outs: &[],
            owner_addrs: &[],
            ins: &[],
            sig_indices: &[],
            memo: &[],
        }
    }
}

/// Write a Spend message and answer its bytes.
pub fn new_spend(input: &SpendInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new(256);
    let mut ob = b.start_object(SPEND_SIZE);
    ob.set_u8(&mut b, SPEND_KIND, input.kind);
    ob.set_u32(&mut b, SPEND_NETWORK_ID, input.network_id);
    ob.set_bytes_fixed(&mut b, SPEND_BLOCKCHAIN_ID, input.blockchain_id);
    let mut list_outs = b.start_list();
    for elem in input.outs {
        list_outs.add_object_bytes(&mut b, elem);
    }
    ob.set_list(&mut b, SPEND_OUTS, list_outs.finish_offset(), input.outs.len());
    let mut list_owner_addrs = b.start_list();
    for elem in input.owner_addrs {
        list_owner_addrs.add_object_bytes(&mut b, elem);
    }
    ob.set_list(&mut b, SPEND_OWNER_ADDRS, list_owner_addrs.finish_offset(), input.owner_addrs.len());
    let mut list_ins = b.start_list();
    for elem in input.ins {
        list_ins.add_object_bytes(&mut b, elem);
    }
    ob.set_list(&mut b, SPEND_INS, list_ins.finish_offset(), input.ins.len());
    let mut list_sig_indices = b.start_list();
    for elem in input.sig_indices {
        list_sig_indices.add_object_bytes(&mut b, elem);
    }
    ob.set_list(&mut b, SPEND_SIG_INDICES, list_sig_indices.finish_offset(), input.sig_indices.len());
    ob.set_bytes(&mut b, SPEND_MEMO, input.memo);
    ob.finish_as_root(&mut b);
    b.finish()
}

// Out — field offsets, in bytes, and the fixed section's size.
pub const OUT_ASSET: usize = 0;
pub const OUT_STAKE_LOCK: usize = 32;
pub const OUT_AMOUNT: usize = 40;
pub const OUT_THRESHOLD: usize = 48;
pub const OUT_OWNER_LOCK: usize = 52;
pub const OUT_ADDR_START: usize = 60;
pub const OUT_ADDR_COUNT: usize = 64;
pub const OUT_PAD: usize = 68;
pub const OUT_SIZE: usize = 72;

/// A view of a ZAP-encoded Out. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Out<'a> {
    o: zap::Object<'a>,
}

impl<'a> Out<'a> {
    /// Take `data` as a Out message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Out {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Out { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 32 inline bytes at `OUT_ASSET`; zeros if the span runs off the buffer.
    pub fn asset(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(OUT_ASSET, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn stake_lock(&self) -> u64 {
        self.o.u64(OUT_STAKE_LOCK)
    }

    pub fn amount(&self) -> u64 {
        self.o.u64(OUT_AMOUNT)
    }

    pub fn threshold(&self) -> u32 {
        self.o.u32(OUT_THRESHOLD)
    }

    pub fn owner_lock(&self) -> u64 {
        self.o.u64(OUT_OWNER_LOCK)
    }

    pub fn addr_start(&self) -> u32 {
        self.o.u32(OUT_ADDR_START)
    }

    pub fn addr_count(&self) -> u32 {
        self.o.u32(OUT_ADDR_COUNT)
    }

    /// The 4 inline bytes at `OUT_PAD`; zeros if the span runs off the buffer.
    pub fn pad(&self) -> &'a [u8; 4] {
        self.o
            .bytes_fixed(OUT_PAD, 4)
            .try_into()
            .unwrap_or(&[0u8; 4])
    }
}

/// The field values [`new_out`] writes.
#[derive(Clone, Copy, Debug)]
pub struct OutInput<'a> {
    pub asset: &'a [u8; 32],
    pub stake_lock: u64,
    pub amount: u64,
    pub threshold: u32,
    pub owner_lock: u64,
    pub addr_start: u32,
    pub addr_count: u32,
    pub pad: &'a [u8; 4],
}

impl<'a> Default for OutInput<'a> {
    fn default() -> Self {
        OutInput {
            asset: &[0u8; 32],
            stake_lock: 0,
            amount: 0,
            threshold: 0,
            owner_lock: 0,
            addr_start: 0,
            addr_count: 0,
            pad: &[0u8; 4],
        }
    }
}

/// Write a Out message and answer its bytes.
pub fn new_out(input: &OutInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new(256);
    let mut ob = b.start_object(OUT_SIZE);
    ob.set_bytes_fixed(&mut b, OUT_ASSET, input.asset);
    ob.set_u64(&mut b, OUT_STAKE_LOCK, input.stake_lock);
    ob.set_u64(&mut b, OUT_AMOUNT, input.amount);
    ob.set_u32(&mut b, OUT_THRESHOLD, input.threshold);
    ob.set_u64(&mut b, OUT_OWNER_LOCK, input.owner_lock);
    ob.set_u32(&mut b, OUT_ADDR_START, input.addr_start);
    ob.set_u32(&mut b, OUT_ADDR_COUNT, input.addr_count);
    ob.set_bytes_fixed(&mut b, OUT_PAD, input.pad);
    ob.finish_as_root(&mut b);
    b.finish()
}

// In — field offsets, in bytes, and the fixed section's size.
pub const IN_TX_ID: usize = 0;
pub const IN_OUTPUT_INDEX: usize = 32;
pub const IN_ASSET: usize = 36;
pub const IN_STAKE_LOCK: usize = 68;
pub const IN_AMOUNT: usize = 76;
pub const IN_SIG_START: usize = 84;
pub const IN_SIG_COUNT: usize = 88;
pub const IN_PAD: usize = 92;
pub const IN_SIZE: usize = 96;

/// A view of a ZAP-encoded In. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct In<'a> {
    o: zap::Object<'a>,
}

impl<'a> In<'a> {
    /// Take `data` as a In message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(In {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        In { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 32 inline bytes at `IN_TX_ID`; zeros if the span runs off the buffer.
    pub fn tx_id(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(IN_TX_ID, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn output_index(&self) -> u32 {
        self.o.u32(IN_OUTPUT_INDEX)
    }

    /// The 32 inline bytes at `IN_ASSET`; zeros if the span runs off the buffer.
    pub fn asset(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(IN_ASSET, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn stake_lock(&self) -> u64 {
        self.o.u64(IN_STAKE_LOCK)
    }

    pub fn amount(&self) -> u64 {
        self.o.u64(IN_AMOUNT)
    }

    pub fn sig_start(&self) -> u32 {
        self.o.u32(IN_SIG_START)
    }

    pub fn sig_count(&self) -> u32 {
        self.o.u32(IN_SIG_COUNT)
    }

    /// The 4 inline bytes at `IN_PAD`; zeros if the span runs off the buffer.
    pub fn pad(&self) -> &'a [u8; 4] {
        self.o
            .bytes_fixed(IN_PAD, 4)
            .try_into()
            .unwrap_or(&[0u8; 4])
    }
}

/// The field values [`new_in`] writes.
#[derive(Clone, Copy, Debug)]
pub struct InInput<'a> {
    pub tx_id: &'a [u8; 32],
    pub output_index: u32,
    pub asset: &'a [u8; 32],
    pub stake_lock: u64,
    pub amount: u64,
    pub sig_start: u32,
    pub sig_count: u32,
    pub pad: &'a [u8; 4],
}

impl<'a> Default for InInput<'a> {
    fn default() -> Self {
        InInput {
            tx_id: &[0u8; 32],
            output_index: 0,
            asset: &[0u8; 32],
            stake_lock: 0,
            amount: 0,
            sig_start: 0,
            sig_count: 0,
            pad: &[0u8; 4],
        }
    }
}

/// Write a In message and answer its bytes.
pub fn new_in(input: &InInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new(256);
    let mut ob = b.start_object(IN_SIZE);
    ob.set_bytes_fixed(&mut b, IN_TX_ID, input.tx_id);
    ob.set_u32(&mut b, IN_OUTPUT_INDEX, input.output_index);
    ob.set_bytes_fixed(&mut b, IN_ASSET, input.asset);
    ob.set_u64(&mut b, IN_STAKE_LOCK, input.stake_lock);
    ob.set_u64(&mut b, IN_AMOUNT, input.amount);
    ob.set_u32(&mut b, IN_SIG_START, input.sig_start);
    ob.set_u32(&mut b, IN_SIG_COUNT, input.sig_count);
    ob.set_bytes_fixed(&mut b, IN_PAD, input.pad);
    ob.finish_as_root(&mut b);
    b.finish()
}

// Addr — field offsets, in bytes, and the fixed section's size.
pub const ADDR_BYTES: usize = 0;
pub const ADDR_SIZE: usize = 20;

/// A view of a ZAP-encoded Addr. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Addr<'a> {
    o: zap::Object<'a>,
}

impl<'a> Addr<'a> {
    /// Take `data` as a Addr message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Addr {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Addr { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 20 inline bytes at `ADDR_BYTES`; zeros if the span runs off the buffer.
    pub fn bytes(&self) -> &'a [u8; 20] {
        self.o
            .bytes_fixed(ADDR_BYTES, 20)
            .try_into()
            .unwrap_or(&[0u8; 20])
    }
}

/// The field values [`new_addr`] writes.
#[derive(Clone, Copy, Debug)]
pub struct AddrInput<'a> {
    pub bytes: &'a [u8; 20],
}

impl<'a> Default for AddrInput<'a> {
    fn default() -> Self {
        AddrInput {
            bytes: &[0u8; 20],
        }
    }
}

/// Write a Addr message and answer its bytes.
pub fn new_addr(input: &AddrInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new(256);
    let mut ob = b.start_object(ADDR_SIZE);
    ob.set_bytes_fixed(&mut b, ADDR_BYTES, input.bytes);
    ob.finish_as_root(&mut b);
    b.finish()
}

// Sig — field offsets, in bytes, and the fixed section's size.
pub const SIG_INDEX: usize = 0;
pub const SIG_SIZE: usize = 4;

/// A view of a ZAP-encoded Sig. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Sig<'a> {
    o: zap::Object<'a>,
}

impl<'a> Sig<'a> {
    /// Take `data` as a Sig message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Sig {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Sig { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn index(&self) -> u32 {
        self.o.u32(SIG_INDEX)
    }
}

/// The field values [`new_sig`] writes.
#[derive(Clone, Copy, Debug)]
pub struct SigInput {
    pub index: u32,
}

impl Default for SigInput {
    fn default() -> Self {
        SigInput {
            index: 0,
        }
    }
}

/// Write a Sig message and answer its bytes.
pub fn new_sig(input: &SigInput) -> Vec<u8> {
    let mut b = zap::Builder::new(256);
    let mut ob = b.start_object(SIG_SIZE);
    ob.set_u32(&mut b, SIG_INDEX, input.index);
    ob.finish_as_root(&mut b);
    b.finish()
}

// Block — field offsets, in bytes, and the fixed section's size.
pub const BLOCK_KIND: usize = 0;
pub const BLOCK_PARENT: usize = 1;
pub const BLOCK_HEIGHT: usize = 33;
pub const BLOCK_TIME: usize = 41;
pub const BLOCK_TX_LENGTHS: usize = 49;
pub const BLOCK_TX_BLOB: usize = 57;
pub const BLOCK_PROPOSAL_TX: usize = 65;
pub const BLOCK_SIZE: usize = 73;

/// A view of a ZAP-encoded Block. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Block<'a> {
    o: zap::Object<'a>,
}

impl<'a> Block<'a> {
    /// Take `data` as a Block message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Block {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Block { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn kind(&self) -> u8 {
        self.o.u8(BLOCK_KIND)
    }

    /// The 32 inline bytes at `BLOCK_PARENT`; zeros if the span runs off the buffer.
    pub fn parent(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(BLOCK_PARENT, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn height(&self) -> u64 {
        self.o.u64(BLOCK_HEIGHT)
    }

    pub fn time(&self) -> u64 {
        self.o.u64(BLOCK_TIME)
    }

    pub fn tx_lengths(&self) -> zap::List<'a> {
        self.o.list(BLOCK_TX_LENGTHS)
    }

    pub fn tx_blob(&self) -> &'a [u8] {
        self.o.bytes(BLOCK_TX_BLOB)
    }

    pub fn proposal_tx(&self) -> &'a [u8] {
        self.o.bytes(BLOCK_PROPOSAL_TX)
    }
}

/// The field values [`new_block`] writes.
#[derive(Clone, Copy, Debug)]
pub struct BlockInput<'a> {
    pub kind: u8,
    pub parent: &'a [u8; 32],
    pub height: u64,
    pub time: u64,
    pub tx_lengths: &'a [&'a [u8]],
    pub tx_blob: &'a [u8],
    pub proposal_tx: &'a [u8],
}

impl<'a> Default for BlockInput<'a> {
    fn default() -> Self {
        BlockInput {
            kind: 0,
            parent: &[0u8; 32],
            height: 0,
            time: 0,
            tx_lengths: &[],
            tx_blob: &[],
            proposal_tx: &[],
        }
    }
}

/// Write a Block message and answer its bytes.
pub fn new_block(input: &BlockInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new(256);
    let mut ob = b.start_object(BLOCK_SIZE);
    ob.set_u8(&mut b, BLOCK_KIND, input.kind);
    ob.set_bytes_fixed(&mut b, BLOCK_PARENT, input.parent);
    ob.set_u64(&mut b, BLOCK_HEIGHT, input.height);
    ob.set_u64(&mut b, BLOCK_TIME, input.time);
    let mut list_tx_lengths = b.start_list();
    for elem in input.tx_lengths {
        list_tx_lengths.add_object_bytes(&mut b, elem);
    }
    ob.set_list(&mut b, BLOCK_TX_LENGTHS, list_tx_lengths.finish_offset(), input.tx_lengths.len());
    ob.set_bytes(&mut b, BLOCK_TX_BLOB, input.tx_blob);
    ob.set_bytes(&mut b, BLOCK_PROPOSAL_TX, input.proposal_tx);
    ob.finish_as_root(&mut b);
    b.finish()
}

