// Code generated by zapgen; DO NOT EDIT.
// source: pchain.zap

//! ZAP schema `pchain.zap`, package `pchain`.
//!
//! Every view here borrows the buffer it reads: a field is a bounds-checked
//! look at bytes already in hand, never a decode into an owned struct. The
//! builders write into one buffer and hand it over at the end.

#![allow(dead_code)]

use crate::zap;

// Spend — field offsets, in bytes, and the fixed section's size.
pub const SPEND_KIND: usize = 0;
pub const SPEND_NETWORK_ID: usize = 1;
pub const SPEND_BLOCKCHAIN_ID: usize = 5;
pub const SPEND_OUTS: usize = 37;
pub const SPEND_OWNER_ADDRS: usize = 45;
pub const SPEND_INS: usize = 53;
pub const SPEND_SIG_INDICES: usize = 61;
pub const SPEND_MEMO: usize = 69;
pub const SPEND_SIZE: usize = 77;

/// A view of a ZAP-encoded Spend. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Spend<'a> {
    o: zap::Object<'a>,
}

impl<'a> Spend<'a> {
    /// Take `data` as a Spend message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Spend {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Spend { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn kind(&self) -> u8 {
        self.o.u8(SPEND_KIND)
    }

    pub fn network_id(&self) -> u32 {
        self.o.u32(SPEND_NETWORK_ID)
    }

    /// The 32 inline bytes at `SPEND_BLOCKCHAIN_ID`; zeros if the span runs off the buffer.
    pub fn blockchain_id(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(SPEND_BLOCKCHAIN_ID, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn outs(&self) -> OutList<'a> {
        OutList { l: self.o.list_stride(SPEND_OUTS, OUT_SIZE) }
    }

    pub fn owner_addrs(&self) -> AddrList<'a> {
        AddrList { l: self.o.list_stride(SPEND_OWNER_ADDRS, ADDR_SIZE) }
    }

    pub fn ins(&self) -> InList<'a> {
        InList { l: self.o.list_stride(SPEND_INS, IN_SIZE) }
    }

    pub fn sig_indices(&self) -> SigList<'a> {
        SigList { l: self.o.list_stride(SPEND_SIG_INDICES, SIG_SIZE) }
    }

    pub fn memo(&self) -> &'a [u8] {
        self.o.bytes(SPEND_MEMO)
    }
}

/// The field values [`new_spend`] writes.
#[derive(Clone, Copy, Debug)]
pub struct SpendInput<'a> {
    pub kind: u8,
    pub network_id: u32,
    pub blockchain_id: &'a [u8; 32],
    pub outs: &'a [&'a [u8]],
    pub owner_addrs: &'a [&'a [u8]],
    pub ins: &'a [&'a [u8]],
    pub sig_indices: &'a [&'a [u8]],
    pub memo: &'a [u8],
}

impl<'a> Default for SpendInput<'a> {
    fn default() -> Self {
        SpendInput {
            kind: 0,
            network_id: 0,
            blockchain_id: &[0u8; 32],
            outs: &[],
            owner_addrs: &[],
            ins: &[],
            sig_indices: &[],
            memo: &[],
        }
    }
}

/// Write a Spend message and answer its bytes.
pub fn new_spend(input: &SpendInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut at_outs = 0;
    if !input.outs.is_empty() {
        let mut lb = b.start_list();
        for elem in input.outs {
            let mut rec = [0u8; OUT_SIZE];
            let n = elem.len().min(OUT_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_outs = lb.finish_offset();
    }
    let mut at_owner_addrs = 0;
    if !input.owner_addrs.is_empty() {
        let mut lb = b.start_list();
        for elem in input.owner_addrs {
            let mut rec = [0u8; ADDR_SIZE];
            let n = elem.len().min(ADDR_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_owner_addrs = lb.finish_offset();
    }
    let mut at_ins = 0;
    if !input.ins.is_empty() {
        let mut lb = b.start_list();
        for elem in input.ins {
            let mut rec = [0u8; IN_SIZE];
            let n = elem.len().min(IN_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_ins = lb.finish_offset();
    }
    let mut at_sig_indices = 0;
    if !input.sig_indices.is_empty() {
        let mut lb = b.start_list();
        for elem in input.sig_indices {
            let mut rec = [0u8; SIG_SIZE];
            let n = elem.len().min(SIG_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_sig_indices = lb.finish_offset();
    }
    let mut ob = b.start_object(SPEND_SIZE);
    ob.set_u8(&mut b, SPEND_KIND, input.kind);
    ob.set_u32(&mut b, SPEND_NETWORK_ID, input.network_id);
    ob.set_bytes_fixed(&mut b, SPEND_BLOCKCHAIN_ID, input.blockchain_id);
    ob.set_list(&mut b, SPEND_OUTS, at_outs, input.outs.len());
    ob.set_list(&mut b, SPEND_OWNER_ADDRS, at_owner_addrs, input.owner_addrs.len());
    ob.set_list(&mut b, SPEND_INS, at_ins, input.ins.len());
    ob.set_list(&mut b, SPEND_SIG_INDICES, at_sig_indices, input.sig_indices.len());
    ob.set_bytes(&mut b, SPEND_MEMO, input.memo);
    ob.finish_as_root(&mut b);
    b.finish()
}

// Out — field offsets, in bytes, and the fixed section's size.
pub const OUT_ASSET: usize = 0;
pub const OUT_STAKE_LOCK: usize = 32;
pub const OUT_AMOUNT: usize = 40;
pub const OUT_THRESHOLD: usize = 48;
pub const OUT_OWNER_LOCK: usize = 52;
pub const OUT_ADDR_START: usize = 60;
pub const OUT_ADDR_COUNT: usize = 64;
pub const OUT_PAD: usize = 68;
pub const OUT_SIZE: usize = 72;

/// A view of a ZAP-encoded Out. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Out<'a> {
    o: zap::Object<'a>,
}

impl<'a> Out<'a> {
    /// Take `data` as a Out message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Out {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Out { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 32 inline bytes at `OUT_ASSET`; zeros if the span runs off the buffer.
    pub fn asset(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(OUT_ASSET, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn stake_lock(&self) -> u64 {
        self.o.u64(OUT_STAKE_LOCK)
    }

    pub fn amount(&self) -> u64 {
        self.o.u64(OUT_AMOUNT)
    }

    pub fn threshold(&self) -> u32 {
        self.o.u32(OUT_THRESHOLD)
    }

    pub fn owner_lock(&self) -> u64 {
        self.o.u64(OUT_OWNER_LOCK)
    }

    pub fn addr_start(&self) -> u32 {
        self.o.u32(OUT_ADDR_START)
    }

    pub fn addr_count(&self) -> u32 {
        self.o.u32(OUT_ADDR_COUNT)
    }

    /// The 4 inline bytes at `OUT_PAD`; zeros if the span runs off the buffer.
    pub fn pad(&self) -> &'a [u8; 4] {
        self.o
            .bytes_fixed(OUT_PAD, 4)
            .try_into()
            .unwrap_or(&[0u8; 4])
    }

    /// The OUT_SIZE bytes this Out occupies where it lies.
    pub fn record(&self) -> &'a [u8] {
        self.o.bytes_fixed(0, OUT_SIZE)
    }
}

/// A run of Out records, OUT_SIZE bytes each.
#[derive(Clone, Copy, Debug)]
pub struct OutList<'a> {
    l: zap::List<'a>,
}

impl<'a> OutList<'a> {
    /// How many elements the list holds.
    pub fn len(&self) -> usize {
        self.l.len()
    }

    /// Whether the list holds none.
    pub fn is_empty(&self) -> bool {
        self.l.len() == 0
    }

    /// Element `i`, or the absent Out past the end.
    pub fn at(&self, i: usize) -> Out<'a> {
        Out::new(self.l.object(i, OUT_SIZE))
    }
}

/// The field values [`new_out`] writes.
#[derive(Clone, Copy, Debug)]
pub struct OutInput<'a> {
    pub asset: &'a [u8; 32],
    pub stake_lock: u64,
    pub amount: u64,
    pub threshold: u32,
    pub owner_lock: u64,
    pub addr_start: u32,
    pub addr_count: u32,
    pub pad: &'a [u8; 4],
}

impl<'a> Default for OutInput<'a> {
    fn default() -> Self {
        OutInput {
            asset: &[0u8; 32],
            stake_lock: 0,
            amount: 0,
            threshold: 0,
            owner_lock: 0,
            addr_start: 0,
            addr_count: 0,
            pad: &[0u8; 4],
        }
    }
}

/// Write a Out message and answer its bytes.
pub fn new_out(input: &OutInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut ob = b.start_object(OUT_SIZE);
    ob.set_bytes_fixed(&mut b, OUT_ASSET, input.asset);
    ob.set_u64(&mut b, OUT_STAKE_LOCK, input.stake_lock);
    ob.set_u64(&mut b, OUT_AMOUNT, input.amount);
    ob.set_u32(&mut b, OUT_THRESHOLD, input.threshold);
    ob.set_u64(&mut b, OUT_OWNER_LOCK, input.owner_lock);
    ob.set_u32(&mut b, OUT_ADDR_START, input.addr_start);
    ob.set_u32(&mut b, OUT_ADDR_COUNT, input.addr_count);
    ob.set_bytes_fixed(&mut b, OUT_PAD, input.pad);
    ob.finish_as_root(&mut b);
    b.finish()
}

// In — field offsets, in bytes, and the fixed section's size.
pub const IN_TX_ID: usize = 0;
pub const IN_OUTPUT_INDEX: usize = 32;
pub const IN_ASSET: usize = 36;
pub const IN_STAKE_LOCK: usize = 68;
pub const IN_AMOUNT: usize = 76;
pub const IN_SIG_START: usize = 84;
pub const IN_SIG_COUNT: usize = 88;
pub const IN_PAD: usize = 92;
pub const IN_SIZE: usize = 96;

/// A view of a ZAP-encoded In. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct In<'a> {
    o: zap::Object<'a>,
}

impl<'a> In<'a> {
    /// Take `data` as a In message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(In {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        In { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 32 inline bytes at `IN_TX_ID`; zeros if the span runs off the buffer.
    pub fn tx_id(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(IN_TX_ID, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn output_index(&self) -> u32 {
        self.o.u32(IN_OUTPUT_INDEX)
    }

    /// The 32 inline bytes at `IN_ASSET`; zeros if the span runs off the buffer.
    pub fn asset(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(IN_ASSET, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn stake_lock(&self) -> u64 {
        self.o.u64(IN_STAKE_LOCK)
    }

    pub fn amount(&self) -> u64 {
        self.o.u64(IN_AMOUNT)
    }

    pub fn sig_start(&self) -> u32 {
        self.o.u32(IN_SIG_START)
    }

    pub fn sig_count(&self) -> u32 {
        self.o.u32(IN_SIG_COUNT)
    }

    /// The 4 inline bytes at `IN_PAD`; zeros if the span runs off the buffer.
    pub fn pad(&self) -> &'a [u8; 4] {
        self.o
            .bytes_fixed(IN_PAD, 4)
            .try_into()
            .unwrap_or(&[0u8; 4])
    }

    /// The IN_SIZE bytes this In occupies where it lies.
    pub fn record(&self) -> &'a [u8] {
        self.o.bytes_fixed(0, IN_SIZE)
    }
}

/// A run of In records, IN_SIZE bytes each.
#[derive(Clone, Copy, Debug)]
pub struct InList<'a> {
    l: zap::List<'a>,
}

impl<'a> InList<'a> {
    /// How many elements the list holds.
    pub fn len(&self) -> usize {
        self.l.len()
    }

    /// Whether the list holds none.
    pub fn is_empty(&self) -> bool {
        self.l.len() == 0
    }

    /// Element `i`, or the absent In past the end.
    pub fn at(&self, i: usize) -> In<'a> {
        In::new(self.l.object(i, IN_SIZE))
    }
}

/// The field values [`new_in`] writes.
#[derive(Clone, Copy, Debug)]
pub struct InInput<'a> {
    pub tx_id: &'a [u8; 32],
    pub output_index: u32,
    pub asset: &'a [u8; 32],
    pub stake_lock: u64,
    pub amount: u64,
    pub sig_start: u32,
    pub sig_count: u32,
    pub pad: &'a [u8; 4],
}

impl<'a> Default for InInput<'a> {
    fn default() -> Self {
        InInput {
            tx_id: &[0u8; 32],
            output_index: 0,
            asset: &[0u8; 32],
            stake_lock: 0,
            amount: 0,
            sig_start: 0,
            sig_count: 0,
            pad: &[0u8; 4],
        }
    }
}

/// Write a In message and answer its bytes.
pub fn new_in(input: &InInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut ob = b.start_object(IN_SIZE);
    ob.set_bytes_fixed(&mut b, IN_TX_ID, input.tx_id);
    ob.set_u32(&mut b, IN_OUTPUT_INDEX, input.output_index);
    ob.set_bytes_fixed(&mut b, IN_ASSET, input.asset);
    ob.set_u64(&mut b, IN_STAKE_LOCK, input.stake_lock);
    ob.set_u64(&mut b, IN_AMOUNT, input.amount);
    ob.set_u32(&mut b, IN_SIG_START, input.sig_start);
    ob.set_u32(&mut b, IN_SIG_COUNT, input.sig_count);
    ob.set_bytes_fixed(&mut b, IN_PAD, input.pad);
    ob.finish_as_root(&mut b);
    b.finish()
}

// Addr — field offsets, in bytes, and the fixed section's size.
pub const ADDR_BYTES: usize = 0;
pub const ADDR_SIZE: usize = 20;

/// A view of a ZAP-encoded Addr. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Addr<'a> {
    o: zap::Object<'a>,
}

impl<'a> Addr<'a> {
    /// Take `data` as a Addr message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Addr {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Addr { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 20 inline bytes at `ADDR_BYTES`; zeros if the span runs off the buffer.
    pub fn bytes(&self) -> &'a [u8; 20] {
        self.o
            .bytes_fixed(ADDR_BYTES, 20)
            .try_into()
            .unwrap_or(&[0u8; 20])
    }

    /// The ADDR_SIZE bytes this Addr occupies where it lies.
    pub fn record(&self) -> &'a [u8] {
        self.o.bytes_fixed(0, ADDR_SIZE)
    }
}

/// A run of Addr records, ADDR_SIZE bytes each.
#[derive(Clone, Copy, Debug)]
pub struct AddrList<'a> {
    l: zap::List<'a>,
}

impl<'a> AddrList<'a> {
    /// How many elements the list holds.
    pub fn len(&self) -> usize {
        self.l.len()
    }

    /// Whether the list holds none.
    pub fn is_empty(&self) -> bool {
        self.l.len() == 0
    }

    /// Element `i`, or the absent Addr past the end.
    pub fn at(&self, i: usize) -> Addr<'a> {
        Addr::new(self.l.object(i, ADDR_SIZE))
    }
}

/// The field values [`new_addr`] writes.
#[derive(Clone, Copy, Debug)]
pub struct AddrInput<'a> {
    pub bytes: &'a [u8; 20],
}

impl<'a> Default for AddrInput<'a> {
    fn default() -> Self {
        AddrInput {
            bytes: &[0u8; 20],
        }
    }
}

/// Write a Addr message and answer its bytes.
pub fn new_addr(input: &AddrInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut ob = b.start_object(ADDR_SIZE);
    ob.set_bytes_fixed(&mut b, ADDR_BYTES, input.bytes);
    ob.finish_as_root(&mut b);
    b.finish()
}

// Sig — field offsets, in bytes, and the fixed section's size.
pub const SIG_INDEX: usize = 0;
pub const SIG_SIZE: usize = 4;

/// A view of a ZAP-encoded Sig. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Sig<'a> {
    o: zap::Object<'a>,
}

impl<'a> Sig<'a> {
    /// Take `data` as a Sig message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Sig {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Sig { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn index(&self) -> u32 {
        self.o.u32(SIG_INDEX)
    }

    /// The SIG_SIZE bytes this Sig occupies where it lies.
    pub fn record(&self) -> &'a [u8] {
        self.o.bytes_fixed(0, SIG_SIZE)
    }
}

/// A run of Sig records, SIG_SIZE bytes each.
#[derive(Clone, Copy, Debug)]
pub struct SigList<'a> {
    l: zap::List<'a>,
}

impl<'a> SigList<'a> {
    /// How many elements the list holds.
    pub fn len(&self) -> usize {
        self.l.len()
    }

    /// Whether the list holds none.
    pub fn is_empty(&self) -> bool {
        self.l.len() == 0
    }

    /// Element `i`, or the absent Sig past the end.
    pub fn at(&self, i: usize) -> Sig<'a> {
        Sig::new(self.l.object(i, SIG_SIZE))
    }
}

/// The field values [`new_sig`] writes.
#[derive(Clone, Copy, Debug)]
pub struct SigInput {
    pub index: u32,
}

impl Default for SigInput {
    fn default() -> Self {
        SigInput {
            index: 0,
        }
    }
}

/// Write a Sig message and answer its bytes.
pub fn new_sig(input: &SigInput) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut ob = b.start_object(SIG_SIZE);
    ob.set_u32(&mut b, SIG_INDEX, input.index);
    ob.finish_as_root(&mut b);
    b.finish()
}

// Block — field offsets, in bytes, and the fixed section's size.
pub const BLOCK_KIND: usize = 0;
pub const BLOCK_PARENT: usize = 1;
pub const BLOCK_HEIGHT: usize = 33;
pub const BLOCK_TIME: usize = 41;
pub const BLOCK_TX_LENGTHS: usize = 49;
pub const BLOCK_TX_BLOB: usize = 57;
pub const BLOCK_PROPOSAL_TX: usize = 65;
pub const BLOCK_SIZE: usize = 73;

/// A view of a ZAP-encoded Block. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Block<'a> {
    o: zap::Object<'a>,
}

impl<'a> Block<'a> {
    /// Take `data` as a Block message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Block {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Block { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn kind(&self) -> u8 {
        self.o.u8(BLOCK_KIND)
    }

    /// The 32 inline bytes at `BLOCK_PARENT`; zeros if the span runs off the buffer.
    pub fn parent(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(BLOCK_PARENT, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn height(&self) -> u64 {
        self.o.u64(BLOCK_HEIGHT)
    }

    pub fn time(&self) -> u64 {
        self.o.u64(BLOCK_TIME)
    }

    pub fn tx_lengths(&self) -> SigList<'a> {
        SigList { l: self.o.list_stride(BLOCK_TX_LENGTHS, SIG_SIZE) }
    }

    pub fn tx_blob(&self) -> &'a [u8] {
        self.o.bytes(BLOCK_TX_BLOB)
    }

    pub fn proposal_tx(&self) -> &'a [u8] {
        self.o.bytes(BLOCK_PROPOSAL_TX)
    }
}

/// The field values [`new_block`] writes.
#[derive(Clone, Copy, Debug)]
pub struct BlockInput<'a> {
    pub kind: u8,
    pub parent: &'a [u8; 32],
    pub height: u64,
    pub time: u64,
    pub tx_lengths: &'a [&'a [u8]],
    pub tx_blob: &'a [u8],
    pub proposal_tx: &'a [u8],
}

impl<'a> Default for BlockInput<'a> {
    fn default() -> Self {
        BlockInput {
            kind: 0,
            parent: &[0u8; 32],
            height: 0,
            time: 0,
            tx_lengths: &[],
            tx_blob: &[],
            proposal_tx: &[],
        }
    }
}

/// Write a Block message and answer its bytes.
pub fn new_block(input: &BlockInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut at_tx_lengths = 0;
    if !input.tx_lengths.is_empty() {
        let mut lb = b.start_list();
        for elem in input.tx_lengths {
            let mut rec = [0u8; SIG_SIZE];
            let n = elem.len().min(SIG_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_tx_lengths = lb.finish_offset();
    }
    let mut ob = b.start_object(BLOCK_SIZE);
    ob.set_u8(&mut b, BLOCK_KIND, input.kind);
    ob.set_bytes_fixed(&mut b, BLOCK_PARENT, input.parent);
    ob.set_u64(&mut b, BLOCK_HEIGHT, input.height);
    ob.set_u64(&mut b, BLOCK_TIME, input.time);
    ob.set_list(&mut b, BLOCK_TX_LENGTHS, at_tx_lengths, input.tx_lengths.len());
    ob.set_bytes(&mut b, BLOCK_TX_BLOB, input.tx_blob);
    ob.set_bytes(&mut b, BLOCK_PROPOSAL_TX, input.proposal_tx);
    ob.finish_as_root(&mut b);
    b.finish()
}

// Import — field offsets, in bytes, and the fixed section's size.
pub const IMPORT_KIND: usize = 0;
pub const IMPORT_NETWORK_ID: usize = 1;
pub const IMPORT_BLOCKCHAIN_ID: usize = 5;
pub const IMPORT_OUTS: usize = 37;
pub const IMPORT_OWNER_ADDRS: usize = 45;
pub const IMPORT_INS: usize = 53;
pub const IMPORT_SIG_INDICES: usize = 61;
pub const IMPORT_MEMO: usize = 69;
pub const IMPORT_SOURCE_CHAIN: usize = 77;
pub const IMPORT_IMPORTED_INS: usize = 109;
pub const IMPORT_IMPORTED_SIGS: usize = 117;
pub const IMPORT_SIZE: usize = 125;

/// A view of a ZAP-encoded Import. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Import<'a> {
    o: zap::Object<'a>,
}

impl<'a> Import<'a> {
    /// Take `data` as a Import message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Import {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Import { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn kind(&self) -> u8 {
        self.o.u8(IMPORT_KIND)
    }

    pub fn network_id(&self) -> u32 {
        self.o.u32(IMPORT_NETWORK_ID)
    }

    /// The 32 inline bytes at `IMPORT_BLOCKCHAIN_ID`; zeros if the span runs off the buffer.
    pub fn blockchain_id(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(IMPORT_BLOCKCHAIN_ID, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn outs(&self) -> OutList<'a> {
        OutList { l: self.o.list_stride(IMPORT_OUTS, OUT_SIZE) }
    }

    pub fn owner_addrs(&self) -> AddrList<'a> {
        AddrList { l: self.o.list_stride(IMPORT_OWNER_ADDRS, ADDR_SIZE) }
    }

    pub fn ins(&self) -> InList<'a> {
        InList { l: self.o.list_stride(IMPORT_INS, IN_SIZE) }
    }

    pub fn sig_indices(&self) -> SigList<'a> {
        SigList { l: self.o.list_stride(IMPORT_SIG_INDICES, SIG_SIZE) }
    }

    pub fn memo(&self) -> &'a [u8] {
        self.o.bytes(IMPORT_MEMO)
    }

    /// The 32 inline bytes at `IMPORT_SOURCE_CHAIN`; zeros if the span runs off the buffer.
    pub fn source_chain(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(IMPORT_SOURCE_CHAIN, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn imported_ins(&self) -> InList<'a> {
        InList { l: self.o.list_stride(IMPORT_IMPORTED_INS, IN_SIZE) }
    }

    pub fn imported_sigs(&self) -> SigList<'a> {
        SigList { l: self.o.list_stride(IMPORT_IMPORTED_SIGS, SIG_SIZE) }
    }
}

/// The field values [`new_import`] writes.
#[derive(Clone, Copy, Debug)]
pub struct ImportInput<'a> {
    pub kind: u8,
    pub network_id: u32,
    pub blockchain_id: &'a [u8; 32],
    pub outs: &'a [&'a [u8]],
    pub owner_addrs: &'a [&'a [u8]],
    pub ins: &'a [&'a [u8]],
    pub sig_indices: &'a [&'a [u8]],
    pub memo: &'a [u8],
    pub source_chain: &'a [u8; 32],
    pub imported_ins: &'a [&'a [u8]],
    pub imported_sigs: &'a [&'a [u8]],
}

impl<'a> Default for ImportInput<'a> {
    fn default() -> Self {
        ImportInput {
            kind: 0,
            network_id: 0,
            blockchain_id: &[0u8; 32],
            outs: &[],
            owner_addrs: &[],
            ins: &[],
            sig_indices: &[],
            memo: &[],
            source_chain: &[0u8; 32],
            imported_ins: &[],
            imported_sigs: &[],
        }
    }
}

/// Write a Import message and answer its bytes.
pub fn new_import(input: &ImportInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut at_outs = 0;
    if !input.outs.is_empty() {
        let mut lb = b.start_list();
        for elem in input.outs {
            let mut rec = [0u8; OUT_SIZE];
            let n = elem.len().min(OUT_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_outs = lb.finish_offset();
    }
    let mut at_owner_addrs = 0;
    if !input.owner_addrs.is_empty() {
        let mut lb = b.start_list();
        for elem in input.owner_addrs {
            let mut rec = [0u8; ADDR_SIZE];
            let n = elem.len().min(ADDR_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_owner_addrs = lb.finish_offset();
    }
    let mut at_ins = 0;
    if !input.ins.is_empty() {
        let mut lb = b.start_list();
        for elem in input.ins {
            let mut rec = [0u8; IN_SIZE];
            let n = elem.len().min(IN_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_ins = lb.finish_offset();
    }
    let mut at_sig_indices = 0;
    if !input.sig_indices.is_empty() {
        let mut lb = b.start_list();
        for elem in input.sig_indices {
            let mut rec = [0u8; SIG_SIZE];
            let n = elem.len().min(SIG_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_sig_indices = lb.finish_offset();
    }
    let mut at_imported_ins = 0;
    if !input.imported_ins.is_empty() {
        let mut lb = b.start_list();
        for elem in input.imported_ins {
            let mut rec = [0u8; IN_SIZE];
            let n = elem.len().min(IN_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_imported_ins = lb.finish_offset();
    }
    let mut at_imported_sigs = 0;
    if !input.imported_sigs.is_empty() {
        let mut lb = b.start_list();
        for elem in input.imported_sigs {
            let mut rec = [0u8; SIG_SIZE];
            let n = elem.len().min(SIG_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_imported_sigs = lb.finish_offset();
    }
    let mut ob = b.start_object(IMPORT_SIZE);
    ob.set_u8(&mut b, IMPORT_KIND, input.kind);
    ob.set_u32(&mut b, IMPORT_NETWORK_ID, input.network_id);
    ob.set_bytes_fixed(&mut b, IMPORT_BLOCKCHAIN_ID, input.blockchain_id);
    ob.set_list(&mut b, IMPORT_OUTS, at_outs, input.outs.len());
    ob.set_list(&mut b, IMPORT_OWNER_ADDRS, at_owner_addrs, input.owner_addrs.len());
    ob.set_list(&mut b, IMPORT_INS, at_ins, input.ins.len());
    ob.set_list(&mut b, IMPORT_SIG_INDICES, at_sig_indices, input.sig_indices.len());
    ob.set_bytes(&mut b, IMPORT_MEMO, input.memo);
    ob.set_bytes_fixed(&mut b, IMPORT_SOURCE_CHAIN, input.source_chain);
    ob.set_list(&mut b, IMPORT_IMPORTED_INS, at_imported_ins, input.imported_ins.len());
    ob.set_list(&mut b, IMPORT_IMPORTED_SIGS, at_imported_sigs, input.imported_sigs.len());
    ob.finish_as_root(&mut b);
    b.finish()
}

// Export — field offsets, in bytes, and the fixed section's size.
pub const EXPORT_KIND: usize = 0;
pub const EXPORT_NETWORK_ID: usize = 1;
pub const EXPORT_BLOCKCHAIN_ID: usize = 5;
pub const EXPORT_OUTS: usize = 37;
pub const EXPORT_OWNER_ADDRS: usize = 45;
pub const EXPORT_INS: usize = 53;
pub const EXPORT_SIG_INDICES: usize = 61;
pub const EXPORT_MEMO: usize = 69;
pub const EXPORT_DEST_CHAIN: usize = 77;
pub const EXPORT_EXPORTED_OUTS: usize = 109;
pub const EXPORT_EXPORTED_ADDRS: usize = 117;
pub const EXPORT_SIZE: usize = 125;

/// A view of a ZAP-encoded Export. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Export<'a> {
    o: zap::Object<'a>,
}

impl<'a> Export<'a> {
    /// Take `data` as a Export message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Export {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Export { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn kind(&self) -> u8 {
        self.o.u8(EXPORT_KIND)
    }

    pub fn network_id(&self) -> u32 {
        self.o.u32(EXPORT_NETWORK_ID)
    }

    /// The 32 inline bytes at `EXPORT_BLOCKCHAIN_ID`; zeros if the span runs off the buffer.
    pub fn blockchain_id(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(EXPORT_BLOCKCHAIN_ID, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn outs(&self) -> OutList<'a> {
        OutList { l: self.o.list_stride(EXPORT_OUTS, OUT_SIZE) }
    }

    pub fn owner_addrs(&self) -> AddrList<'a> {
        AddrList { l: self.o.list_stride(EXPORT_OWNER_ADDRS, ADDR_SIZE) }
    }

    pub fn ins(&self) -> InList<'a> {
        InList { l: self.o.list_stride(EXPORT_INS, IN_SIZE) }
    }

    pub fn sig_indices(&self) -> SigList<'a> {
        SigList { l: self.o.list_stride(EXPORT_SIG_INDICES, SIG_SIZE) }
    }

    pub fn memo(&self) -> &'a [u8] {
        self.o.bytes(EXPORT_MEMO)
    }

    /// The 32 inline bytes at `EXPORT_DEST_CHAIN`; zeros if the span runs off the buffer.
    pub fn dest_chain(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(EXPORT_DEST_CHAIN, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn exported_outs(&self) -> OutList<'a> {
        OutList { l: self.o.list_stride(EXPORT_EXPORTED_OUTS, OUT_SIZE) }
    }

    pub fn exported_addrs(&self) -> AddrList<'a> {
        AddrList { l: self.o.list_stride(EXPORT_EXPORTED_ADDRS, ADDR_SIZE) }
    }
}

/// The field values [`new_export`] writes.
#[derive(Clone, Copy, Debug)]
pub struct ExportInput<'a> {
    pub kind: u8,
    pub network_id: u32,
    pub blockchain_id: &'a [u8; 32],
    pub outs: &'a [&'a [u8]],
    pub owner_addrs: &'a [&'a [u8]],
    pub ins: &'a [&'a [u8]],
    pub sig_indices: &'a [&'a [u8]],
    pub memo: &'a [u8],
    pub dest_chain: &'a [u8; 32],
    pub exported_outs: &'a [&'a [u8]],
    pub exported_addrs: &'a [&'a [u8]],
}

impl<'a> Default for ExportInput<'a> {
    fn default() -> Self {
        ExportInput {
            kind: 0,
            network_id: 0,
            blockchain_id: &[0u8; 32],
            outs: &[],
            owner_addrs: &[],
            ins: &[],
            sig_indices: &[],
            memo: &[],
            dest_chain: &[0u8; 32],
            exported_outs: &[],
            exported_addrs: &[],
        }
    }
}

/// Write a Export message and answer its bytes.
pub fn new_export(input: &ExportInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut at_outs = 0;
    if !input.outs.is_empty() {
        let mut lb = b.start_list();
        for elem in input.outs {
            let mut rec = [0u8; OUT_SIZE];
            let n = elem.len().min(OUT_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_outs = lb.finish_offset();
    }
    let mut at_owner_addrs = 0;
    if !input.owner_addrs.is_empty() {
        let mut lb = b.start_list();
        for elem in input.owner_addrs {
            let mut rec = [0u8; ADDR_SIZE];
            let n = elem.len().min(ADDR_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_owner_addrs = lb.finish_offset();
    }
    let mut at_ins = 0;
    if !input.ins.is_empty() {
        let mut lb = b.start_list();
        for elem in input.ins {
            let mut rec = [0u8; IN_SIZE];
            let n = elem.len().min(IN_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_ins = lb.finish_offset();
    }
    let mut at_sig_indices = 0;
    if !input.sig_indices.is_empty() {
        let mut lb = b.start_list();
        for elem in input.sig_indices {
            let mut rec = [0u8; SIG_SIZE];
            let n = elem.len().min(SIG_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_sig_indices = lb.finish_offset();
    }
    let mut at_exported_outs = 0;
    if !input.exported_outs.is_empty() {
        let mut lb = b.start_list();
        for elem in input.exported_outs {
            let mut rec = [0u8; OUT_SIZE];
            let n = elem.len().min(OUT_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_exported_outs = lb.finish_offset();
    }
    let mut at_exported_addrs = 0;
    if !input.exported_addrs.is_empty() {
        let mut lb = b.start_list();
        for elem in input.exported_addrs {
            let mut rec = [0u8; ADDR_SIZE];
            let n = elem.len().min(ADDR_SIZE);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_exported_addrs = lb.finish_offset();
    }
    let mut ob = b.start_object(EXPORT_SIZE);
    ob.set_u8(&mut b, EXPORT_KIND, input.kind);
    ob.set_u32(&mut b, EXPORT_NETWORK_ID, input.network_id);
    ob.set_bytes_fixed(&mut b, EXPORT_BLOCKCHAIN_ID, input.blockchain_id);
    ob.set_list(&mut b, EXPORT_OUTS, at_outs, input.outs.len());
    ob.set_list(&mut b, EXPORT_OWNER_ADDRS, at_owner_addrs, input.owner_addrs.len());
    ob.set_list(&mut b, EXPORT_INS, at_ins, input.ins.len());
    ob.set_list(&mut b, EXPORT_SIG_INDICES, at_sig_indices, input.sig_indices.len());
    ob.set_bytes(&mut b, EXPORT_MEMO, input.memo);
    ob.set_bytes_fixed(&mut b, EXPORT_DEST_CHAIN, input.dest_chain);
    ob.set_list(&mut b, EXPORT_EXPORTED_OUTS, at_exported_outs, input.exported_outs.len());
    ob.set_list(&mut b, EXPORT_EXPORTED_ADDRS, at_exported_addrs, input.exported_addrs.len());
    ob.finish_as_root(&mut b);
    b.finish()
}

