// Code generated by zapgen; DO NOT EDIT.
// source: xchain.zap

//! ZAP schema `xchain.zap`, package `xchain`.
//!
//! Every view here borrows the buffer it reads: a field is a bounds-checked
//! look at bytes already in hand, never a decode into an owned struct. The
//! builders write into one buffer and hand it over at the end.

#![allow(dead_code)]

use crate::zap;

// Signed — field offsets, in bytes, and the fixed section's size.
pub const SIGNED_UNSIGNED: usize = 0;
pub const SIGNED_CREDENTIAL_COUNT: usize = 8;
pub const SIGNED_CREDENTIAL_BYTES: usize = 12;
pub const SIGNED_SIZE: usize = 20;

/// A view of a ZAP-encoded Signed. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Signed<'a> {
    o: zap::Object<'a>,
}

impl<'a> Signed<'a> {
    /// Take `data` as a Signed message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Signed {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Signed { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn unsigned(&self) -> &'a [u8] {
        self.o.bytes(SIGNED_UNSIGNED)
    }

    pub fn credential_count(&self) -> u32 {
        self.o.u32(SIGNED_CREDENTIAL_COUNT)
    }

    pub fn credential_bytes(&self) -> &'a [u8] {
        self.o.bytes(SIGNED_CREDENTIAL_BYTES)
    }
}

/// The field values [`new_signed`] writes.
#[derive(Clone, Copy, Debug)]
pub struct SignedInput<'a> {
    pub unsigned: &'a [u8],
    pub credential_count: u32,
    pub credential_bytes: &'a [u8],
}

impl<'a> Default for SignedInput<'a> {
    fn default() -> Self {
        SignedInput {
            unsigned: &[],
            credential_count: 0,
            credential_bytes: &[],
        }
    }
}

/// Write a Signed into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_signed(b: &mut zap::Builder, input: &SignedInput<'_>) -> usize {
    let mut ob = b.start_object(SIGNED_SIZE);
    ob.set_bytes(b, SIGNED_UNSIGNED, input.unsigned);
    ob.set_u32(b, SIGNED_CREDENTIAL_COUNT, input.credential_count);
    ob.set_bytes(b, SIGNED_CREDENTIAL_BYTES, input.credential_bytes);
    ob.finish(b)
}

/// Write a Signed message and answer its bytes.
pub fn new_signed(input: &SignedInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_signed(&mut b, input);
    b.set_root(at);
    b.finish()
}

// Base — field offsets, in bytes, and the fixed section's size.
pub const BASE_NETWORK_ID: usize = 0;
pub const BASE_BLOCKCHAIN_ID: usize = 8;
pub const BASE_OUTS: usize = 40;
pub const BASE_INS: usize = 48;
pub const BASE_MEMO: usize = 56;
pub const BASE_SIZE: usize = 64;

/// A view of a ZAP-encoded Base. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Base<'a> {
    o: zap::Object<'a>,
}

impl<'a> Base<'a> {
    /// Take `data` as a Base message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Base {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Base { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn network_id(&self) -> u32 {
        self.o.u32(BASE_NETWORK_ID)
    }

    /// The 32 inline bytes at `BASE_BLOCKCHAIN_ID`; zeros if the span runs off the buffer.
    pub fn blockchain_id(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(BASE_BLOCKCHAIN_ID, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn outs(&self) -> zap::List<'a> {
        self.o.list_stride(BASE_OUTS, 4)
    }

    /// Element `i` of `outs`. Out of range answers the zero view.
    pub fn outs_at(&self, i: usize) -> Ptr<'a> {
        Ptr::new(self.outs().object(i, PTR_SIZE))
    }

    pub fn ins(&self) -> zap::List<'a> {
        self.o.list_stride(BASE_INS, 4)
    }

    /// Element `i` of `ins`. Out of range answers the zero view.
    pub fn ins_at(&self, i: usize) -> Ptr<'a> {
        Ptr::new(self.ins().object(i, PTR_SIZE))
    }

    pub fn memo(&self) -> &'a [u8] {
        self.o.bytes(BASE_MEMO)
    }
}

/// The field values [`new_base`] writes.
#[derive(Clone, Copy, Debug)]
pub struct BaseInput<'a> {
    pub network_id: u32,
    pub blockchain_id: &'a [u8; 32],
    pub outs: &'a [&'a [u8]],
    pub ins: &'a [&'a [u8]],
    pub memo: &'a [u8],
}

impl<'a> Default for BaseInput<'a> {
    fn default() -> Self {
        BaseInput {
            network_id: 0,
            blockchain_id: &[0u8; 32],
            outs: &[],
            ins: &[],
            memo: &[],
        }
    }
}

/// Write a Base into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_base(b: &mut zap::Builder, input: &BaseInput<'_>) -> usize {
    let mut list_outs = b.start_list();
    for elem in input.outs {
        list_outs.add_bytes(b, elem);
    }
    let at_outs = list_outs.finish_offset();
    let mut list_ins = b.start_list();
    for elem in input.ins {
        list_ins.add_bytes(b, elem);
    }
    let at_ins = list_ins.finish_offset();
    let mut ob = b.start_object(BASE_SIZE);
    ob.set_u32(b, BASE_NETWORK_ID, input.network_id);
    ob.set_bytes_fixed(b, BASE_BLOCKCHAIN_ID, input.blockchain_id);
    ob.set_list(b, BASE_OUTS, at_outs, input.outs.len());
    ob.set_list(b, BASE_INS, at_ins, input.ins.len());
    ob.set_bytes(b, BASE_MEMO, input.memo);
    ob.finish(b)
}

/// Write a Base message and answer its bytes.
pub fn new_base(input: &BaseInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_base(&mut b, input);
    b.set_root(at);
    b.finish()
}

// Ptr — field offsets, in bytes, and the fixed section's size.
pub const PTR_OFFSET: usize = 0;
pub const PTR_SIZE: usize = 4;

/// A view of a ZAP-encoded Ptr. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Ptr<'a> {
    o: zap::Object<'a>,
}

impl<'a> Ptr<'a> {
    /// Take `data` as a Ptr message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Ptr {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Ptr { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn offset(&self) -> u32 {
        self.o.u32(PTR_OFFSET)
    }
}

/// The field values [`new_ptr`] writes.
#[derive(Clone, Copy, Debug)]
pub struct PtrInput {
    pub offset: u32,
}

impl Default for PtrInput {
    fn default() -> Self {
        PtrInput {
            offset: 0,
        }
    }
}

/// Ptr as the PTR_SIZE bytes one element of a list holds.
pub fn pack_ptr(input: &PtrInput) -> [u8; PTR_SIZE] {
    let mut r = [0u8; PTR_SIZE];
    r[PTR_OFFSET..PTR_OFFSET + 4].copy_from_slice(&input.offset.to_le_bytes());
    r
}

/// Write a Ptr into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_ptr(b: &mut zap::Builder, input: &PtrInput) -> usize {
    let mut ob = b.start_object(PTR_SIZE);
    ob.set_u32(b, PTR_OFFSET, input.offset);
    ob.finish(b)
}

/// Write a Ptr message and answer its bytes.
pub fn new_ptr(input: &PtrInput) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_ptr(&mut b, input);
    b.set_root(at);
    b.finish()
}

// Block — field offsets, in bytes, and the fixed section's size.
pub const BLOCK_PARENT: usize = 0;
pub const BLOCK_HEIGHT: usize = 32;
pub const BLOCK_TIME: usize = 40;
pub const BLOCK_ROOT: usize = 48;
pub const BLOCK_TX_LENGTHS: usize = 80;
pub const BLOCK_TX_BLOB: usize = 88;
pub const BLOCK_SIZE: usize = 96;

/// A view of a ZAP-encoded Block. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Block<'a> {
    o: zap::Object<'a>,
}

impl<'a> Block<'a> {
    /// Take `data` as a Block message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Block {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Block { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 32 inline bytes at `BLOCK_PARENT`; zeros if the span runs off the buffer.
    pub fn parent(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(BLOCK_PARENT, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn height(&self) -> u64 {
        self.o.u64(BLOCK_HEIGHT)
    }

    pub fn time(&self) -> u64 {
        self.o.u64(BLOCK_TIME)
    }

    /// The 32 inline bytes at `BLOCK_ROOT`; zeros if the span runs off the buffer.
    pub fn root(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(BLOCK_ROOT, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn tx_lengths(&self) -> zap::List<'a> {
        self.o.list_stride(BLOCK_TX_LENGTHS, 4)
    }

    /// Element `i` of `tx_lengths`. Out of range answers the zero view.
    pub fn tx_lengths_at(&self, i: usize) -> Ptr<'a> {
        Ptr::new(self.tx_lengths().object(i, PTR_SIZE))
    }

    pub fn tx_blob(&self) -> &'a [u8] {
        self.o.bytes(BLOCK_TX_BLOB)
    }
}

/// The field values [`new_block`] writes.
#[derive(Clone, Copy, Debug)]
pub struct BlockInput<'a> {
    pub parent: &'a [u8; 32],
    pub height: u64,
    pub time: u64,
    pub root: &'a [u8; 32],
    pub tx_lengths: &'a [&'a [u8]],
    pub tx_blob: &'a [u8],
}

impl<'a> Default for BlockInput<'a> {
    fn default() -> Self {
        BlockInput {
            parent: &[0u8; 32],
            height: 0,
            time: 0,
            root: &[0u8; 32],
            tx_lengths: &[],
            tx_blob: &[],
        }
    }
}

/// Write a Block into `b` and answer where its object landed.
///
/// What a field points AT is written first, in field order, and the
/// fixed section last: a pointer always leads backward, to bytes
/// already placed.
pub fn put_block(b: &mut zap::Builder, input: &BlockInput<'_>) -> usize {
    let mut list_tx_lengths = b.start_list();
    for elem in input.tx_lengths {
        list_tx_lengths.add_bytes(b, elem);
    }
    let at_tx_lengths = list_tx_lengths.finish_offset();
    let mut ob = b.start_object(BLOCK_SIZE);
    ob.set_bytes_fixed(b, BLOCK_PARENT, input.parent);
    ob.set_u64(b, BLOCK_HEIGHT, input.height);
    ob.set_u64(b, BLOCK_TIME, input.time);
    ob.set_bytes_fixed(b, BLOCK_ROOT, input.root);
    ob.set_list(b, BLOCK_TX_LENGTHS, at_tx_lengths, input.tx_lengths.len());
    ob.set_bytes(b, BLOCK_TX_BLOB, input.tx_blob);
    ob.finish(b)
}

/// Write a Block message and answer its bytes.
pub fn new_block(input: &BlockInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let at = put_block(&mut b, input);
    b.set_root(at);
    b.finish()
}

