// Code generated by zapgen; DO NOT EDIT.
// source: xchain.zap

//! ZAP schema `xchain.zap`, package `xchain`.
//!
//! Every view here borrows the buffer it reads: a field is a bounds-checked
//! look at bytes already in hand, never a decode into an owned struct. The
//! builders write into one buffer and hand it over at the end.

#![allow(dead_code)]

use crate::zap;

// Signed — field offsets, in bytes, and the fixed section's size.
pub const SIGNED_UNSIGNED: usize = 0;
pub const SIGNED_CREDENTIAL_COUNT: usize = 8;
pub const SIGNED_CREDENTIAL_BYTES: usize = 12;
pub const SIGNED_SIZE: usize = 20;

/// A view of a ZAP-encoded Signed. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Signed<'a> {
    o: zap::Object<'a>,
}

impl<'a> Signed<'a> {
    /// Take `data` as a Signed message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Signed {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Signed { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn unsigned(&self) -> &'a [u8] {
        self.o.bytes(SIGNED_UNSIGNED)
    }

    pub fn credential_count(&self) -> u32 {
        self.o.u32(SIGNED_CREDENTIAL_COUNT)
    }

    pub fn credential_bytes(&self) -> &'a [u8] {
        self.o.bytes(SIGNED_CREDENTIAL_BYTES)
    }
}

/// The field values [`new_signed`] writes.
#[derive(Clone, Copy, Debug)]
pub struct SignedInput<'a> {
    pub unsigned: &'a [u8],
    pub credential_count: u32,
    pub credential_bytes: &'a [u8],
}

impl<'a> Default for SignedInput<'a> {
    fn default() -> Self {
        SignedInput {
            unsigned: &[],
            credential_count: 0,
            credential_bytes: &[],
        }
    }
}

/// Write a Signed message and answer its bytes.
pub fn new_signed(input: &SignedInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut ob = b.start_object(SIGNED_SIZE);
    ob.set_bytes(&mut b, SIGNED_UNSIGNED, input.unsigned);
    ob.set_u32(&mut b, SIGNED_CREDENTIAL_COUNT, input.credential_count);
    ob.set_bytes(&mut b, SIGNED_CREDENTIAL_BYTES, input.credential_bytes);
    ob.finish_as_root(&mut b);
    b.finish()
}

// Tx — field offsets, in bytes, and the fixed section's size.
pub const TX_KIND: usize = 0;
pub const TX_BASE_TX: usize = 8;
pub const TX_SIZE: usize = 16;

/// A view of a ZAP-encoded Tx. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Tx<'a> {
    o: zap::Object<'a>,
}

impl<'a> Tx<'a> {
    /// Take `data` as a Tx message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Tx {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Tx { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn kind(&self) -> u8 {
        self.o.u8(TX_KIND)
    }

    pub fn base_tx(&self) -> &'a [u8] {
        self.o.bytes(TX_BASE_TX)
    }
}

/// The field values [`new_tx`] writes.
#[derive(Clone, Copy, Debug)]
pub struct TxInput<'a> {
    pub kind: u8,
    pub base_tx: &'a [u8],
}

impl<'a> Default for TxInput<'a> {
    fn default() -> Self {
        TxInput {
            kind: 0,
            base_tx: &[],
        }
    }
}

/// Write a Tx message and answer its bytes.
pub fn new_tx(input: &TxInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut ob = b.start_object(TX_SIZE);
    ob.set_u8(&mut b, TX_KIND, input.kind);
    ob.set_bytes(&mut b, TX_BASE_TX, input.base_tx);
    ob.finish_as_root(&mut b);
    b.finish()
}

// Base — field offsets, in bytes, and the fixed section's size.
pub const BASE_NETWORK_ID: usize = 0;
pub const BASE_BLOCKCHAIN_ID: usize = 8;
pub const BASE_OUTS: usize = 40;
pub const BASE_INS: usize = 48;
pub const BASE_MEMO: usize = 56;
pub const BASE_SIZE: usize = 64;

/// A view of a ZAP-encoded Base. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Base<'a> {
    o: zap::Object<'a>,
}

impl<'a> Base<'a> {
    /// Take `data` as a Base message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Base {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Base { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn network_id(&self) -> u32 {
        self.o.u32(BASE_NETWORK_ID)
    }

    /// The 32 inline bytes at `BASE_BLOCKCHAIN_ID`; zeros if the span runs off the buffer.
    pub fn blockchain_id(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(BASE_BLOCKCHAIN_ID, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn outs(&self) -> TransferableOutList<'a> {
        TransferableOutList { l: self.o.list_stride(BASE_OUTS, 4) }
    }

    pub fn ins(&self) -> TransferableInList<'a> {
        TransferableInList { l: self.o.list_stride(BASE_INS, 4) }
    }

    pub fn memo(&self) -> &'a [u8] {
        self.o.bytes(BASE_MEMO)
    }
}

/// The field values [`new_base`] writes.
#[derive(Clone, Copy, Debug)]
pub struct BaseInput<'a> {
    pub network_id: u32,
    pub blockchain_id: &'a [u8; 32],
    pub outs: &'a [&'a [u8]],
    pub ins: &'a [&'a [u8]],
    pub memo: &'a [u8],
}

impl<'a> Default for BaseInput<'a> {
    fn default() -> Self {
        BaseInput {
            network_id: 0,
            blockchain_id: &[0u8; 32],
            outs: &[],
            ins: &[],
            memo: &[],
        }
    }
}

/// Write a Base message and answer its bytes.
pub fn new_base(input: &BaseInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut at_outs = 0;
    if !input.outs.is_empty() {
        let mut aims = Vec::with_capacity(input.outs.len());
        for elem in input.outs {
            aims.push(b.embed(elem));
        }
        let mut lb = b.start_list();
        for at in &aims {
            lb.add_object_ptr(&mut b, *at);
        }
        at_outs = lb.finish_offset();
    }
    let mut at_ins = 0;
    if !input.ins.is_empty() {
        let mut aims = Vec::with_capacity(input.ins.len());
        for elem in input.ins {
            aims.push(b.embed(elem));
        }
        let mut lb = b.start_list();
        for at in &aims {
            lb.add_object_ptr(&mut b, *at);
        }
        at_ins = lb.finish_offset();
    }
    let mut ob = b.start_object(BASE_SIZE);
    ob.set_u32(&mut b, BASE_NETWORK_ID, input.network_id);
    ob.set_bytes_fixed(&mut b, BASE_BLOCKCHAIN_ID, input.blockchain_id);
    ob.set_list(&mut b, BASE_OUTS, at_outs, input.outs.len());
    ob.set_list(&mut b, BASE_INS, at_ins, input.ins.len());
    ob.set_bytes(&mut b, BASE_MEMO, input.memo);
    ob.finish_as_root(&mut b);
    b.finish()
}

// TransferableOut — field offsets, in bytes, and the fixed section's size.
pub const TRANSFERABLE_OUT_ASSET_ID: usize = 0;
pub const TRANSFERABLE_OUT_OUTPUT: usize = 32;
pub const TRANSFERABLE_OUT_SIZE: usize = 40;

/// A view of a ZAP-encoded TransferableOut. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct TransferableOut<'a> {
    o: zap::Object<'a>,
}

impl<'a> TransferableOut<'a> {
    /// Take `data` as a TransferableOut message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(TransferableOut {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        TransferableOut { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 32 inline bytes at `TRANSFERABLE_OUT_ASSET_ID`; zeros if the span runs off the buffer.
    pub fn asset_id(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(TRANSFERABLE_OUT_ASSET_ID, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn output(&self) -> &'a [u8] {
        self.o.bytes(TRANSFERABLE_OUT_OUTPUT)
    }
}

/// A run of four-byte offsets, each aiming at one TransferableOut.
#[derive(Clone, Copy, Debug)]
pub struct TransferableOutList<'a> {
    l: zap::List<'a>,
}

impl<'a> TransferableOutList<'a> {
    /// How many elements the list holds.
    pub fn len(&self) -> usize {
        self.l.len()
    }

    /// Whether the list holds none.
    pub fn is_empty(&self) -> bool {
        self.l.len() == 0
    }

    /// Element `i`, or the absent TransferableOut past the end.
    pub fn at(&self, i: usize) -> TransferableOut<'a> {
        TransferableOut::new(self.l.object_ptr(i))
    }
}

/// The field values [`new_transferable_out`] writes.
#[derive(Clone, Copy, Debug)]
pub struct TransferableOutInput<'a> {
    pub asset_id: &'a [u8; 32],
    pub output: &'a [u8],
}

impl<'a> Default for TransferableOutInput<'a> {
    fn default() -> Self {
        TransferableOutInput {
            asset_id: &[0u8; 32],
            output: &[],
        }
    }
}

/// Write a TransferableOut message and answer its bytes.
pub fn new_transferable_out(input: &TransferableOutInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut ob = b.start_object(TRANSFERABLE_OUT_SIZE);
    ob.set_bytes_fixed(&mut b, TRANSFERABLE_OUT_ASSET_ID, input.asset_id);
    ob.set_bytes(&mut b, TRANSFERABLE_OUT_OUTPUT, input.output);
    ob.finish_as_root(&mut b);
    b.finish()
}

// TransferableIn — field offsets, in bytes, and the fixed section's size.
pub const TRANSFERABLE_IN_TX_ID: usize = 0;
pub const TRANSFERABLE_IN_OUTPUT_INDEX: usize = 32;
pub const TRANSFERABLE_IN_ASSET_ID: usize = 36;
pub const TRANSFERABLE_IN_INPUT: usize = 68;
pub const TRANSFERABLE_IN_SIZE: usize = 76;

/// A view of a ZAP-encoded TransferableIn. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct TransferableIn<'a> {
    o: zap::Object<'a>,
}

impl<'a> TransferableIn<'a> {
    /// Take `data` as a TransferableIn message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(TransferableIn {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        TransferableIn { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 32 inline bytes at `TRANSFERABLE_IN_TX_ID`; zeros if the span runs off the buffer.
    pub fn tx_id(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(TRANSFERABLE_IN_TX_ID, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn output_index(&self) -> u32 {
        self.o.u32(TRANSFERABLE_IN_OUTPUT_INDEX)
    }

    /// The 32 inline bytes at `TRANSFERABLE_IN_ASSET_ID`; zeros if the span runs off the buffer.
    pub fn asset_id(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(TRANSFERABLE_IN_ASSET_ID, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn input(&self) -> &'a [u8] {
        self.o.bytes(TRANSFERABLE_IN_INPUT)
    }
}

/// A run of four-byte offsets, each aiming at one TransferableIn.
#[derive(Clone, Copy, Debug)]
pub struct TransferableInList<'a> {
    l: zap::List<'a>,
}

impl<'a> TransferableInList<'a> {
    /// How many elements the list holds.
    pub fn len(&self) -> usize {
        self.l.len()
    }

    /// Whether the list holds none.
    pub fn is_empty(&self) -> bool {
        self.l.len() == 0
    }

    /// Element `i`, or the absent TransferableIn past the end.
    pub fn at(&self, i: usize) -> TransferableIn<'a> {
        TransferableIn::new(self.l.object_ptr(i))
    }
}

/// The field values [`new_transferable_in`] writes.
#[derive(Clone, Copy, Debug)]
pub struct TransferableInInput<'a> {
    pub tx_id: &'a [u8; 32],
    pub output_index: u32,
    pub asset_id: &'a [u8; 32],
    pub input: &'a [u8],
}

impl<'a> Default for TransferableInInput<'a> {
    fn default() -> Self {
        TransferableInInput {
            tx_id: &[0u8; 32],
            output_index: 0,
            asset_id: &[0u8; 32],
            input: &[],
        }
    }
}

/// Write a TransferableIn message and answer its bytes.
pub fn new_transferable_in(input: &TransferableInInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut ob = b.start_object(TRANSFERABLE_IN_SIZE);
    ob.set_bytes_fixed(&mut b, TRANSFERABLE_IN_TX_ID, input.tx_id);
    ob.set_u32(&mut b, TRANSFERABLE_IN_OUTPUT_INDEX, input.output_index);
    ob.set_bytes_fixed(&mut b, TRANSFERABLE_IN_ASSET_ID, input.asset_id);
    ob.set_bytes(&mut b, TRANSFERABLE_IN_INPUT, input.input);
    ob.finish_as_root(&mut b);
    b.finish()
}

// Block — field offsets, in bytes, and the fixed section's size.
pub const BLOCK_PARENT: usize = 0;
pub const BLOCK_HEIGHT: usize = 32;
pub const BLOCK_TIME: usize = 40;
pub const BLOCK_ROOT: usize = 48;
pub const BLOCK_TX_LENGTHS: usize = 80;
pub const BLOCK_TX_BLOB: usize = 88;
pub const BLOCK_SIZE: usize = 96;

/// A view of a ZAP-encoded Block. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Block<'a> {
    o: zap::Object<'a>,
}

impl<'a> Block<'a> {
    /// Take `data` as a Block message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Block {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Block { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    /// The 32 inline bytes at `BLOCK_PARENT`; zeros if the span runs off the buffer.
    pub fn parent(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(BLOCK_PARENT, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn height(&self) -> u64 {
        self.o.u64(BLOCK_HEIGHT)
    }

    pub fn time(&self) -> u64 {
        self.o.u64(BLOCK_TIME)
    }

    /// The 32 inline bytes at `BLOCK_ROOT`; zeros if the span runs off the buffer.
    pub fn root(&self) -> &'a [u8; 32] {
        self.o
            .bytes_fixed(BLOCK_ROOT, 32)
            .try_into()
            .unwrap_or(&[0u8; 32])
    }

    pub fn tx_lengths(&self) -> zap::List<'a> {
        self.o.list_stride(BLOCK_TX_LENGTHS, 4)
    }

    pub fn tx_blob(&self) -> &'a [u8] {
        self.o.bytes(BLOCK_TX_BLOB)
    }
}

/// The field values [`new_block`] writes.
#[derive(Clone, Copy, Debug)]
pub struct BlockInput<'a> {
    pub parent: &'a [u8; 32],
    pub height: u64,
    pub time: u64,
    pub root: &'a [u8; 32],
    pub tx_lengths: &'a [&'a [u8]],
    pub tx_blob: &'a [u8],
}

impl<'a> Default for BlockInput<'a> {
    fn default() -> Self {
        BlockInput {
            parent: &[0u8; 32],
            height: 0,
            time: 0,
            root: &[0u8; 32],
            tx_lengths: &[],
            tx_blob: &[],
        }
    }
}

/// Write a Block message and answer its bytes.
pub fn new_block(input: &BlockInput<'_>) -> Vec<u8> {
    let mut b = zap::Builder::new_v2(256);
    let mut at_tx_lengths = 0;
    if !input.tx_lengths.is_empty() {
        let mut lb = b.start_list();
        for elem in input.tx_lengths {
            let mut rec = [0u8; 4];
            let n = elem.len().min(4);
            rec[..n].copy_from_slice(&elem[..n]);
            lb.add_bytes(&mut b, &rec);
        }
        at_tx_lengths = lb.finish_offset();
    }
    let mut ob = b.start_object(BLOCK_SIZE);
    ob.set_bytes_fixed(&mut b, BLOCK_PARENT, input.parent);
    ob.set_u64(&mut b, BLOCK_HEIGHT, input.height);
    ob.set_u64(&mut b, BLOCK_TIME, input.time);
    ob.set_bytes_fixed(&mut b, BLOCK_ROOT, input.root);
    ob.set_list(&mut b, BLOCK_TX_LENGTHS, at_tx_lengths, input.tx_lengths.len());
    ob.set_bytes(&mut b, BLOCK_TX_BLOB, input.tx_blob);
    ob.finish_as_root(&mut b);
    b.finish()
}

