// Code generated by zapgen; DO NOT EDIT.
// source: basetx.zap
// SPDX-License-Identifier: BSD-3-Clause-Eco

#pragma once

#include <array>
#include <cstdint>
#include <expected>
#include <span>
#include <vector>

#include <zap/zap.hpp>

namespace xvm {

class BaseTx;

// Field byte offsets for BaseTx, and the size of its fixed section.
inline constexpr std::int64_t kBaseTxNetworkIDOff = 0;
inline constexpr std::int64_t kBaseTxBlockchainIDOff = 4;
inline constexpr std::int64_t kBaseTxOutsOff = 36;
inline constexpr std::int64_t kBaseTxInsOff = 44;
inline constexpr std::int64_t kBaseTxMemoOff = 52;
inline constexpr std::int64_t kBaseTxSize = 60;

// BaseTx is a zero-copy view into a ZAP-encoded BaseTx message. It borrows the
// bytes it was built over, which must outlive it, and copies no field.
class BaseTx {
  public:
    BaseTx() = default;
    explicit BaseTx(zap::Object o) : o_(o) {}

    bool is_null() const { return o_.is_null(); }
    zap::Object object() const { return o_; }

    std::uint32_t NetworkID() const { return o_.u32(kBaseTxNetworkIDOff); }
    std::span<const std::uint8_t> BlockchainID() const {
        static constexpr std::array<std::uint8_t, 32> zero{};
        const auto b = o_.bytes_fixed(kBaseTxBlockchainIDOff, 32);
        return b.size() == 32 ? b : std::span<const std::uint8_t>(zero);
    }
    zap::List Outs() const { return o_.list(kBaseTxOutsOff); }
    zap::List Ins() const { return o_.list(kBaseTxInsOff); }
    std::span<const std::uint8_t> Memo() const { return o_.bytes(kBaseTxMemoOff); }

  private:
    zap::Object o_;
};

// WrapBaseTx parses b and returns a typed view over it, or says why b is not a
// message. The view borrows b.
inline std::expected<BaseTx, zap::Error> WrapBaseTx(std::span<const std::uint8_t> b) {
    auto m = zap::Message::parse(b);
    if (!m) return std::unexpected(m.error());
    return BaseTx(m->root());
}

// BaseTxInput collects the field values for NewBaseTx. A borrowed field is a view:
// it must outlive the call, not the buffer the call returns.
struct BaseTxInput {
    std::uint32_t NetworkID{};
    std::array<std::uint8_t, 32> BlockchainID{};
    std::vector<std::span<const std::uint8_t>> Outs{};
    std::vector<std::span<const std::uint8_t>> Ins{};
    std::span<const std::uint8_t> Memo{};
};

// NewBaseTx writes a ZAP-encoded BaseTx message into a fresh buffer and returns it.
inline std::vector<std::uint8_t> NewBaseTx(const BaseTxInput& in) {
    zap::Builder b(256, zap::kVersion1);
    auto ob = b.start_object(kBaseTxSize);
    ob.set_u32(kBaseTxNetworkIDOff, in.NetworkID);
    ob.set_bytes_fixed(kBaseTxBlockchainIDOff, std::span<const std::uint8_t>(in.BlockchainID));
    auto outs_list = b.start_list(0);
    for (const auto& elem : in.Outs) {
        outs_list.add_u32(static_cast<std::uint32_t>(elem.size()));
        outs_list.add_bytes(elem);
    }
    ob.set_list(kBaseTxOutsOff, outs_list.finish().first, static_cast<std::int64_t>(in.Outs.size()));
    auto ins_list = b.start_list(0);
    for (const auto& elem : in.Ins) {
        ins_list.add_u32(static_cast<std::uint32_t>(elem.size()));
        ins_list.add_bytes(elem);
    }
    ob.set_list(kBaseTxInsOff, ins_list.finish().first, static_cast<std::int64_t>(in.Ins.size()));
    ob.set_bytes(kBaseTxMemoOff, in.Memo);
    ob.finish_as_root();
    return b.finish();
}

}  // namespace xvm
