// Code generated by zapgen; DO NOT EDIT.
// source: echo.zap

//! ZAP schema `echo.zap`, package `echo`.
//!
//! Every view here borrows the buffer it reads: a field is a bounds-checked
//! look at bytes already in hand, never a decode into an owned struct. The
//! builders write into one buffer and hand it over at the end.

#![allow(dead_code)]

use crate::rpc;
use crate::zap;

// Ping — field offsets, in bytes, and the fixed section's size.
pub const PING_SEQ: usize = 0;
pub const PING_SIZE: usize = 8;

/// A view of a ZAP-encoded Ping. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Ping<'a> {
    o: zap::Object<'a>,
}

impl<'a> Ping<'a> {
    /// Take `data` as a Ping message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Ping {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Ping { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn seq(&self) -> u64 {
        self.o.u64(PING_SEQ)
    }
}

/// The field values [`new_ping`] writes.
#[derive(Clone, Copy, Debug)]
pub struct PingInput {
    pub seq: u64,
}

impl Default for PingInput {
    fn default() -> Self {
        PingInput {
            seq: 0,
        }
    }
}

/// Write a Ping message and answer its bytes.
pub fn new_ping(input: &PingInput) -> Vec<u8> {
    let mut b = zap::Builder::new(256);
    let mut ob = b.start_object(PING_SIZE);
    ob.set_u64(&mut b, PING_SEQ, input.seq);
    ob.finish_as_root(&mut b);
    b.finish()
}

// Pong — field offsets, in bytes, and the fixed section's size.
pub const PONG_SEQ: usize = 0;
pub const PONG_SIZE: usize = 8;

/// A view of a ZAP-encoded Pong. Reading a field costs a bounds check.
#[derive(Clone, Copy, Debug)]
pub struct Pong<'a> {
    o: zap::Object<'a>,
}

impl<'a> Pong<'a> {
    /// Take `data` as a Pong message. Fails only on the wire-level
    /// checks — magic, version, declared size.
    pub fn wrap(data: &'a [u8]) -> Result<Self, zap::Error> {
        Ok(Pong {
            o: zap::Message::parse(data)?.root(),
        })
    }

    /// A view of an object already located in a message — a nested
    /// field, or one element of a list.
    pub fn new(o: zap::Object<'a>) -> Self {
        Pong { o }
    }

    /// The object this view reads.
    pub fn object(&self) -> zap::Object<'a> {
        self.o
    }

    pub fn seq(&self) -> u64 {
        self.o.u64(PONG_SEQ)
    }
}

/// The field values [`new_pong`] writes.
#[derive(Clone, Copy, Debug)]
pub struct PongInput {
    pub seq: u64,
}

impl Default for PongInput {
    fn default() -> Self {
        PongInput {
            seq: 0,
        }
    }
}

/// Write a Pong message and answer its bytes.
pub fn new_pong(input: &PongInput) -> Vec<u8> {
    let mut b = zap::Builder::new(256);
    let mut ob = b.start_object(PONG_SIZE);
    ob.set_u64(&mut b, PONG_SEQ, input.seq);
    ob.finish_as_root(&mut b);
    b.finish()
}

// Echo — method ordinals, the 1-based wire ids. Appending a method
// never moves an earlier one.
pub const ECHO_PING_ORDINAL: u32 = 1;
pub const ECHO_NOTIFY_ORDINAL: u32 = 2;
pub const ECHO_HEALTH_ORDINAL: u32 = 3;
pub const ECHO_SHUTDOWN_ORDINAL: u32 = 4;

/// Ships one Echo call and answers with the response envelope.
pub trait EchoChannel {
    fn call(&mut self, envelope: &[u8]) -> Result<Vec<u8>, rpc::CallError>;
}

/// A typed client for the Echo service. Each call takes a fresh promise;
/// the `_on` form of a method targets an earlier one, so the server
/// chains them without a round trip in between.
#[derive(Debug)]
pub struct EchoClient<C: EchoChannel> {
    channel: C,
    cap: Vec<u8>,
    session: rpc::Session,
}

impl<C: EchoChannel> EchoClient<C> {
    /// A client that issues calls over `channel`, attaching `cap`
    /// (which may be empty) to every request.
    pub fn new(channel: C, cap: &[u8]) -> Self {
        EchoClient {
            channel,
            cap: cap.to_vec(),
            session: rpc::Session::new(),
        }
    }

    /// `ping`, as an originating call.
    pub fn ping(&mut self, req: &[u8]) -> (rpc::Promise, Result<Vec<u8>, rpc::CallError>) {
        self.invoke_ping(rpc::NO_TARGET, req)
    }

    /// `ping`, pipelined on `on`: the server substitutes on's answer for
    /// this call's payload, so it ships before on comes back.
    pub fn ping_on(&mut self, on: rpc::Promise) -> (rpc::Promise, Result<Vec<u8>, rpc::CallError>) {
        self.invoke_ping(on.id, &[])
    }

    fn invoke_ping(&mut self, target: u32, payload: &[u8]) -> (rpc::Promise, Result<Vec<u8>, rpc::CallError>) {
        let p = self.session.next();
        let envelope = rpc::build_request(&rpc::Call {
            method: ECHO_PING_ORDINAL,
            promise_id: p.id,
            target,
            cap: &self.cap,
            payload,
        });
        let answer = match self.channel.call(&envelope) {
            Ok(a) => a,
            Err(e) => return (p, Err(e)),
        };
        let resp = match rpc::parse_response(&answer) {
            Ok(r) => r,
            Err(e) => return (p, Err(e.into())),
        };
        if resp.status != rpc::STATUS_OK {
            return (p, Err(rpc::CallError::Status(resp.status)));
        }
        (p, Ok(resp.body.to_vec()))
    }

    /// `notify`, as an originating call.
    pub fn notify(&mut self, req: &[u8]) -> (rpc::Promise, Result<(), rpc::CallError>) {
        self.invoke_notify(rpc::NO_TARGET, req)
    }

    /// `notify`, pipelined on `on`: the server substitutes on's answer for
    /// this call's payload, so it ships before on comes back.
    pub fn notify_on(&mut self, on: rpc::Promise) -> (rpc::Promise, Result<(), rpc::CallError>) {
        self.invoke_notify(on.id, &[])
    }

    fn invoke_notify(&mut self, target: u32, payload: &[u8]) -> (rpc::Promise, Result<(), rpc::CallError>) {
        let p = self.session.next();
        let envelope = rpc::build_request(&rpc::Call {
            method: ECHO_NOTIFY_ORDINAL,
            promise_id: p.id,
            target,
            cap: &self.cap,
            payload,
        });
        let answer = match self.channel.call(&envelope) {
            Ok(a) => a,
            Err(e) => return (p, Err(e)),
        };
        let resp = match rpc::parse_response(&answer) {
            Ok(r) => r,
            Err(e) => return (p, Err(e.into())),
        };
        if resp.status != rpc::STATUS_OK {
            return (p, Err(rpc::CallError::Status(resp.status)));
        }
        (p, Ok(()))
    }

    /// `health`, as an originating call.
    pub fn health(&mut self) -> (rpc::Promise, Result<Vec<u8>, rpc::CallError>) {
        self.invoke_health(rpc::NO_TARGET, &[])
    }

    /// `health`, pipelined on `on`: the server substitutes on's answer for
    /// this call's payload, so it ships before on comes back.
    pub fn health_on(&mut self, on: rpc::Promise) -> (rpc::Promise, Result<Vec<u8>, rpc::CallError>) {
        self.invoke_health(on.id, &[])
    }

    fn invoke_health(&mut self, target: u32, payload: &[u8]) -> (rpc::Promise, Result<Vec<u8>, rpc::CallError>) {
        let p = self.session.next();
        let envelope = rpc::build_request(&rpc::Call {
            method: ECHO_HEALTH_ORDINAL,
            promise_id: p.id,
            target,
            cap: &self.cap,
            payload,
        });
        let answer = match self.channel.call(&envelope) {
            Ok(a) => a,
            Err(e) => return (p, Err(e)),
        };
        let resp = match rpc::parse_response(&answer) {
            Ok(r) => r,
            Err(e) => return (p, Err(e.into())),
        };
        if resp.status != rpc::STATUS_OK {
            return (p, Err(rpc::CallError::Status(resp.status)));
        }
        (p, Ok(resp.body.to_vec()))
    }

    /// `shutdown`, as an originating call.
    pub fn shutdown(&mut self) -> (rpc::Promise, Result<(), rpc::CallError>) {
        self.invoke_shutdown(rpc::NO_TARGET, &[])
    }

    /// `shutdown`, pipelined on `on`: the server substitutes on's answer for
    /// this call's payload, so it ships before on comes back.
    pub fn shutdown_on(&mut self, on: rpc::Promise) -> (rpc::Promise, Result<(), rpc::CallError>) {
        self.invoke_shutdown(on.id, &[])
    }

    fn invoke_shutdown(&mut self, target: u32, payload: &[u8]) -> (rpc::Promise, Result<(), rpc::CallError>) {
        let p = self.session.next();
        let envelope = rpc::build_request(&rpc::Call {
            method: ECHO_SHUTDOWN_ORDINAL,
            promise_id: p.id,
            target,
            cap: &self.cap,
            payload,
        });
        let answer = match self.channel.call(&envelope) {
            Ok(a) => a,
            Err(e) => return (p, Err(e)),
        };
        let resp = match rpc::parse_response(&answer) {
            Ok(r) => r,
            Err(e) => return (p, Err(e.into())),
        };
        if resp.status != rpc::STATUS_OK {
            return (p, Err(rpc::CallError::Status(resp.status)));
        }
        (p, Ok(()))
    }
}

/// The server contract for Echo. Implement it, then route calls to it
/// with [`dispatch_echo`].
pub trait EchoHandler {
    fn ping(&mut self, req: &[u8]) -> Result<Vec<u8>, rpc::Fault>;
    fn notify(&mut self, req: &[u8]) -> Result<(), rpc::Fault>;
    fn health(&mut self) -> Result<Vec<u8>, rpc::Fault>;
    fn shutdown(&mut self) -> Result<(), rpc::Fault>;
}

/// Read one call envelope, route it by ordinal to `h`, and write the
/// response envelope. An unknown ordinal answers not-found; a handler
/// fault answers internal.
pub fn dispatch_echo<H: EchoHandler>(h: &mut H, envelope: &[u8]) -> Result<Vec<u8>, zap::Error> {
    let call = rpc::parse_request(envelope)?;
    let answer = match call.method {
        ECHO_PING_ORDINAL => match h.ping(call.payload) {
            Ok(body) => rpc::build_response(rpc::STATUS_OK, call.promise_id, &body),
            Err(_) => rpc::build_response(rpc::STATUS_INTERNAL, call.promise_id, &[]),
        },
        ECHO_NOTIFY_ORDINAL => match h.notify(call.payload) {
            Ok(()) => rpc::build_response(rpc::STATUS_OK, call.promise_id, &[]),
            Err(_) => rpc::build_response(rpc::STATUS_INTERNAL, call.promise_id, &[]),
        },
        ECHO_HEALTH_ORDINAL => match h.health() {
            Ok(body) => rpc::build_response(rpc::STATUS_OK, call.promise_id, &body),
            Err(_) => rpc::build_response(rpc::STATUS_INTERNAL, call.promise_id, &[]),
        },
        ECHO_SHUTDOWN_ORDINAL => match h.shutdown() {
            Ok(()) => rpc::build_response(rpc::STATUS_OK, call.promise_id, &[]),
            Err(_) => rpc::build_response(rpc::STATUS_INTERNAL, call.promise_id, &[]),
        },
        _ => rpc::build_response(rpc::STATUS_NOT_FOUND, call.promise_id, &[]),
    };
    Ok(answer)
}

