// Code generated by zapgen; DO NOT EDIT.
// source: echo.zap

package echo

import (
	zap "github.com/zap-proto/go"
)

const (
	pingSeqOff = 0
	pingSize   = 8
)

// Ping is a zero-copy view into a ZAP-encoded Ping message.
type Ping struct{ o zap.Object }

// WrapPing parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapPing(b []byte) (Ping, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Ping{}, err
	}
	return Ping{o: m.Root()}, nil
}

func (t Ping) Seq() uint64 { return t.o.Uint64(pingSeqOff) }

// PingInput collects the field values for NewPing.
type PingInput struct {
	Seq uint64
}

// NewPing builds a ZAP-encoded Ping message from in and returns the bytes.
func NewPing(in PingInput) []byte {
	b := zap.NewBuilder(256)
	ob := b.StartObject(pingSize)
	ob.SetUint64(pingSeqOff, in.Seq)
	ob.FinishAsRoot()
	return b.Finish()
}
