// Code generated by zapgen; DO NOT EDIT.
// source: echo.zap

package echo

import (
	zap "github.com/zap-proto/go"
)

const (
	pongSeqOff = 0
	pongSize   = 8
)

// Pong is a zero-copy view into a ZAP-encoded Pong message.
type Pong struct{ o zap.Object }

// WrapPong parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapPong(b []byte) (Pong, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Pong{}, err
	}
	return Pong{o: m.Root()}, nil
}

func (t Pong) Seq() uint64 { return t.o.Uint64(pongSeqOff) }

// PongInput collects the field values for NewPong.
type PongInput struct {
	Seq uint64
}

// NewPong builds a ZAP-encoded Pong message from in and returns the bytes.
func NewPong(in PongInput) []byte {
	b := zap.NewBuilder(256)
	ob := b.StartObject(pongSize)
	ob.SetUint64(pongSeqOff, in.Seq)
	ob.FinishAsRoot()
	return b.Finish()
}
